kube-reporting/metering-operator

Jenkinsfile, charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/namenode-statefulset.yaml, charts/metering-operator/templates/metering-deployment.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-worker-deployment.yaml, hack/deploy-ci.sh
This should help with our imagePull errors in integration/e2e deployments, which might be caused due to concurrent anonymous image pulls
=> *: Set imagePullSecret for pods in CI

pkg/chargeback/datasources.go, pkg/chargeback/health.go, pkg/chargeback/http.go, pkg/chargeback/operator.go, pkg/chargeback/pprof.go, pkg/chargeback/promsum.go, pkg/chargeback/query.go, pkg/chargeback/reports.go, pkg/chargeback/scheduled_reports.go, pkg/chargeback/util.go
Beginnings of refactoring that reduce the overall interface required for
the HTTP API to work. This will be necessary in the tests that we are
adding for the HTTP API so that can control the behavior as needed.
=> pkg/chargeback: Refactor http.go to rely on *Chargeback less

pkg/chargeback/generate_report.go, pkg/chargeback/health.go, pkg/chargeback/http.go, pkg/chargeback/operator.go, pkg/chargeback/prestostore/importer.go, pkg/chargeback/prestostore/prometheusmetric.go, pkg/chargeback/promsum.go, pkg/presto/db.go, pkg/presto/presto.go, pkg/presto/util.go
Updates querying logic to rely on presto.ExecQueryer instead of
db.Queryer.  The presto.ExecQueryer is a higher level abstraction over
the db.Queryer interface which has an implementation in presto.(*DB).
This higher level abstraction will be easier to fake/mock in tests since
we can avoid having to make the sql.Rows and instead just mock creating
presto.Row objects which are easier to construct.
=> Use presto.ExecQueryer instead of db.Queryer in chargeback package

pkg/chargeback/http_test.go
To make it easier to understand the current HTTP unit test, add comments
detailing what's happening in the test
=> pkg/chargeback: Add comments to TestAPIV1ReportsGet

pkg/chargeback/http_test.go
Simplify the http unit tests a bit by making helpers for creating test
resources instead of having a bool to control if the resource is added
to the indexer store, just use a pointer and if non-nil, add to the
indexer.
Based on #309
=> Refactor HTTP unit test to use helpers

pkg/chargeback/http.go, pkg/chargeback/http_test.go
Adds a sub test for the v1 API endpoint for testing trying to get report
results for a non-existant report. Updates the API to return a 404
response code instead of a 500.
Based on #310
=> Test non-existing report in http unit tests

pkg/apis/chargeback/v1alpha1/scheduled_report.go, pkg/chargeback/aws_usage_hive.go, pkg/chargeback/datasources.go, pkg/chargeback/generate_report.go, pkg/chargeback/health.go, pkg/chargeback/hive.go, pkg/chargeback/reports.go, pkg/chargeback/scheduled_reports.go, pkg/chargeback/storage.go, pkg/hive/table.go
Refactors create table logic and removes the dropTable portion since
it's possible to do separately and many createTable calls don't want to
drop the table. Since most commonly dropping a table happens for
reports, the generateReport method has options for both dropTable and
deleting existing data.
=> pkg/{chargeback,apis}: Support overwriteExistingData in scheduledReports

jenkins/main.groovy, jenkins/vars/testRunner.groovy
Allow skipping specific platforms for e2e/integration tests, and print the PR labels at the beginning of the main job.
=> Improve jenkins flexibility

Makefile
As part of my testing environment for work on the containers, I've created repos under my own name on Quay so that I have a little more room to breathe. This makefile change lets me build and push these images in an easy fashion.
(My eventual goal here is a three-liner to `docker-build-all`, `docker-push-all`, and template a custom values file that contains the images by sha so I can iterate on the image install as quickly as possible.)
=> Makefile: allow customization of base image url

pkg/chargeback/http.go
%v would delegate to %g for floats meaning scientific notation is used
for the display when the number is large enough or small enough. This
forces %f for floats causing decimal representation to be used with
default precision.
=> pkg/chargeback: Always format outputs using decimals for floats

pkg/aws/client.go, pkg/chargeback/prestostore/prometheusmetric.go
I noticed after the weekend my metering instance was being OOM killed periodically. I ran a quick pprof profile and found a lot of the allocations happening in StorePrometheusMetrics. The biggest culprit is keeping a slice of strings containing SQL values before writing to our byte.Buffer, so instead remove the slice, and just write to the buffer instead. 
Additionally, since we usually have a few ReportDataSources and worker go routines are running in small batches, re-using the buffers using a sync.Pool should yield some smaller improvements on general allocation, but total in-use memory would probably remain about the same with sync.Pool improvements. 
Finally, reducing the amount of keys returned by the S3 ListObjects API to 200 should reduce allocations and peek usage when an AWS …
=> Improve memory usage

charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/namenode-statefulset.yaml, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, images/hadoop/datanode-entrypoint.sh
Openshift requires volumes exposed in a image have mounts in the pod,
otherwise docker will try to create the empty dir volume and fail.
Related to https://github.com/openshift/origin/issues/16211#issuecomment-350819976
=> Fix image volumes when deploying to Openshift

Gopkg.lock, charts/metering-operator/templates/custom-resources/report-queries/node-cpu.yaml, charts/metering-operator/templates/custom-resources/report-queries/node-memory.yaml, charts/metering-operator/templates/custom-resources/report-queries/pod-cpu.yaml, charts/metering-operator/templates/custom-resources/report-queries/pod-memory.yaml, pkg/chargeback/http.go, pkg/chargeback/http_test.go, pkg/chargeback/util.go, pkg/chargeback/util_test.go, pkg/presto/util.go, vendor/github.com/stretchr/testify/assert/assertion_format.go, vendor/github.com/stretchr/testify/assert/assertion_forward.go, vendor/github.com/stretchr/testify/assert/assertions.go, vendor/github.com/stretchr/testify/assert/http_assertions.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/requirements.go
Since ReportGenerationQueries can change, always use the PrestoTable columns to query results.
We still need ReportGenerationQuery columns to check the TableHidden metadata for displaying purposes however.
=> Use PrestoTable columns as list of columns when querying results in http API

charts/metering-operator/templates/metering-aws-credentials-secrets.yaml, charts/metering-operator/templates/metering-deployment.yaml, charts/metering-operator/values.yaml, charts/presto/templates/_helpers.tpl, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/templates/presto-aws-credentials-secrets.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-worker-deployment.yaml, charts/presto/values.yaml
This enables us to avoid storing aws credentials in plain text in the metering CRD.
=> Allow passing existing secret with AWS credentials instead of creating a new one

charts/metering-operator/templates/metering-service.yaml, charts/metering-operator/values.yaml, charts/openshift-metering/values.yaml
Allows specifying the metering service should be created as either a
ClusterIP, NodePort, or LoadBalancer type service. Additionally, if the
type is NodePort or LoadBalancer the NodePort can optionally be specified.
=> charts: Support exposing metering service via LoadBalancer or NodePort

charts/metering-operator/templates/metering-auth-proxy-authenticated-emails-secret.yaml, charts/metering-operator/templates/metering-auth-proxy-cookie-secret.yaml, charts/metering-operator/templates/metering-auth-proxy-htpasswd-secret.yaml, charts/metering-operator/templates/metering-auth-proxy-rbac.yaml, charts/metering-operator/templates/metering-config.yaml, charts/metering-operator/templates/metering-deployment.yaml, charts/metering-operator/templates/metering-rbac.yaml, charts/metering-operator/templates/metering-service.yaml, charts/metering-operator/templates/metering-serviceaccount.yaml, charts/metering-operator/templates/route.yaml, charts/metering-operator/values.yaml, manifests/deploy/common-helm-operator-values.yaml, manifests/deploy/generic/alm/metering.0.6.1-latest.clusterserviceversion.yaml, manifests/deploy/generic/helm-operator/metering-helm-operator-role.yaml, manifests/deploy/openshift/alm/metering.0.6.1-latest.clusterserviceversion.yaml, manifests/deploy/openshift/helm-operator/metering-helm-operator-role.yaml, manifests/deploy/tectonic/alm/metering.0.6.1-latest.clusterserviceversion.yaml, manifests/deploy/tectonic/helm-operator/metering-helm-operator-role.yaml
Adds a set of configuration options for adding an extra sidecar
container to the metering pod which is responsible for authenticating
incoming requests to the metering pod and proxying them to the metering
operator container. The auth proxy uses openshift service accounts for
auth and requires that the service account has namespace access to be
allowed to access the metering API. To enable verification of
permissions metering-operator.authProxy.subjectAccessReviewEnabled must
be enabled and the metering service account must have permissions to
create SubjectAccessReview resources (requires a ClusterRole and
ClusterRoleBinding). Currently the metering-helm-operator has support
for creating these RBAC resources, but requires these permissons itself,
which is not yet supported.
=> charts/metering-operator: Support configuring openshift auth proxy to auth metering service

images/chargeback/Dockerfile, images/hadoop/Dockerfile, images/helm-operator/Dockerfile, images/hive/Dockerfile, images/presto/Dockerfile
As part of preparing metering for use in Openshift Origin, we need to use a CentOS base for our images. For now, this is a pretty simple transform of deps, but in the future we'll need to rely less on `curl`ing binaries and `git clone`ing inside the build step.
Also, I swapped `http` mirror urls to `https` while I was in there.
https://jira.coreos.com/browse/MC-197
=> CentOS based Docker images

images/helm-operator/Dockerfile
Download fewer unnecessary packages for building helm and tiller, and build helm instead of downloading a precompiled version.
=> Optimize helm-operator build process

Makefile, jenkins/build.groovy, jenkins/main.groovy
Defaults to rebuilding unless building a PR in jenkins, in which case it
will just use the latest tag from quay.
=> Make rebuilding helm-operator conditional

pkg/apis/metering/v1alpha1/report.go, pkg/apis/metering/v1alpha1/scheduled_report.go, pkg/operator/generate_report.go, pkg/operator/http.go, pkg/operator/http_test.go, pkg/operator/prestostore/importer.go, pkg/operator/prestostore/query.go, pkg/operator/promsum.go, pkg/operator/reports.go, pkg/operator/scheduled_reports.go, test/e2e/main_test.go, test/e2e/report_test.go, test/e2e/scheduled_report_test.go, test/framework/collect.go, test/framework/datasource.go, test/framework/report.go, test/framework/reportgenerationquery.go
If /api/v1/datasources/prometheus/collect is called before the reporting-operator's informer cache contains ReportDataSources then the collection call will result in no metrics being imported.
In e2e this is happening fairly often due to the ReportDataSources being created at the same time as the reporting-operator, meaning the reporting-operator will only see them after it issues it's first resync list on ReportDataSources.
To deal with this, avoid using the cache for the prometheus collect endpoint, and update tests to correctly wait for ReportDataSources to exist.
=> Fix test flakes when ReportDataSources aren't seen by reporting-operator

pkg/operator/promsum.go, test/e2e/report_test.go
Missed a map assignment causing importers created using the non-cached list of ReportDataSources to not get used.
=> Fix on-demand collect to correctly use non-cached ReportDataSources

jenkins/main.groovy, jenkins/vars/testRunner.groovy
We no longer target Tectonic and this isn't providing much value for us,
and the certificates are due to expire in the coming weeks, so this will
just avoid breakage when that occurs.
=> jenkins: Remove deploying integration/e2e to Tectonic cluster

charts/reporting-operator/templates/custom-resources/report-queries/aws-billing.yaml
The report generation query aws-ec2-billing-data is missing a column, which makes reports fail with the error:
```
output: >-
Failed to execute error usage report: presto: query failed (200 OK):
"com.facebook.presto.sql.analyzer.SemanticException: Insert query has
mismatched column types: Table: [varchar, timestamp, timestamp, double,
varchar, varchar, timestamp, timestamp], Query: [varchar, timestamp,
timestamp, double, varchar, varchar, double, timestamp, timestamp]"
phase: Error
```
Just adding the missing column fixes the problem.
=> Added missing column to aws-ec2-billing-data report generation query

pkg/operator/datasources.go, pkg/operator/operator.go, pkg/operator/prestotables.go, pkg/operator/query.go, pkg/operator/queues.go, pkg/operator/reports.go, pkg/operator/scheduled_reports.go
Main improvements are handling of queueing resources when things they
depend on are "ready" (eg: table/view is created), which ensures
resources are reprocessed even without a resync when their initial sync
failed more than 5 times.
Additionally, now sync handlers for different kinds have a different
number of allowed retries before requeues are stopped.
With all of these improvements, this also allows the operator to avoid
triggering sync handlers when a resync occurs and the ResourceVersion of
a resource isn't changed.
Given the reliance on resyncs is largely reduced by the improved sync
handlers queueing their dependents the operators resync interval can be
increased from the current value of 1 minute to something much longer.
For now we'll start with 15 minutes and see how it behaves …
=> Improve sync handlers to requeue dependent resources and updateFuncs now skip queuing unchanged resources

Documentation/report.md, pkg/apis/metering/v1alpha1/scheduled_report.go, pkg/apis/metering/v1alpha1/util/scheduled_report_util.go, pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go, pkg/operator/scheduled_reports.go
This allows configuring a ScheduledReport to have a fixed time range
which it will report on, while still allowing the ScheduledReport to run
forever if `spec.reportingEnd` isn't set.
=> pkg,Documentation: Allow specifying a reportingEnd on ScheduledReports

pkg/operator/datasources.go, pkg/operator/operator.go, pkg/operator/promsum.go, pkg/operator/queues.go
Like ScheduledReports, ReportDataSources had a lot of code to manage
state of Go routines running periodic imports on top of a time.Ticker.
Instead, we can just a delaying queue to requeue our resource for later
when we want to import data from Prometheus again.
=> Change Promsum ReportDataSource periodic collection to use workqueues

cmd/reporting-operator/start.go
Also move rootCmd flags to startCmd
=> cmd: Use ParseFlags directly before SetFlagsFromEnv to properly get merged flags

Documentation/index.md, Documentation/report.md, Documentation/rollup-reports.md
The reports generated with the examples in the docs produce the same output.
I'd like to rendez-vous with you about why we're doing both `<=` and `>=` in general in ReportGenerationQueries by default. I think that's probably a mistake in general, and will lead to things getting miscounted no matter what. After all, even without automated roll-up, there's at least someone somewhere who deals with these reports in chunks, and as it stands we're double-counting every start/end point.
Also, thoughts on what to do about the `data_start`/`data_end` on the aggregated reports? It seems to me that we either have to accept internal gaps that we can't expose on larger scales (how do we propagate the fact that on the 3rd we were missing twenty minutes of data?), fail out, or add a data_period that …
=> Documentation: roll-up report guide & explanation

Dockerfile.reporting-operator
GOPATH sometimes has more than a single directory in the variable, so
use /go assuming our Go base image sets $GOPATH to /go
=> Dockerfile.reporting-operator: Use /go instead of $GOPATH for copying source

charts/presto/templates/_helpers.tpl, charts/presto/templates/hive-common-secrets.yaml
This was incorrectly removed when refactoring presto configuration. This
should enable using S3 again, which previously failed due to auth errors.
=> charts/presto: Add AWS credentials env vars back to hive env helper template

pkg/operator/reports.go
Instead of erroring, we can just recreate the table before running
generating the report.
=> pkg/operator: Handle already started reports missing their table

test/e2e/scheduled_report_test.go, test/framework/collect.go
An hour and a half back is a bit much now especially if Prometheus loses
data it means waiting for at least 1.5 hours worth of data, now we only
have to wait for 5 minutes.
=> test/framework: Change CollectMetricsOnce to collect up to 5 minutes before current time

Documentation/manual-install.md, Makefile, hack/install.sh, hack/lib/init.sh, hack/run-metering-operator-local.sh
Adds a script which allows running tiller and metering-helm-operator
via docker. Updates install script to support skipping creation
of the metering-operator for use with run-metering-operator-local.sh.
export LOCAL_METERING_OPERATOR_RUN_INSTALL to enable it to automatically
run the script specified by $METERING_INSTALL_SCRIPT, or
hack/openshift-install.sh by default, prior to running the operator.
=> hack,Makefile: Add a script to run metering-operator locally

test/e2e/scheduled_report_test.go, test/framework/report.go
Using the current time was a mistake, given that if these run after
other tests, it can drift away from the collected period.
=> test: Set scheduled reportStart/end to a range which definitely was collected

test/e2e/scheduled_report_test.go
Previously we effectively only checked if it was started, but not
necessarily if it has reached the reportingEnd
=> test/e2e: Check that the scheduledReport has reported on the period

manifests/custom-resource-definitions/report.crd.yaml, manifests/custom-resource-definitions/reportdatasource.crd.yaml, manifests/custom-resource-definitions/reportgenerationquery.crd.yaml, manifests/custom-resource-definitions/scheduledreport.crd.yaml
From Kubernetes 1.11 and onwards the API server can tell kubectl what
columns to print in get/describe output:
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/#additional-printer-columns
```
kubectl get reportgenerationqueries,reportdatasources,scheduledreports
NAME                                                                                        VIEW DISABLED   VIEW NAME                                AGE
reportgenerationquery.metering.openshift.io/namespace-cpu-request                           true                                                     28m
reportgenerationquery.metering.openshift.io/namespace-cpu-usage                             true                                                     28m …
```
=> manifests: Add additionalPrinterColumns to CRDs for display purposes

Documentation/writing-custom-queries.md
I didn't elaborate too much here since we link just below that the using-metering guide has more info, but gives an easy solution to a confusing error openshift users of this guide will see.
=> docs: writing custom query for openshift update

manifests/custom-resource-definitions/reportdatasource.crd.yaml, manifests/custom-resource-definitions/reportgenerationquery.crd.yaml, manifests/custom-resource-definitions/reportprometheusquery.crd.yaml
I'm not doing ScheduledReport since we plan to combine it with Report, and report is already short.
This gives us shorter names to use when using kubectl get query reportgenerationqueries and reportprometheusqueries.
Before:
```
kubectl get rgq
error: the server doesn't have a resource type "rgq"
kubectl get rpq
error: the server doesn't have a resource type "rpq"
```
Apply the CRDs:
```
kubectl apply -f manifests/custom-resource-definitions
```
After:
```
kubectl get rgq
NAME                                            VIEW DISABLED   VIEW NAME   AGE
namespace-cpu-request                           true                        48s
namespace-cpu-usage                             true                        48s
namespace-memory-request                        true                        47s …
```
=> manifests: Add short names to long CRDs

charts/reporting-operator/values.yaml
This was basically querying presto every 10 seconds after startup which
is a bit excessive.
=> charts/reporting-operator: Lower readiness probe period

pkg/operator/datasources.go, pkg/operator/prestotables.go, pkg/operator/query.go, pkg/operator/reports.go, pkg/operator/scheduled_reports.go
To ensure we are never mutating the objects returned from the cache,
create the copy immediately after it's retrieved.
=> pkg/operator: Update resource DeepCopies to happen earlier

charts/reporting-operator/templates/custom-resources/report-queries/node-cpu.yaml, charts/reporting-operator/templates/custom-resources/report-queries/node-memory.yaml, charts/reporting-operator/templates/custom-resources/report-queries/pod-cpu.yaml, charts/reporting-operator/templates/custom-resources/report-queries/pod-memory.yaml
Moves the aliasing to a -raw suffixed query and adds a query with
reportingStart/reportingEnd inputs to replace the previous.
=> charts/reporting-operator: Make node-memory/cpu-capacity/allocatable queries filterable

pkg/operator/reporting/validate.go, test/e2e/main_test.go, test/framework/collect.go, test/framework/framework.go, test/framework/reportgenerationquery.go
Previously CollectMetricsOnce blindly assumed all ReportDataSources
should have non-zero metrics, but we're getting to a point where we
aren't always using every ReportDataSource in every e2e env, so we need
the ability to only validate the metric import count for a
ReportDataSource is non-zero if it's a direct dependency of the queries
we're testing.
=> Only validate non-zero imported metric count of ReportDataSources that are dependencies of queries being tested

pkg/apis/metering/v1alpha1/util/scheduled_report_util.go, pkg/operator/query.go, pkg/operator/scheduled_reports.go
The idea here is to surface dependency validation errors to users when a scheduledReport has a reportGenerationQuery which is uninitialized, or has uninitialized ReportDataSource/ReportGenerationQuery dependencies itself.
To test this:
- Modify a reportGenerationQuery and add a non-existent ReportDataSource and/or ReportGenerationQuery to it's spec.reportDataSources or spec.reportQueries field.
- `kubectl edit reportgenerationquery namespace-cpu-usage` then edit the `spec.reportQueries` list to include an item that doesn't exist.
- Create a scheduledReport that uses the above reportGenerationQuery
Query the scheduledReport and check it's status:
```
kubectl get scheduledreport
NAME                            QUERY                    SCHEDULE   RUNNING                     FAILED …
```
=> Set ScheduledReport condition failure if validation fails

hack/e2e-test-runner.sh, jenkins/gke-e2e.groovy, jenkins/gke-integration.groovy, jenkins/main.groovy, jenkins/openshift-e2e.groovy, jenkins/openshift-integration.groovy, jenkins/vars/testRunner.groovy
This updates our pipelines to define a pipeline per environment per test type, making for 4 jobs:
- openshift-integration
- openshift-e2e
- gke-integration
- gke-e2e
This PR updates the re-usable jenkins/vars/testRunner.groovy script so that it's parameterized by the differences in openshift and gke in addition to differences between e2e/integration, and then adds a pipeline file for each job.
=> Run a single e2e/integration test per jenkins job

pkg/operator/scheduled_reports.go
A small fix in validation where we assumed a field was set. Caused a panic when unset.
=> pkg/operator: Validate cron.expression is specified when using cron Schedule

charts/reporting-operator/templates/custom-resources/report-queries/cluster.yaml, charts/reporting-operator/templates/custom-resources/report-queries/node-cpu.yaml, charts/reporting-operator/templates/custom-resources/report-queries/node-memory.yaml, test/e2e/main_test.go
Add 2 new reports that provide views of overall capacity of the cluster.
These new reports support aggregating by setting
spec.inputs.AggregatedReportName to the sub-report to aggregate.
=> charts/reporting-operator: Add ReportGenerationQueries on cluster-wide capacity

pkg/operator/datasources.go
This allows other ReportDataSources to be processed when many are
submitted at the same time like during install or when a group are
created via kubectl apply.
=> pkg/operator: Do not immediately import after creating ReportDataSource table

charts/hdfs/templates/configmap.yaml, charts/hdfs/values.yaml
Currently this configures each pod as as a separate rack. Our default
tolerations disallow pods from running on the same node so this should
suffice.
This makes it so HDFS will actually properly do replication across datanodes. Currently it will not really attempt to replicate because without the network topology script, the nodes all run in the "default rack" which causes them to be considered within a shared failure domain, which means replication isn't done since replications is done across racks to ensure multiple replicas aren't going to be affected by a rack outage. Since we're in the cloud, in Kubernetes we're just considering each node equivalent to a rack.
=> charts/hdfs: Add rack awareness

charts/reporting-operator/templates/custom-resources/report-queries/cluster-capacity.yaml, charts/reporting-operator/templates/custom-resources/report-queries/cluster-usage.yaml, charts/reporting-operator/templates/custom-resources/report-queries/cluster-utilization.yaml, test/e2e/main_test.go
This also updates all these cluster wide reports to use a different input
name matching the query's name so that inputs for sub-report names don't
have overlapping inputs parameters.
Base on #482
=> Add cluster utilization reports that compare usage and capacity

charts/reporting-operator/templates/custom-resources/prom-queries/pod-cpu-usage.yaml, charts/reporting-operator/templates/custom-resources/prom-queries/pod-memory-usage.yaml
I've heard of a double counting report for metering and recently I noticed some
values looked larger than I know they are in the Prometheus UI using these
queries and the built-in Prometheus recording rules.  When I looked in Grafana
I noticed the values were closer to what I expected. They key difference is
Grafana is also not using the recording rules from Prometheus, but is running
the aggregations directly, and I noticed it had container_name!="" in it's
label filters where the recording rules don't and our queries don't either.
When testing these queries manually with container_name!="" I found this to
produce more accurate values that are closer to what I was expecting and
measuring manually.
Also updated these same queries used in upstream recording rules: …
=> charts/reporting-operator: Fix usage query double counting

charts/hdfs/templates/configmap.yaml, charts/presto/templates/hive-scripts-configmap.yaml, charts/presto/templates/presto-coordinator-config.yaml, charts/presto/templates/presto-worker-config.yaml
Use ExitOnOutOfMemoryError instead of OnOutOfMemoryError=kill -9 %p
which doesn't work in a container when the JVM is PID 1 which can't be
killed. Also updates hdfs/hive to use the G1 garbage collector for consistency 
with Presto and be verbose when there are GC pauses or errors. Also enables 
JMX options which provide GC info/metrics. Taken from hadoop-env.sh and hive-env.sh.
=> charts: Set JVM options for hdfs, hive and presto

charts/openshift-metering/values.yaml, charts/operator-metering/values.yaml, charts/presto/templates/presto-coordinator-config.yaml, charts/presto/templates/presto-worker-config.yaml, charts/presto/values.yaml, charts/reporting-operator/templates/reporting-operator-config.yaml, charts/reporting-operator/templates/reporting-operator-deployment.yaml, charts/reporting-operator/values.yaml, cmd/reporting-operator/start.go, pkg/operator/operator.go, pkg/operator/prestostore/prometheusmetric.go
Sets new default for maxQueryLength to 10,000,000 which is around 10Mb (ish)
=> Support setting max query length in presto and reporting-operator

Documentation/install-metering.md, charts/presto/templates/_helpers.tpl, charts/presto/templates/presto-common-config.yaml, charts/presto/templates/presto-coordinator-config.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-worker-config.yaml, charts/presto/templates/presto-worker-deployment.yaml, charts/presto/values.yaml
Allows tweaking various GC settings which is becoming necessary to
optimize the performance of Presto based on resources available.
Fully enable jmx for debugging. This allows using jconsole against
Presto's 8081 port and other Java debugging tool.
Increase presto resource requests/limits slightly
Also fix task configuration values on worker. They were set to use the
spec.presto.coordinator values but need to use the worker values.
=> charts/presto: Make JVM configuration more parameterized and tunable

charts/reporting-operator/templates/custom-resources/report-queries/cluster-capacity.yaml, charts/reporting-operator/templates/custom-resources/report-queries/cluster-usage.yaml
Causes these queries to correctly use the underlying partitions in the ReportDataSources.
=> charts/reporting-operator: Use `dt` column in cluster-capacity queries.

Documentation/common-configuration.md, Documentation/configuring-reporting-operator.md, Documentation/metering-config.md, manifests/metering-config/expose-route.yaml
Adds documentation on how to expose the reporting API so that you can query reports outside of the cluster.
Also documents how to enable the openshift oauth proxy to protect the API when exposing it.
=> Documentation,manifests: Document exposing reporting API outside of cluster

Documentation/configuring-reporting-operator.md
Minor update to include details about assumptions of where Prometheus is located when installing on Openshift and non-Openshift clusters.
=> Document difference between openshift and non-openshift installs for default Promethus URL config

Documentation/common-configuration.md, Documentation/configuring-reporting-operator.md
After moving the content to a new file I forgot to move the link references too.
=> Documentation: Fix broken links in new Exposing the reporting API doc

hack/deploy-continuous-upgrade.sh, jenkins/vars/testRunner.groovy, manifests/reports/cluster-capacity-daily.yaml, manifests/reports/cluster-capacity-hourly.yaml, manifests/reports/cluster-usage-daily.yaml, manifests/reports/cluster-usage-hourly.yaml, manifests/reports/cluster-utilization-daily.yaml, manifests/reports/cluster-utilization-hourly.yaml, manifests/reports/namespace-usage-daily.yaml, manifests/reports/namespace-usage-hourly.yaml
This should ensure we're continuously reportings in the continuous upgrade job.
Future steps would be to run more reports, but also to write tests in Go to validate they produce what we want.
=> manifests,hack,jenkins: Deploy default set of ScheduledReports in continuous-upgrade job

pkg/operator/prestostore/importer.go
Avoid re-allocating a map more than necessary.
=> pkg/operator: Hoist map creation to outer loop for creating metric labels map when converting

pkg/operator/operator.go
I noticed this when I looked in hdfs directly and found a bunch of files in the root of `/operator-metering/storage`. This properly puts health checks in a sub-directory for it's table.
=> pkg/operator: Properly store health checks in subdir of storage location

charts/openshift-metering/requirements.yaml, charts/openshift-metering/values.yaml, charts/operator-metering/requirements.yaml, charts/operator-metering/values.yaml, charts/superset/.helmignore, charts/superset/Chart.yaml, charts/superset/README.md, charts/superset/templates/NOTES.txt, charts/superset/templates/_helpers.tpl, charts/superset/templates/datasources-configmap.yaml, charts/superset/templates/deployment.yaml, charts/superset/templates/env-secret.yaml, charts/superset/templates/ingress.yaml, charts/superset/templates/pvc.yaml, charts/superset/templates/scripts-configmap.yaml, charts/superset/templates/server-config-secret.yaml, charts/superset/templates/svc.yaml, charts/superset/values.yaml, manifests/metering-config/superset.yaml
Allows building visualizations from the reports and raw data available via
Presto.  Disabled by default. Can be enabled by setting spec.superset.enabled
to true in Metering CR.
Based on https://github.com/helm/charts/tree/master/stable/superset
=> Add superset chart for interacting with Presto

manifests/reports/cluster-usage-hourly.yaml
These exist in [manifests/reports/cluster-usage-daily.yaml](https://github.com/operator-framework/operator-metering/blob/master/manifests/reports/cluster-usage-daily.yaml)
=> manifests/reports; Remove duplicate usage reports in hourly usage report file

charts/hdfs/templates/configmap.yaml, charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/namenode-statefulset.yaml, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-scripts-configmap.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/templates/presto-coordinator-config.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-worker-config.yaml, charts/presto/templates/presto-worker-deployment.yaml
Hive/hdfs were unable to write logs with current settings due to
HADOOP_LOG_DIR being unset and the logs attempting to be written to /.
This updates both to set HADOOP_LOG_DIR to $HADOOP_HOME/logs and updates
presto pods to store logs in /var/presto/logs also.
=> charts/{hdfs,presto}: Store presto, hive, hdfs GC logs into an emptyDir

Documentation/configuring-storage.md, charts/presto/templates/_helpers.tpl, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/templates/presto-aws-credentials-secret.yaml, charts/presto/templates/presto-common-config.yaml, charts/presto/values.yaml, manifests/metering-config/s3-storage.yaml
This is to allow not having to pass aws credentials in the Metering CR directly.
=> Enable passing pre-existing secret with AWS credentials to hive/presto

charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/namenode-statefulset.yaml, charts/hdfs/values.yaml, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-worker-deployment.yaml, charts/presto/values.yaml, charts/reporting-operator/templates/reporting-operator-deployment.yaml, charts/reporting-operator/values.yaml
Some pods supported setting affinity (hdfs, and presto) but others didn't, and
nothing supports tolerations yet which is necessary to run on dedicated pools
of nodes. Affinity is useful for improving reliability when nodes fail by
ensuring pods run on different nodes or across AZs.
=> Support setting tolerations and affinity for all pods

charts/reporting-operator/templates/custom-resources/report-queries/aws-billing.yaml, charts/reporting-operator/templates/custom-resources/report-queries/pod-cpu-aws.yaml, charts/reporting-operator/templates/custom-resources/report-queries/pod-memory-aws.yaml, pkg/operator/aws_usage_hive.go
AWS Billing tables are external so we don't want to modify the location
by appending the table's name to the location.
The queries were broken when I previously made the node-cpu/memory-allocatable-raw
queries, which were intended to be the re-usable views, and all queries except the AWS ones
got updated to use the -raw one, so this fixes that as well.
=> Fix AWS ReportDataSource

pkg/operator/query.go, pkg/operator/reporting/validate.go
Use dedicated error struct and functions to allow differentiating between the
kind of error to allow handling different types of dependency validation errors
differently.
=> Improve ReportGenerationQuery dependency validation error handling

charts/reporting-operator/templates/custom-resources/prom-queries/persistentvolumeclaim-capacity.yaml, charts/reporting-operator/templates/custom-resources/prom-queries/persistentvolumeclaim-usage.yaml, charts/reporting-operator/templates/custom-resources/report-queries/persistentvolumeclaim-capacity.yaml, charts/reporting-operator/templates/custom-resources/report-queries/persistentvolumeclaim-usage.yaml, charts/reporting-operator/values.yaml
This is the basic I'm using to figure out my non-raw rgq. I was using pod-memory as one of the examples to look at.
=> reporting-operator: add pvc-usage and capacity

pkg/operator/prestostore/prometheusmetric.go
The previously logic appended a comma when VALUES wasn't written to the
buffer, but this was broken when nothing else can be written due to the
size of the metric.
Also avoids running INSERT INTO without any values which could occur
previously if the buffer was too small.
=> pkg/operator: Don't add comma unless a new metric is being added to buffer

Makefile
Fail early if e2e/integration can't be compiled after running unit tests.
=> Makefile: Try to compile e2e/integration tests in test target

Documentation/dev/builds.md, hack/ocp-util/ocp-metering-chart-values.yaml
The intention of this is to make it so someone else could find everything they need related to how our OCP images get built. I still intend to write down a full section on how to make a release, but not everything is done yet so it's difficult to write that currently.
=> Documentation: Document where images are built for origin/OCP

charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/values.yaml
This should at least cause the pods to restart if they get to a point where we're unable to talk to the thrift RPC port. Overall it's still a very simple liveness and readiness check that we should look to improve, but I believe something here is better than nothing.
=> charts/presto: Configure hive server and metastore readiness/liveness probes

charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml
To allow pulling private images for Hive such as the OCP images.
=> charts/presto: Set imagePullSecrets for hive statefulsets

charts/hdfs/templates/configmap.yaml
OCP image builds only have jq 1.3 so use a reduce instead of all function since jq 1.3
doesn't have the all function.
=> charts/hdfs: Support older jq versions

Documentation/configuring-reporting-operator.md, charts/openshift-metering/templates/rolebindings.yaml, charts/openshift-metering/templates/roles.yaml, charts/openshift-metering/values.yaml, charts/reporting-operator/templates/reporting-operator-deployment.yaml, charts/reporting-operator/values.yaml, manifests/metering-config/advanced-auth.yaml, manifests/metering-config/expose-route.yaml
- Adds support for creating rolebindings granting access to various metering resources via roles.
- Changes permissions required to query reporting API with authentication enabled from GET namespaces to GET reports/export sub-resource.
- Adds support for granting permission to reporting API by creating a rolebinding which grants the reports/export GET permission.
=> Improve authorization support

charts/openshift-metering/templates/monitoring-rbac.yaml, charts/openshift-metering/templates/presto-service-monitor.yaml, charts/openshift-metering/templates/reporting-operator-service-monitor.yaml, charts/openshift-metering/values.yaml, hack/openshift-install.sh, manifests/deploy/common-helm-operator-values.yaml, manifests/deploy/openshift/alm/metering.0.12.0-latest.clusterserviceversion.yaml, manifests/deploy/openshift/helm-operator/metering-operator-role.yaml
Take advantage of the new multi-namespace watch feature of
cluster-monitoring and prometheus-operator.
Moves the ServiceMonitors to be openshift-metering chart and sets them
to be created by default. Adds creates rbac polices that enable
Prometheus to perform it's kubernetes service discovery to discover
scrape targets.
Updates openshift install script to label namespace for scraping by Prometheus.
=> manifests,charts,hack: Move ServiceMonitors to openshift-metering chart

charts/openshift-reporting/templates/report-queries/pod-volume-request.yaml
Changed direct array reference in pvc-request ReportGenerationQuery to use element_at
=> Bugfix: PVC Request ReportGenerationQuery Storageclass

charts/presto/templates/_helpers.tpl, charts/presto/values.yaml
This only effects hive, so it should be a config value under
spec.presto.spec.presto.config instead of spec.presto.spec.hive.config
=> charts/presto: move hive metastore timeout config into presto config

charts/presto/templates/hive-configmap.yaml, charts/presto/values.yaml
Used by hive server clients to communicate with hive metastore
=> charts/presto: Support configuring hive metastore client timeout

images/helm-operator/run-operator.sh
Return empty when the number of configmaps to delete is less than
$RELEASE_HISTORY_LIMIT
=> images/helm-operator: Handle less than $RELEASE_HISTORY_LIMIT configmaps

charts/openshift-metering/templates/monitoring-rbac.yaml, charts/openshift-metering/values.yaml
Also renames them to have a metering-prefix to make conflicts with other
default role/rolebinding names less likely.
=> charts/openshift-metering: Add config option to disable creating prometheus rbac resources

Documentation/manual-install.md, hack/run-local-with-port-forward.sh
lets you do things like connecting to the telemeter integration script's telemeter prometheus:
Run a telemeter prometheus instance (from within the openshift/telemeter repo):
```
make
./test/integration.sh http://localhost:9005
```
Create the resources:
```
apiVersion: metering.openshift.io/v1alpha1
kind: ReportPrometheusQuery
metadata:
name: "time"
labels:
operator-metering: "true"
spec:
query: |
time()
---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
labels:
operator-metering: "true"
name: time
spec:
awsBilling: null
promsum:
query: time
---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
name: "time"
labels:
operator-metering: "true"
spec:
reportDataSources:
- "time"
reportQueries:
- "time"
columns: []
query: ""
```
In …
=> reporting-operator-local: allow custom prom host

Makefile
In openshift CI our Dockerfile gets rewritten, and the .dockerfileignore isn't copied either. So restrict the `make verify` diff to files we expect to change after re-generating manifests and running go fmt.
=> Makefile: Restrict `make verify` diff to specific files/directories

Documentation/configuring-reporting-operator.md, Documentation/metering-config.md, charts/reporting-operator/templates/reporting-operator-config.yaml, charts/reporting-operator/templates/reporting-operator-deployment.yaml, charts/reporting-operator/templates/reporting-operator-prometheus-bearer-token-secrets.yaml, charts/reporting-operator/values.yaml
I'm not particularly happy with the configuration structure for bearer tokens now that we have three options, two intertwined, for bearer config. 
Would it be better perhaps to refactor into something more like the TLS config:
```
prometheusBearer:
tokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token" 
token: null # "my_token_here"
createSecret: false
tokenSecretName: reporting-operator-prometheus-bearer-secrets
```
?
I'm also not particularly happy with that, since it still leads to awkward-feeling options between the tokenFile and the rest of the options that are specifically about the secret.
Thoughts?
=> reporting-operator: use secret for token config

hack/capture-pod-logs.sh, hack/e2e-test-runner.sh, hack/lib/util.sh, jenkins/vars/testRunner.groovy
This basically moves the logic into the test runner script and puts each pod description and pod log into a seperate file instead of 1 huge log file which was getting difficult to sift through. I removed the log collection from the jenkins side since it failing without logs due to the script failing is fairly rare, and in origin CI, our script is the only thing which can collect the logs.
=> hack: improve capturing pod logs in e2e tests

test/testhelpers/assert.go
Use assert.Equal for zero values since assert.InEpsilon cannot be used when expectedValue is zero
=> test/testhelpers: Handle when results have zero as comparison column

images/helm-operator/run-operator.sh
Prevents it from never trying again upon failures
=> images/helm-operator: Only store resource version after helm upgrade succeeds

test/integration/report_test.go
Retrieve and store actual results before opening expected reports so
that results can be seen even if expected results isn't currently known.
This makes updating and adding new integration tests easier and less
confusing.
=> test/integration: Retrieve actual results before opening expected results file

pkg/operator/datasources.go
Correctly take length of metrics, not processedTimeRanges to get number
of results imported.
This is because line 628 `firstMetric := results.Metrics[0]` panics when metrics is empty. In PR #610 we changed from using `results.ProcessedTimeRanges` to `results.Metrics` but forgot to change what slice numResultsImported used.
=> pkg/operator: Fix panic when there are no metrics imported

test/testhelpers/assert.go
Expected comes before actual in the arguments.
=> test: Fix order of assert.Equal arguments

charts/metering-ci/templates/metering.yaml, hack/e2e-test-runner.sh, jenkins/vars/testRunner.groovy, test/e2e/main_test.go
Because 4.0 tests are run against brand new clusters, we can't expect there to
be 2 hours with of data already in monitoring. Instead, use less data, and run
a scheduled report with a more frequent schedule using the cron period
configuration.
This is based on #410 as it changes how tests run dramatically and this leverages the new functionality.
=> Update e2e for running against origin CI/4.0 clusters

hack/deploy.sh
Fix the ` Cannot iterate over null (null)` that occur in the deploy script.
=> hack/deploy.sh: Fix jq cannot iterate over null errors

Dockerfile.src, Makefile, jenkins/vars/testRunner.groovy
Remove source from Dockerfile.src, so we mount/check it out in builds and tests as needed.
=> Dockerfile.src,jenkins: Move checkout of code to happen via jenkins in the container

Documentation/report.md, manifests/custom-resource-definitions/reportdatasource.crd.yaml, pkg/apis/metering/v1alpha1/report_datasource.go, pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go, pkg/operator/datasources.go, pkg/operator/prestostore/query.go, pkg/operator/reports.go, test/integration/main_test.go
When spec.runImmediately is true, it should cause the report to run, regardless of data collected.
Additionally, the status message now provides more details on why a dependency isn't met.
=> Improve validation of Report data dependency checks and fix runImmediately

charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/namenode-statefulset.yaml
Makes it easier to query a specific hdfs pod or service by role, and matches
how we label presto and hive components also.
=> charts/hdfs: Add hdfs label to hdfs resources

Dockerfile.metering-operator, Dockerfile.metering-operator.rhel, Dockerfile.src, charts/helm-operator/templates/deployment.yaml, charts/helm-operator/values.yaml, images/helm-operator/run-operator.sh, manifests/deploy/common-helm-operator-values.yaml, manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml, manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
Also updates Dockerfiles to use a newer kubectl by using the `oc` binary as kubectl. Need a newer version to allow patching CRDs. Currently only kubectl 1.5.2 is available in centos/rhel repos.
The idea is this can be used to determine if a Metering operator has reacted to an update in the spec, as currently you cannot tell without looking at what's been deployed.
=> Write resourceVersion used to Metering CR status

Documentation/report.md, pkg/operator/reports.go
Automatically determine the next full reportingPeriod after the current
time when spec.reportingStart is unset.
Closes #641
=> Documentation,pkg/operator: Make Report spec.reportingStart optional again.

pkg/operator/http.go, pkg/operator/http_test.go, pkg/operator/promsum.go
This is an initial step to make it easier to backfill historical data after installation. This allows manually triggering data collect for a single ReportDataSource. Currently we only have an API for triggering a  collection for all reportDataSources.
=> pkg/operator: Allow triggering ReportDataSource collection for individual ReportDataSource

charts/presto/templates/presto-catalog-config-secret.yaml, charts/presto/values.yaml
I tested this manually out, and it works. I'm throwing this up @JooyoungJeong can try to access MySQL in Presto/metering. Currently it has no integration with anything, but my WIP rewrite of storage and table CRs will help with that sooner.
The idea is you could specify extra configuration for (Presto connectors)(https://prestodb.github.io/docs/current/connector.html) by providing a metering config like so:
```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
name: "operator-metering"
spec:
presto:
spec:
presto:
image:
tag: pr-650
config:
connectors:
extraConnectorFiles:
- name: "mysql.properties"
content: |
connector.name=mysql
connection-url=jdbc:mysql://example.net:3306
connection-user=root
connection-password=secret
```
=> charts/presto: Add initial support for configuring extra Presto connectors

test/e2e/main_test.go, test/e2e/report_test.go, test/framework/datasource.go
Improves e2e reliability by looking at the datasources for each Report, and finding a time that all reportDataSources for the Report have in common, and uses that as the reportingStart, and sets reportingEnd to 5 minutes after that. This ensures e2e always runs using a period of time that is covered by the ReportDataSources.
=> test/e2e: Check ReportDataSources for EarliestImportedMetricTime to determine reportStart

cmd/reporting-operator/start.go
55a6117a5ae4803d67508a08199c4f9074b05664 changed the default
metrics port accidently, this changes it back to it's old value.
Currently 8081 is used for oauth-proxy when running with auth enabled,
and this causes a port conflict with the current default.
=> cmd/reporting-operator: Fix port conflict with auth-proxy

Documentation/manual-olm-install.md, Documentation/olm-install.md
Rendered version: https://github.com/chancez/operator-metering/blob/olm_install_admin_console_doc/Documentation/olm-install.md
Two commits so that git sees the rename as a rename rather than a diff.
Github renders it as a diff changing the original file so probably best to view the rendered version or use the split diff viewer.
=> Documentation: Add documentation covering how to install using the Openshift OperatorHub

Dockerfile.src, hack/scl-operator-courier.sh
Also adds a wrapper script for using operator-courier within the
python36 software collection chroot.
=> Dockerfile.src,hack: Add operator-courier to src image

pkg/operator/datasources.go, pkg/operator/http.go, pkg/operator/reports.go, pkg/operator/storage.go
This would remove an unneeded `else` condition when the accompanied `if` statement returns a value.
Removes any declared type when initializing a variable using the `var` keyword.
=> pkg/operator: Fix small linting errors and remove unneeded code.

Makefile, pkg/operator/datasources.go, pkg/operator/operator.go, pkg/operator/prestostore/prometheusmetric.go, pkg/operator/reports.go
Fixes some errors reported by go vet. The copylock ones could be potentially
cause panics. I added this to our Makefile's verify target to ensure we keep
things correct.
=> Fix go vet errors

charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-capacity.yaml, charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-usage.yaml
Be compatible with newer versions of kube/prometheus which uses
"namespace" instead of "exported_namespace" in it's
kubelet_volume_stats_* metrics.
=> Use `namespace` label if `exported_namespace` metric label is missing in PVC queries

pkg/operator/prestostore/query.go
We were overwriting the metrics slice in importResults rather than appending to it, this fixes that. We also sort sooner to ensure the metricBegin/metricsEnd log message fields are accurate.
=> pkg/operator: Fix metrics importing tracking

charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/service-account.yaml, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/templates/hive-serviceaccount.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-serviceaccount.yaml, charts/presto/templates/presto-worker-deployment.yaml
Found by templating the charts out and running everything through
kubectl apply --dry-run.
=> charts/*: Fix invalid configurations in helm charts.

pkg/operator/http_test.go, pkg/operator/reporting/validate_test.go, pkg/operator/reports.go, pkg/operator/reports_test.go, test/testhelpers/helpers.go
Currently, in the `runReport(..)` function in pkg/operator/reports.go, we check the report parameter's running condition. This change would move those checks into a separate function and adds unit tests to verify that the function works as intended.
=> pkg/operator: Refactor the checks/validations in runReport into individual functions and add their unit tests.

pkg/operator/reports.go, pkg/operator/reports_test.go
Currently based off of #697. Same idea as that PR - refactor portions of `runReport` into their own function with the intent of being able to unit tests those functions.
There's a `panic` call when the built-up `reportPeriod` struct contains an invalid start and end period, so I used `assert.Panics()` to test this, but there may be better way to achieve this.
=> pkg/operator: Refactor getting a report's reportPeriod into its own function and add unit tests.

pkg/operator/reportingutil/util.go
Only compare to uppercased column types, do not change the original value.
Fixes a warning when the http code compares ReportQuery columns to
Presto columns:
```
time="2019-05-09T18:43:55Z" level=debug msg="mismatched columns, PrestoTable columns: [{period_start TIMESTAMP} {period_end TIMESTAMP} {namespace VARCHAR} {pod_usage_cpu_core_seconds DOUBLE} {pod_request_cpu_core_seconds DOUBLE} {pod_cpu_usage_percent DOUBLE} {pod_cpu_request_percent DOUBLE} {total_cluster_capacity_cpu_core_seconds DOUBLE}], ReportQuery columns: [{period_start timestamp} {period_end timestamp} {namespace varchar} {pod_usage_cpu_core_seconds double} {pod_request_cpu_core_seconds double} {pod_cpu_usage_percent double} {pod_cpu_request_percent double} {total_cluster_capacity_cpu_core_seconds double}]" app=metering …
```
=> pkg/operator: Do not return uppercased column types

charts/openshift-metering/templates/reporting-operator/reporting-operator-prometheus-certificate-authority-config.yaml
The value must be quoted since it is multiple lines
=> charts: Fix custom Prometheus CA configmap

hack/openshift-install.sh
oc fails with openshift- namespaces when using oc project, and also
mutates your kubeconfig which isn't great.
=> hack: Just use kubectl to create the namespace instead of `oc project`

charts/metering-helm-operator/values.yaml, manifests/deploy/openshift/metering-helm-operator/metering-operator-role.yaml, manifests/deploy/openshift/olm/bundle/4.1/meteringoperator.v4.1.0.clusterserviceversion.yaml
Since we use `oc` aliased to `kubectl` in the metering-operator image,
it defaults to querying using the authorization.openshift.io API group
instead of rbac.authorization.k8s.io so we should grant permissions to
both groups so metering-operator can manage RBAC without having to fully
qualify RBAC resources with an apiGroup.
=> metering-operator: Grant access to openshift authorization apis

charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/templates/presto/presto-catalog-config-secret.yaml
These connectors are useful for testing and debugging have little extra cost to enable by default.
=> charts/openshift-metering: Configure Presto blackhole, memory, tpcds, and tpch connectors

pkg/operator/datasources.go, pkg/operator/reporting/templates.go, pkg/operator/reportingutil/util.go, pkg/operator/reports.go
This aims to make the API surface of the templating code simpler by removing some struct fields we only use certain parts of, primarily the ReportQuery.
=> pkg/operator: Reduces template rendering use of report query fields.

pkg/operator/datasources.go
Was previously producing an invalid ownerRef because the GCK didn't match the information used for the name/UID of the owning resource. This can cause the kube GC to delete the PrestoTables created due to the invalid owner not existing.
=> pkg/operator: Fix ownerReference GVK for ReportQueryView ReportDataSources

pkg/operator/datasources.go, pkg/operator/http.go, pkg/operator/http_test.go, pkg/operator/promsum.go, pkg/operator/reporting/templates.go, pkg/operator/reporting/templates_test.go, pkg/operator/reportingutil/util.go, pkg/operator/reports.go, test/testhelpers/helpers.go
Currently, I need to add more test cases, clean up the code, and potentially move the test helper functions to a separate file. 
These unit tests would handle the validation of a ReportQuery's templating.
Also added a check for the return of `reportingutil.FullyQualifiedTableName` as I was able to get the function to return `..initialized_datasource`, which would result in invalid SQL (i.e. `SELECT * FROM ..initialized_datasouce`. This could either be moved to a function or have the function do the check to eliminate the code repetition.
=> pkg/operator: Add unit-tests for ReportQuery templating.

Dockerfile.metering-ansible-operator, images/helm-operator/deploy-resources.sh, images/metering-ansible-operator/deploy/clusterrole.yaml, images/metering-ansible-operator/deploy/clusterrolebinding.yaml, images/metering-ansible-operator/deploy/role.yaml, images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml, images/metering-ansible-operator/watches.yaml
Manually tested by editing the deployment to use my own custom image of metering-ansible-operator.
This updates metering-ansible-operator to run the deploy-resources.sh script that metering-helm-operator currently uses to deploy the metering stack.
As a follow up, this script can be translated into ansible roles and tasks that accomplish the same logic directly.
=> metering-ansible-operator: Run deploy-resources.sh in meteringconfig role

Makefile, hack/ocp-util/ocp-build-vars.sh, hack/ocp-util/ocp-image-pull-and-rename.sh, hack/ocp-util/redhat.repo
Support using imagebuilder for docker image builds via Makefile, and
update scripts to handle pulling latest bases.
For example, this allows building OCP images locally (must be on RH network and your docker daemon trust the brew-pulp docker registry):
```
./hack/ocp-util/ocp-image-pull-and-rename.sh
make docker-build-all OCP_BUILD=true
```
=> hack/ocp-util,Makefile: Update utilities/files for local ocp image builds

charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, cmd/reporting-operator/start.go, images/helm-operator/deploy-resources.sh, pkg/operator/operator.go
Currently, the presto coordinator and worker pods communicate using http. With this change, the presto components can communicate using https when specified in the configurations, or by default, http.
You would need to specify key/cert pem files, which are then used to create a java keystore file and provided to presto.
=> charts/openshift-metering: Update the reporting-operator and Presto StatefulSets to use TLS when specified

charts/openshift-metering/templates/presto/presto-common-config.yaml
The chart config file doesn't always have a trailing newline so
appending to the presto config files in the entrypoint was appending to
the last line, rather than adding a new configuration option on it's own
line, causing some options to be applied.
This fixes this issue by always appending a newline to the config files
we modify before appending any configuration options.
=> charts: Fix missing newline in presto configs

charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml
As recommended by the presto deployment documentation.
=> charts: Add ReservedCodeCacheSize and jdk.nio.maxCachedBufferSize to presto JVM options

charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, cmd/reporting-operator/start.go, pkg/operator/operator.go
There are a couple more things that need to be fleshed out - most notably the ordering of the TLS/auth (`.Values.presto.spec.presto.config.*.enabled` in `values.yaml`) and what we want the default behavior to be when TLS is enabled and auth is not, and vice-versa. 
The current state of this PR is was constructed under the assumption that we want to be able to configure authentication only if TLS is also enabled (which is reflected as a nested helm if-conditional  templating). It's also important to note that we recently upgraded our Presto fork to a much newer version. This version allows us to specify PEM formatted certificates/keys to Presto, where before we needed to provide JKS/PKCS files (and had to convert the PEM files in the pre-existing secrets, to JKS keystores/truststores.) …
=> Add support for configuring TLS authentication for Presto components by providing pre-existing secrets containing server, client, and CA resources.

images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
The marketplace publishing pipeline managed by RCM/ART does string replacement of the image values in the CSV manifest, and currently we expose those as environment variables to the metering-ansible-operator for this exact purpose.
This updates the role to use those variables as the default values for our component images.
=> Support configuring default component images from environment variables to metering-ansible-operator

charts/metering-ci/templates/metering.yaml, charts/metering-ci/values.yaml, hack/deploy-e2e.sh
I noticed CI fail once because presto coordinator was stuck pending due to not enough CPU resources. removing limits and lowering request may potentially help.
=> charts,hack: Set presto resource requests lower and remove limits for CI tests

pkg/operator/aws_usage_hive.go, pkg/operator/datasources.go, pkg/operator/hive_test.go, pkg/operator/hivetables.go, pkg/operator/http.go, pkg/operator/http_test.go, pkg/operator/prestotables.go, pkg/operator/promsum.go, pkg/operator/queues.go, pkg/operator/reporting/templates_test.go, pkg/operator/reporting/validate.go, pkg/operator/reportingutil/util.go, pkg/operator/reportquery.go, pkg/operator/reports.go, pkg/operator/reports_test.go, pkg/operator/storage.go, pkg/operator/storagelocations.go, test/e2e/main_test.go, test/e2e/report_test.go, test/framework/datasource.go, test/framework/framework.go, test/framework/report.go, test/testhelpers/helpers.go
Used `find pkg/ test/ -type f -exec sed -i 's/cbTypes/metering/g' {} \;` and `grep -nrw . -e "cbTypes"` to find all the occurences. 
The remaining import identifiers are most likely the generated files in the `pkg/` directory, and inconsistently named ones like `meteringv1alpha`.
=> Update and normalize outdated import identifiers for the metering v1alpha package

charts/openshift-metering/templates/presto/presto-common-config.yaml
This was problematic if the user had enabled TLS, but not authentication as the `...config.tls.enabled` conditional would never be evaluated as it's nested under the `...config.auth.enabled` conditional, which would evaluate to false.
=> charts/openshift-metering: Fix the ordering of TLS/Auth tasks in the presto-common-config.yaml.

images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
`item` was already used in a task higher up in the stack, this changes
the loop_var in prune_resources.yml to avoid a conflict.
=> metering-ansible-operator: Use different loop_var for prune_resources.yml

images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
Previously we used async because we looped over each resource to create/delete which caused deploy times to take too long.
We don't need the async tasks anymore now that we submit multiple resources to created/deleted at the same time instead of looping individual resources.
Closes #744
=> Stop using async ansible tasks

charts/openshift-metering/templates/hdfs/hdfs-configmap.yaml, charts/openshift-metering/templates/hdfs/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/presto/hive-scripts-configmap.yaml, charts/openshift-metering/templates/presto/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml
Ensures these files end up in an emptyDir so that we can inspect these
errors in case of an JVM OOM or other JVM fatal error.
=> charts: Set java HeapDumpPath and ErrorFile for JVM based components

charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, cmd/reporting-operator/start.go, pkg/operator/operator.go
Previously we used the passed the same CA to the `RootCAs` and `ClientCAs` field to the custom http client. This wouldn't work if the user provided client and server certificates that were signed by different certificate authorities.
=> Update the Presto and reporting-operator charts to handle a user providing client/server certificates that were signed by different CAs.

charts/openshift-metering/templates/presto/presto-auth-secrets.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-tls-secrets.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-tls-secrets.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
This would update the Presto TLS/auth fields in the helm templating default values that the `MeteringConfig`. 
In the initial state of this PR, a user can specify a secret by populating the `secretName` field in the appropriate tls/auth fields. What's not fully implemented is if a user wants to provide PEM files containing a certificate, key, and certificate authority (when applicable). **Edit**: this has now been implemented.
=> Update Presto and reporting-operator resources to reflect changes made to values.yaml

charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/presto/hive-scripts-configmap.yaml, charts/openshift-metering/templates/presto/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/values.yaml
Uses the native container support built into the JVM instead of hackily setting env vars and JVM properties for adjusting these values.
Previously this functionality was only available in Java 9 or later, but it was recently backported to Java 8. Read more at https://blog.softwaremill.com/docker-support-in-new-java-8-finally-fd595df0ca54.
=> charts: Replace scripted jvm max heap configuration with built-in JVM container support

charts/metering-ci/templates/metering.yaml, charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-jmx-config.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/monitoring/hdfs-service-monitor.yaml, charts/openshift-metering/templates/monitoring/hive-service-monitor.yaml, charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml, charts/openshift-metering/templates/presto/hive-configmap.yaml, charts/openshift-metering/templates/presto/hive-jmx-config.yaml, charts/openshift-metering/templates/presto/hive-metastore-service.yaml, charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/presto/hive-scripts-configmap.yaml, charts/openshift-metering/templates/presto/hive-server-service.yaml, charts/openshift-metering/templates/presto/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-jmx-config.yaml, charts/openshift-metering/templates/presto/presto-service.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-service.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-tls-secrets.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml
- Update presto jmx to use correct mbean names after updating to prestosql.io
- Configures Hadoop and Hive to run the jmx adapter now that it's in the hadoop image after https://github.com/operator-framework/hadoop/pull/8.
=> Monitor JMX metrics from Hadoop, Hive and Presto

pkg/operator/queues.go, pkg/operator/storagelocations.go
I noticed sometimes with the new setup that the reporting-operator stops processing storageLocations because hive-server/hive-metastore isn't reachable when reporting-operator starts, and it errors enough times to stop processing storageLocations. This fixes that by requeuing storageLocation resources forever. These are fairly important and if they don't get processed the reporting-operator is effectively stuck until restarted.
=> pkg/operator: Never stop re queuing StorageLocations

images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
Currently as it is, sometimes labels are too long when combined with the namespace.
=> roles/meteringconfig: Move namespace into separate label to shorten prune label value length

charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
This was left out after we made the switch from deployments to statefulsets.
=> charts/openshift-metering: Update the annotations used in the Presto coordinator/worker statefulsets to use the secret template hashes.

Documentation/common-configuration.md, Documentation/configuring-hdfs.md, Documentation/configuring-hive-metastore.md, Documentation/configuring-storage.md, Documentation/index.md, Documentation/install-metering.md, Documentation/storagelocations.md, charts/metering-ci/templates/metering.yaml, charts/openshift-metering/templates/metering/default-storage-location.yaml, charts/openshift-metering/templates/presto/_hive_helpers.tpl, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/presto/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/hive-shared-volume-pvc.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-aws-credentials-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, manifests/metering-config/default.yaml, manifests/metering-config/hdfs-storage.yaml, manifests/metering-config/metastore-storage.yaml, manifests/metering-config/s3-storage.yaml, manifests/metering-config/shared-storage.yaml, test/integration/main_test.go
- Add new top-level storage config under spec.storage to centralize
storage related configuration.
- openshift-reporting: move storageLocation into
openshift-reporting.spec and rename to defaultStorageLocation. This
move is to aligns with the new top-level storage option so that there
isn't confusion between the two.
- hive: Don't create shared-pvc by default and stop creating empty
warehouse volume. This has been removed from the hive image, and only
makes it possible to start hive without storage which isn't wanted.
- *: Don't create awsCredentialsSecrets by default and don't make
optional env var. Ensures that when the secret is missing that pods do
not start.
- Rename hdfs-config to hadoop-config to generalize it more.
- Update installation documentation and configuration …
=> Disable HDFS by default and wait for user to configure storage

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, Documentation/aws/read-write-create.json, Documentation/configuring-storage.md, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, manifests/metering-config/s3-storage.yaml
If `spec.storage.hive.s3.createBucket` is true, then the
metering-ansible-operator will attempt to create the bucket
`spec.storage.hive.s3.bucket`.
The bucket name is the first portion of the path segment, and we use the
credentials defined in `spec.storage.hive.s3.awsCredentialsSecretName`.
=> metering-ansible-operator: Support provisioning metering storage S3 bucket

images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Using defaults alone was incorrect and breaks actually using the
spec.storage options.
=> roles/meteringconfig: Use CR's spec.storage combined with defaults for doing storage overrides

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, charts/metering-ci/templates/metering.yaml, charts/openshift-metering/templates/presto/presto-auth-secrets.yaml, charts/openshift-metering/templates/presto/presto-tls-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-tls-secrets.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
Currently seeing if the images build correctly.
This needs to add some more validation of relevant fields and clarify some of the behavior we want.
=> Enable TLS and client-side authentication in Presto and reporting-operator by default.

charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Fix not creating S3 bucket when spec.storage.hive.s3.createBucket is false.
The default() filter isn't correct to use here because it sets the value
to the default when false, or empty when the second argument is true.
This causes the default to be used when the user specifies false.
Fixes that by using _storage_overrides and merging that with the user
configuration to determine if createBucket is true instead. Also updates
other s3 storage fields to use this pattern instead of the default()
filter.
Also added a 2nd commit that fixes using a bucket without a sub-path.
=> charts,roles/meterinconfig: Fix bucket configuration handling

cmd/reporting-operator/start.go, hack/run-reporting-operator-local.sh, pkg/operator/operator.go
Necessary for running e2e/integration tests locally with reporting-operator.
=> Allow running reporting-operator locally against TLS secured Presto

manifests/reports/cluster-usage-daily.yaml
Fixes the following:
```
message: 'failed to resolve ReportQuery dependencies cluster-cpu-usage: invalid
input "ClusterCpuusageReportName", supported inputs: ReportingStart ,ReportingEnd
,ClusterCpuUsageReportName ,ClusterCpuUsageRawDataSourceName'
message: 'failed to resolve ReportQuery dependencies cluster-memory-usage: invalid
input "ClusterMemoryusageReportName", supported inputs: ReportingStart ,ReportingEnd
,ClusterMemoryUsageReportName ,ClusterMemoryUsageRawDataSourceName'
```
=> fixed input  names

charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
=> charts/openshift-metering: Add missing hive-metastore TLS secret volume

Dockerfile.src, hack/e2e-test-runner.sh, hack/run-reporting-operator-local.sh
These are rarely used and the other pod log collections are sufficient.
=> Dockerfile.src,hack: Remove stern

charts/openshift-metering/templates/metering/default-storage-location.yaml, charts/openshift-metering/templates/openshift-reporting/_reporting_helpers.tpl, charts/openshift-metering/templates/openshift-reporting/datasources/default-datasources.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
Primarily moves defaultReportDataSources into a list, and supports disabling
the creation of these resources.
Additionally, the first two commits fix issues with pruning resources I
discovered while testing this.
=> Update openshift-reporting MeteringConfig schema

images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
Setting spec.logHelmTemplate tot rue enables better debugging when helm
templates are failing. Defaults to false.
=> roles/meteringconfig: Add MeteringConfig option `spec.logHelmTemplate` to log helm template task

images/metering-ansible-operator/ansible.cfg
Work around for https://bugzilla.redhat.com/show_bug.cgi?id=1726326
=> Fix ansible failures using /.ansible instead of $HOME

test/e2e/report_test.go
Instead of failing if a ReportQuery is missing during e2e, retry up to a
timeout waiting for the ReportQuery to be created.
=> test/e2e: Fix race condition on Reporting resources being created

charts/openshift-metering/templates/hive/hive-configmap.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-tls-secrets.yaml, charts/openshift-metering/templates/hive/hive-server-metastore-tls-secrets.yaml, charts/openshift-metering/templates/hive/hive-server-service.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-tls-secrets.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
Supercedes #795
This adds support for hive-server to communicate with hive-metastore using ghostunnel to provide a secured TLS connection to communicate over.
Also adds the ability to create the hive TLS secrets by providing configuration in your MeteringConfig.
=> Support TLS from Hive Server to Hive metastore using ghostunnel

images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
This is based on #787 
~This would still print things like `meteringconfig_tls_enabled`, `meteringconfig_tls_overrides`, `meteringconfig_root_ca_overrides`, but they won't contain any useful information.~
=> images/metering-ansible-operator: Prefix TLS-related default variables with an underscore.

charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-hive-auth-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-hive-tls-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml, charts/openshift-metering/values.yaml, cmd/reporting-operator/start.go, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml, pkg/operator/operator.go
- Add support for configuring hive-server to use ghostunnel to handle TLS and authentication via client certificates for authenticating to Hive.
- Updates reporting-operator to support passing client certificates when connecting to Hive via TLS.
- Add support configuring reporting-operator to use TLS client certificates for authentication to hive server in MeteringConfig.
=> Support configuring hive-server with authentication via ghostunnel

charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-hive-metastore-tls-secrets.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
Enables Presto to be configured to use ghostunnel to connect to hive-metastore using TLS client certificate authentication.
=> charts,images: Support for configuring Presto to use ghostunnel to authenticate to hive metastore

charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/values.yaml
If spec.reporting-operator.spec.config.hive.host is it takes precedence
over other options.  Default to hive-server:10000 unless
spec.reporting-operator.spec.config.hive.tls.enabled, then use
hive-server:10001.
=> charts/openshift-metering: Auto-configure default hive-host for reporting-operator

charts/openshift-metering/templates/presto/_presto_helpers.tpl
Enables automatic column level statistics collection on write.
https://prestosql.io/docs/current/connector/hive.html#table-statistics
Ensures our Presto tables have stats populated so we can view them using
`SHOW STATS FOR table_name;`.
=> charts/openshift-metering: Set Presto property hive.collect-column-statistics-on-write=true

charts/openshift-metering/values.yaml
This could potentially be done by in the metering-ansible-operator by modifying the variable, `meteringconfig_create_reporting_operator_route: "{{ _reporting_op_spec.route.enabled | default(false) }}"`.
=> charts/openshift-metering: Enable the metering route by default.

charts/metering-ci/templates/metering.yaml, charts/metering-ci/values.yaml, charts/openshift-metering/templates/openshift-reporting/datasources/default-datasources.yaml, charts/openshift-metering/values.yaml, hack/deploy-e2e.sh, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
Updates our Prometheus queries to be prepared for https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md.
Sometime in the future the old metric labels will be removed, so switch
our queries to use the new metric labels.
To support existing users on Kubernetes versions prior to 1.14, they can
set `spec.openshift-reporting.spec.defaultReportDataSources.postKube_1_14`
to false.
Ex:
```
spec:
openshift-reporting:
spec:
defaultReportDataSources:
postKube_1_14:
enabled: false
```
=> charts,images: Support using both pre/post-kubernetes 1.14 metrics

charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
added hadoop-starting-config to hive, presto, and hadoop, this allow the copied core-site.xml from hadoop-starting-config to be editable, allowing us to inject azure secrets with an init-container.
=> Add hadoop-starting-config to hive, presto, hadoop

images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
This somehow was reverted when I rebased my original PR to pull in merged master changes.
=> images/metering-ansible-operator: Rename TLS override variables to avoid being printed.

charts/openshift-metering/templates/hive/hive-configmap.yaml, charts/openshift-metering/templates/hive/hive-metastore-service.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-service.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
Currently this isn't enough because our pods still listen on 0.0.0.0 which means these ports are still accessible.
The config option for setting the bind address for hiveserver2 exists, but doesn't seem to work, and the option for hive-metastore doesn't exist except for in the master branch/hive 4.0 for hive.
=> Disable unauthenticated Hive ports when TLS is enabled

charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
PR #806 defined a new initContainer for hive-server but it overwrites
the initContainers array added previously, preventing the copy-hive-tls
container from being created.
=> charts/openshift-metering: Fix hive-server initContainers

Documentation/rollup-reports.md, charts/openshift-metering/templates/openshift-reporting/report-queries/pod-cpu.yaml
When going thru report queries I noted most of the time we use `CPU_Core_Seconds` as the unit but there were 1-3 units involving cpu measures that were at `core_seconds` so switching to standardize.
=> Standardize CPU_Core_Seconds

pkg/hive/query.go, pkg/operator/hivetables.go, pkg/operator/operator.go, pkg/operator/prestotables.go, pkg/operator/queues.go, pkg/operator/storagelocations.go
First commit fixes a panic dropping a database early during startup when finalizers are enabled.
Other commits ensure we remove finalizers when handling deletions, even if EnableFinalizers is false.
This is important in case the EnableFinalizers config changes from true to false, and when resources may have their finalizers set already.
Also fixes invalid SQL for dropping Hive databases.
=> Fix issues with database/table cleanup

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_openssl.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
This would add another file `configure_reporting_operator_openssl.yml`, which is used to automatically generate client cert/key for the reporting-operator to use when communicating with Presto and Hive Server.
Also, in this PR, there was some inconsistency on how related tasks were handled between the reporting-operator, Presto, and Root CA. I'd rather make these changes in a PR separate from #825 .
=> images/metering-ansible-operator: Move all reporting-operator TLS-related tasks to its own task file and clean-up TLS-related tasks.

charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl, charts/openshift-metering/templates/hadoop/hadoop-azure-credentials.yaml, charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-azure-credentials-secret.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-azure-credentials-secret.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
…h commands to initialize_presto.sh and creadted azure_secret_copy.sh in hadoop-scripts.yaml and hive-scripts-configmap.yaml to edit core-site.xml dynamically, adding in sensitive azure account details.
=> core-site.xml credentials injection

Documentation/reportqueries.md, Documentation/using-metering.md, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-service.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-route.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-service.yaml
This can cause confusion when trying to access the reporting-operator API, i.e.:
```
curl "http://127.0.0.1:8001/api/v1/namespaces/$METERING_NAMESPACE/services/https:reporting-operator:http/proxy/api/v1/reports/get?name=namespace-cpu-utilization&namespace=$METERING_NAMESPACE&format=tab"
```
The `/services/https:reporting-operator:http` endpoint can be a bit misleading with the current port name being `http`, so this PR would change that endpoint to `/services/https:reporting-operator:api`.
For more information, check out: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls
=> Rename the 'http' port name to 'api' in the reporting-operator service.

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
This lead to errors in the case where the secret didn't exist (therefore the 'resources' field would be undefined).
=> images/metering-ansible-operator: Update conditional to check if the 'resources' field is defined in the registered variable.

hack/lib/init.sh, hack/uninstall.sh
metering-ansible-operator deletes the hive-metastore PVC using an
ownerRef when the MeteringConfig is deleted, so we should also delete
the hdfs PVC.
=> hack: Delete PVCs during uninstall

hack/run-reporting-operator-local.sh, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_openssl.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml, pkg/operator/operator.go
Currently, there's pre-existing support to enable TLS/auth in Hive (which communicates with reporting-operator, Presto) by manually setting the necessary fields. This PR would enable TLS in Hive by default, which is conditioned on the top-level `spec.tls.enabled: true` field in the `MeteringConfig` CR.
We add all the necessary default variables (we need to update the reporting-operator Hive, hive, and Presto connectors sections to do this.) These new default variables act as overrides to the default values and use Ansible's "lazy evaluation" to avoid the usage of the `combine` filter.
When a user specifies `spec.tls.enabled: false` and manually configures TLS/auth for Hive, we do some basic validation: check if any necessary fields are non-empty, ensure TLS is not disabled when auth is …
=> Enable TLS in the reporting-operator, Presto, and Hive by default.

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel
Entrypoint in the base image is no longer a script, so update to calling
tini directly against the ansible-operator binary.
=> Dockerfile.metering-ansible-operator*: Fix entrypoint

Documentation/configuring-storage.md, charts/openshift-metering/templates/hadoop/hadoop-azure-credentials.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, manifests/metering-config/azure-blob-storage.yaml
added settings to Ansible, allowing setting the azure credentials in one place to apply to all the different nodes.
=> Azure settings overide

Documentation/olm-install.md
I work on Koku/Cost Management docs, and this procedure is an essential part of setting up an OCP source. While testing our docs and this procedure, I made a few edits to make this doc align with OpenShift branding standards, and a tiny bit easier to follow. Feedback welcome, I'm a new contributor here!
Summary of changes:
- Added procedural formatting
- minimized wording where possible
- edited product names like OpenShift to have the standard brand capitalization
- a few other various edits
=> Edits to OLM install doc

Documentation/configuring-storage.md, Documentation/index.md, Documentation/metering-config.md
Previously, there was some confusion as to whether Metering is able to support any s3 alternative.
=> Documentation: Clarify that Metering only supports Amazon s3 in relevant sections.

Documentation/dev/debugging.md, Documentation/install-metering.md
This would add ways to access the Metering Ansible operator, depending on the way you installed Metering resources, and checking the status of the `MeteringConfig` CR.
=> Documentation: Add troubleshooting for the metering-ansible-operator.

charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/reportdatasource.crd.yaml
See [extending CRDs with structural validation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) for more information on some of the limitations of openAPI V3 features.
More specifically, this violates rule no.3 described in the link above.
=> Update ReportDataSource CRD to comply with k8s structural standards.

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel
The upstream ansible base is now based on UBI so we need to install
openssl since it's no longer pre-installed in our base image.
=> Dockerfile.metering-ansible-operator*: Install openssl

charts/openshift-metering/templates/hive/hive-configmap.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/values.yaml
Ensures that the pod is unaccessible on it's unauthenticated ports and
all communication must be done through ghostunnel which requires TLS and
auth.
=> charts/openshift-metering: Set bind host for hive server and metastore to 127.0.0.1 with TLS/auth enabled

Makefile, hack/e2e-test-runner.sh, hack/run-reporting-operator-local.sh
- Makefile: Build test2json before running integration/e2e
- hack: Only kill if there are background jobs to kill
=> Improve running local tests

manifests/metering-config/hdfs-storage.yaml, manifests/metering-config/metastore-storage.yaml, manifests/metering-config/recommended-resource-limits.yaml
Currently, this would be invalid if we define the type of the `class` key to be of type string (as string != null).
=> manifests/metering-config: Remove the 'class: null' key from MeteringConfig examples.

manifests/metering-config/shared-storage.yaml
This field is a required `spec.storage` property, and is also present in the `s3-storage.yaml`, `hdfs-storage.yaml`, `azure-blob-storage.yaml` manifest files.
=> manifests/metering-config: Add 'spec.storage.type' field to shared-storage.yaml.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/metering-ci/templates/metering.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
This would add schema validation to the `MeteringConfig` CRD using OpenAPI V3. 
To add more detail to the sub-schemas we're most interested in (storage, resource limits, etc.) we first need to add the overall structural schema to the `MeteringConfig` CRD. Without this initial setup PR, most of the existing `MeteringConfig` CR's would be invalid due to miscellaneous keys not being defined. 
This PR also introduces a more defined storage sub-schema validation, which allows us to detect invalid `MeteringConfig` CR configurations, statically.
=> Add structural schema validation to the MeteringConfig CRD using OpenAPI V3.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
This allows us to control what fields are set, and error when a user provides multiple `spec.storage.hive` items, i.e.:
```
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
name: "operator-metering"
spec:
unsupportedFeatures:
enableHDFS: true
storage:
type: "hive"
hive:
type: "azure"
hdfs:
namenode: "hdfs-namenode-0.hdfs-namenode:9820"
s3:
bucket: stub
region: stubstub
secretName: stubstubstub
```
Before this change, this configuration would pass validation, but now this would produce the error message:
```
"spec.storage.hive" must validate one and only one schema (oneOf). Found none valid
"spec.storage.hive" must not validate the schema (not)
"spec.storage.hive" must validate all the schemas (allOf)
```
=> Update the storage sub-schema validation to restrict mutually exclusive fields from being set.

Documentation/olm-install.md
Projects have restrictions on the names, so create a namespace instead,
which also creates a matching project.
=> Documentation: Use namespace instead of projects for OLM install

charts/openshift-metering/templates/presto/_presto_helpers.tpl
Fixes azure which requires the hadoop core-site.xml to work properly.
Also moves hive.collect-column-statistics-on-write=true out of the
condition, as it shouldn't have been in the condition when
hive.config.resources was added.
=> charts/openshift-metering: use correct variable for checking if Hadoop config is available to presto

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
This PR adds the `spec.storage.hive.sharedPVC.mountpath` property, which was undefined previously. 
I also needed to update the `spec.storage.hive.azure` properties to include variables used in the ansible-operator (for developmental purpose), which weren't specified in the documentation.
=> Add properties and update validation to spec.hive.storage in the MeteringConfig CRD.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
With the new validation schema, fsGroup in metering-custom.yaml cannot be an integer (the schema requires a string) nor a string (fails while parsing \ufffd as an integer, if I remember correctly), nor a map (like the k8s docs suggest).
After reading the sources, I am still not sure how it's supposed to work, or if this is due to a bug or work in progress. But reverting the schema to integer fixes the issue for me.
=> validate fsGroup as integer

Dockerfile.metering-ansible-operator, images/metering-ansible-operator/scripts/entrypoint.sh
Use `tini` from path instead of `/tini` because the OCP image installs
tini from a package and it ends up in /usr/bin/tini.
=> metering-ansible-operator: Move tini into $PATH and update entrypoint

Documentation/configuring-reporting-operator.md
Both `using-metering.md` and `writing-custom-queries.md` use the variable `METERING_ROUTE_HOSTNAME`.
=> Documentation: Rename metering route variable to match the other references.

Documentation/writing-custom-queries.md
As written, the docs didn't specify moving from the default schema in presto to the metering schema.
This also fixes a typo.
=> fixes writing-custom-queries.md doc for schema use

Documentation/configuring-storage.md, charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl, charts/openshift-metering/templates/hadoop/hadoop-config.yaml, charts/openshift-metering/templates/hadoop/hadoop-gcs-credentials.yaml, charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-azure-credentials-secret.yaml, charts/openshift-metering/templates/hive/hive-gcs-credentials-secret.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-gcs-credentials-secret.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml, manifests/metering-config/gcs-storage.yaml
Edited helm and ansible to support GCS settings
Added doccumentation for GCS
Added mounts for new Json file as Secrets
Edited hadoop-scripts.yaml, hive-scripts-configmap.yaml, and presto-common-config.yaml to copy the Json keyfile if it is mounted
=> Add support for Google Cloud Storage with Json keyfile as auth

charts/metering-ansible-operator/templates/crds/report.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/report.crd.yaml
This was invaliding reports that didn't provide a schedule like hourly or daily.
=> charts,manifests: Remove the required properties in the Report CRD.

Documentation/prestotables.md, charts/metering-ansible-operator/templates/crds/prestotable.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/prestotable.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/prestotable.crd.yaml, manifests/reports/cluster-capacity-daily.yaml, manifests/reports/cluster-usage-daily.yaml
This would add schema validation to the `PrestoTable` CRD.
To-Do:
This is the output of `oc explain prestotables` after adding the top-level description fields:
```
[tflannag@localhost operator-metering]$ oc explain prestotables
KIND:     PrestoTable
VERSION:  metering.openshift.io/v1
DESCRIPTION:
PrestoTable is a custom resource that represents a database table
accessible from within Presto. When a PrestoTable resource is created, the
reporting-operator creates a table within Presto according to the
configuration provided, or exposes an existing table. More info:
https://prestosql.io/docs/current/index.html
FIELDS:
apiVersion	<string>
APIVersion defines the versioned schema of this representation of an
object. Servers should convert recognized schemas to the latest internal
value, and …
```
=> Add OpenAPI V3 schema validation to the PrestoTable CRD.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
added different configs for azure in the meteringconfig.crd to allow creating secrets for testing
=> fix for azure in meteringconfig.crd 

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
- Use python2-cryptography because openssl_csr requires a newer version of pyOpenSSL than available in the OCP rpm repos.
- Change the generated metering Root CA common name to a hostname to fix issues caused by using python cryptography package instead of pyOpenSSL.
=> Update OCP metering-ansible-operator Root CA CSR creation

Dockerfile.src
Without this, we sometimes get errors updating metadata such as:
http://mirror.math.princeton.edu/pub/epel/7/x86_64/repodata/59cd2d904711571ac63cfec0fec0641233dc027173c6667914bbcc2e10ea11dd-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
=> Dockerfile.src: Run yum clean and remove yum cache before running yum

hack/run-metering-operator-local.sh
I was still getting an error when running `make run-metering-operator-local` saying that the `$HOME/.minikube/*` certificates were missing, but `minikube ssh -- ls $HOME/.minikube` verified they were there. 
After adding a target directory location, I was able to run the metering operator locally.
=> hack: Update the target directory location for the minikube directory.

charts/metering-ansible-operator/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/openshift/olm/bundle/4.2/image-references, manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
The image-references file maps to the in envvars values in the CSV and
are automatically replaced by ART's automation for publishing OLM
manifests. This enables the automation to also update the image used for
ghostunnel.
=> charts,images,manifests: Set ghostunnel image from envvars

Dockerfile.metering-ansible-operator, Dockerfile.reporting-operator.okd
Base images are seemingly keeping cached information and it's causing
our images to fail to yum install, so clear the yum cache before using
yum.
=> Dockerfiles: yum clean and rm yum cache before yum install

charts/metering-ansible-operator/values.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/openshift/olm/bundle/4.2/image-references, manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1744314
=> Bug 1744314: Use 4.2 oauth-proxy image and support override image via envvar for ART OLM manifest manipulation

hack/olm-uninstall.sh
Currently, when running `./hack/olm-uninstall.sh`, all the relevant resources are deleted besides the CSV and metering-operator pod. If we query the `status.currentCSV` field in the subscription before deleting it, we can get the name of the CSV and delete it safely. 
Once the CSV is deleted, the metering-operator will start to terminate.
=> hack: Update the OLM uninstall to delete the CSV created from the subscription.

pkg/operator/datasources.go, pkg/operator/prestostore/importer.go, pkg/operator/prestostore/query.go, pkg/operator/prestostore/query_test.go, pkg/operator/promsum.go
This PR changes metrics importing to always import metrics of the configured import chunk size.
This ensures consistency in metrics being imported.
=> Always import full chunks when querying metrics

charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
- Fixes presto image overrides. The override was using the wrong structure for the helm values
- Adds a new image.override option to each component's helm values, allowing overriding the entire container image field in the pod template
- Updates image overrides in metering-ansible-operator's meteringconfig role to use the new image.override option. Fixes a bug in testing with images with ports in the image name, as is the case when testing staging OLM package bundles.
=> Fix image overrides from environment for components

pkg/operator/aws_usage_hive.go, pkg/operator/datasources.go, pkg/operator/reports.go
When something depends on a storageLocation, it should queue it if it's
not yet initialized with the DatabaseName in it's status.
=> pkg/operator: Queue hive StorageLocation when missing DatabaseName

Documentation/dev/mirroring-ocp-images.md, Documentation/dev/testing-ocp-images.md, Documentation/dev/testing-olm-ocp-install.md, charts/metering-ansible-operator/ocp-testing-values.yaml, hack/get-metering-package-images.sh, hack/mirror-ose-image.sh, hack/mirror-ose-images-into-cluster.sh, manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/ocp-testing/olm/bundle/4.2/image-references, manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
- Updates mirroring scripts to support different image tags per image, as is the case with the CSVs published by ART.
- Adds a script to extract the metering-ocp package CSV from the operator-registry pod created with the test ART OperatorSource. This script is used to set environment variables that are used by the image mirroring script.
- New documentation covering how to test ART published OCP OLM package bundles.
=> Document testing OCP install of metering using ART published OLM manifest bundle

charts/openshift-metering/templates/_ghostunnel_helpers.tpl, charts/openshift-metering/templates/hadoop/_hadoop_helpers.tpl, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/_hive_helpers.tpl, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/_helpers.tpl, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Previously the helm logic always used the image-overrides from the
environment for component images no matter what. Instead, switch to
using more logic in helm templates to determine what options the user
has set to define a proper precedence.
The precedence for image values is the following:
- If the MeteringConfig sets image.repository or image.tag for a
component, then the value specified will be used. If only one is set,
then the unset repo/tag option will fallback to the corresponding
image.repositoryDefault or image.tagDefault defined in the default
values.yaml in the chart.
- Otherwise, if image.defaultOverride is set, it will be used.
- If no overrides are set, then it defaults to the
image.repositoryDefault and image.tagDefault.
The default values have moved to …
=> images,charts: Fix default image overrides from preventing overriding image in MeteringConfig

Makefile, cmd/deploy-metering/main.go, cmd/deploy/main.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/helpers.go, pkg/operator/deploy/install.go, pkg/operator/deploy/uninstall.go
This PR adds a cobra cli that adds commands/flags which are used to customize the deployment process of metering.
```bash
$ make bin/deploy-metering
```
This creates the `deploy-metering` binary in `./bin/`
Most of the logic for setting the `Deployer` internal states have moved away from all environment variables, to a mixture of cli flags and environment variables. In the current iteration of this CLI, the value of the cli flags take precedence of the value of the environment variables:
```bash
$ export METERING_NAMESPACE="metering"
$ ./bin/deploy-metering install --namespace test
INFO[09-17-2019 14:54:42] Setting the log level to info                 app=deploy
INFO[09-17-2019 14:54:42] Metering Deploy Namespace: test               app=deploy
...
```
```bash
$ ./bin/deploy-metering …
```
=> Add a cobra cli that manages the deployment process of metering.

Makefile, hack/deploy.sh, hack/lib/util.sh, hack/run-metering-operator-local.sh
This is based on top of #940, which adds a CLI for deploying metering resources.
In this PR, all the `./hack/*install.sh` and `./hack/*uninstall.sh` scripts are replaced (except for olm) in the deploy scripts and now use the `deploy-metering` binary to manage the metering resources. Also, the `./hack/run-metering-operator-local.sh` now calls the `./hack/lib/util.sh install_metering()` helper function to install metering resources. 
At this moment, only Openshift/OCP and OLM installs are tested in e2e/integration suite. In the future, we can think about testing upstream installs (e.g. `install_metering upstream`) and alter the `install_metering` helper function to call `./bin/deploy-metering install --platform upstream` (or `export DEPLOY_PLATFORM="upstream"` and forgo the platform flag.)
=> hack,Makefile: Update the deploy scripts to use the deploy-metering binary.

charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
See PR title. Fixes a broken link in our package description, which is shown in the OperatorHub UI.
=> bug 1755130: charts,manifests: Fix link to about report docs in OLM CSV package description

Dockerfile.reporting-operator, Dockerfile.reporting-operator.okd, Dockerfile.reporting-operator.rhel, Dockerfile.src, Documentation/dev/developer-guide.md, hack/ocp-util/ocp-image-pull-and-rename.sh, pkg/operator/prestostore/importer.go
Updates Dockerfiles to all use Go 1.12 and dev-guide to require Go 1.12
=> *: Update to go 1.12

Dockerfile.reporting-operator, Dockerfile.reporting-operator.okd, Dockerfile.reporting-operator.rhel, Dockerfile.src
Running builds as in CI is failing with failed to initialize build cache at /go/.cache: open /go/.cache/log.txt: permission denied
=> Set XDG_CACHE_HOME to /tmp

pkg/operator/reporting/templates_test.go
Go 1.12 added more context to template errors so our expected errors
changed.
=> pkg/operator: Fix unit tests after Go 1.12 upgrade

charts/openshift-metering/values.yaml
We need to container, not container_name as the metric name we're
filtering on in container usage metrics. This was missed when changing
from pod_name to pod. In kube 1.16 (OCP 4.3) the older metric labels 
are removed which is what's breaking our CI currently.
=> bug 1756548: charts/openshift-metering: Fix kube 1.14 metrics queries

cmd/deploy-metering/main.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/helpers.go, pkg/operator/deploy/install.go, pkg/operator/deploy/uninstall.go
This would refactor the `deploy.Config` structure to take a `MeteringConfig` object, instead of a file that contains a `MeteringConfig` yaml file. This makes for a cleaner structure and makes testing different configurations easier.
=> cmd,pkg/deploy: Support passing an object to the MeteringConfig resource.

charts/openshift-metering/values.yaml
These queries were returning many to many matching errors on the
group_left that I didn't end up diagnosing, but I discovered we can
remove it since the container level metrics got the node name field that
we were joining from kube_pod_info. This simplifies them overall.
Additionally, I bumped up the window size for when we take the rate of
the CPU.
=> bug 1757547: charts/openshift-metering: Update cpu/memory usage promqueries to handle many to many matching error

cmd/deploy-metering/main.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/helpers.go, pkg/operator/deploy/install.go, pkg/operator/deploy/uninstall.go
Also read InitObjectFromManifest to ReadMeteringAnsibleOperatorManifests.
Moving the reading of MeteringConfig into main means we can re-use
ReadMeteringAnsibleOperatorManifests even if we're creating a
MeteringConfig directly, instead of reading it from a file.
=> pkg/operator,cmd/deploy-metering: Move reading of MeteringConfig into main package

pkg/operator/http.go, pkg/operator/http_test.go, pkg/operator/operator.go
```
export REPORT_API_URL=127.0.0.1:8080
$ curl $REPORT_API_URL/api/v2/reportqueries/metering-chancez3/namespace-memory-request/render --data '{"inputs": [], "start": "2019-09-01T00:00:00-00:00", "end": "2019-09-30T00:00:00-00:00"}' -XPOST -H "Content-Type: application/json"
SELECT
timestamp '2019-09-01 00:00:00.000' AS period_start,
timestamp '2019-09-30 00:00:00.000' AS period_end,
namespace,
sum(pod_request_memory_byte_seconds) as pod_request_memory_byte_seconds
FROM hive.metering.datasource_metering_chancez3_pod_memory_request_raw
WHERE "timestamp" >= timestamp '2019-09-01 00:00:00.000'
AND "timestamp" < timestamp '2019-09-30 00:00:00.000'
AND dt >= '2019-09-01'
AND dt <= '2019-09-30'
GROUP BY namespace
```
=> Add HTTP endpoint to render ReportQueries

charts/openshift-metering/values.yaml
The label_replace was moved to the outside of the sum, so the sum needs
to be on pod_name, not pod.
=> charts/openshift-metering: Fix sum fields on pod-usage-memory-bytes

test/e2e/main_test.go, test/integration/main_test.go, test/reportingframework/framework.go
This is already done in the testing init function for both integration and e2e:
```go
func init() {
reportTestOutputDirectory = os.Getenv("TEST_RESULT_REPORT_OUTPUT_DIRECTORY")
if reportTestOutputDirectory == "" {
log.Fatalf("$TEST_RESULT_REPORT_OUTPUT_DIRECTORY must be set")
}
err := os.MkdirAll(reportTestOutputDirectory, 0777)
if err != nil {
log.Fatalf("error making directory %s, err: %s", reportTestOutputDirectory, err)
}
}
```
=> test: Remove redundant code block from the reportingframework constructor.

test/reportingframework/framework.go
This would add a validation check that the path to the intended report output directory that's passed to the reportingframework constructor is a real directory. 
This is nice to have as metering needs to be deployed before running any tests, so waiting for that stack to become ready, and failing the reporting tests due to an empty/invalid `reportOutputDir` is a waste of time/resources.
=> test/reportingframework: Stat the report output directory.

pkg/operator/deploy/deploy.go, pkg/operator/deploy/install.go
This would add the functionality to pass extra namespace labels, which can be used in the e2e/integration refactoring for easier cleanup, e.g.
```go
cfg.ExtraNamespaceLabels = map[string]string{"name": "metering-testing-ns"}
```
This is useful in the case where there's existing namespaces with the label defined above that you want to cleanup, e.g.:
```bash
kubectl delete namespace -l name=metering-testing-ns
```
=> pkg/deploy: Support passing extra namespace labels for use in testing.

hack/e2e.sh, hack/run-test-cleanup.sh, test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/helpers.go, test/e2e/main_test.go, test/testhelpers/helpers.go
This would refactor the e2e package (`/test/e2e/`) to be responsible for both deploying metering and running the reporting tests against that deployment. This PR adds a `deployframework` package that's in charge of ensuring all of the metering resources are installed and ready to proceed to run the reporting tests, then outputs the resource and container logs to a directory before uninstalling the metering deployment after the testing phase has completed.
It's important to note that the teardown method for the deploy framework calls a bash script, so now the default behavior for when tests complete is to store logs first, then output the test results.
- Pass clientsets to `reportingframework.New` instead of that method creating the clientsets explicitly
- Support a partial install of …
=> test,hack: Refactor the e2e package to use the deploy metering package.

test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/helpers.go, test/e2e/main_test.go
As we push towards refactoring the e2e/integration suites, we need to ensure that overriding the reporting-operator images works as intended. 
This PR adds a testhelper function that validates if the image repository or tag are empty, when that image is overrided.
=> test/deployframework: Ensure the overrided reporting-operator image isn't empty.

cmd/deploy-metering/main.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/helpers.go, pkg/operator/deploy/install.go, pkg/operator/deploy/uninstall.go
With a recent PR failing e2e [1], the following error message was returned: 'Failed to deploy metering: Failed to uninstall metering: Failed to delete the MeteringConfig resource: Failed to delete the MeteringConfig resource:' which is difficult to read/follow the stack/command trace.
[1] https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/operator-framework_operator-metering/997/pull-ci-operator-framework-operator-metering-feature-metering-e2e-aws/62
=> cmd,pkg/deploy: Remove the nested logging and fix linting errors.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/openshift-metering/templates/hive/hive-configmap.yaml, charts/openshift-metering/values.yaml, manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
This setting only affects new tables, so doing this shouldn't have any major
backwards compatible issues, as we shouldn't be assuming anything about the
table formats anyways, since it could be changed.
/hold
We will likely want to file a bug and backport to 4.2.1 so that new installs are more likely to get ORC for all new tables.
=> bug 1763306: Fix setting default fileformat for Hive tables

pkg/operator/deploy/deploy.go, test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/framework_test.go, test/deployframework/helpers.go, test/e2e/main_test.go
The first 2 commits are minor refactorings, and 3rd is bigger refactorings to make some stuff more generally re-usable. The final 2 are about setting things up so that creation of the DeployConfig is unit tested.
=> Add unit test ensuring metering-operator and reporting-operator image repo/tags are set correctly

charts/openshift-metering/templates/hadoop/hdfs-serviceaccount.yaml, charts/openshift-metering/templates/hive/hive-serviceaccount.yaml, charts/openshift-metering/templates/presto/presto-serviceaccount.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-serviceaccount.yaml
This re-uses spec.annotations for each component that are also set on
the pod template annotations to allow additionally setting annotations
on the pod service accounts.
Also adds app labels to each service account.
Partial fix for #947
=> charts/openshift-metering: Support annotations on service accounts

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
=> charts,manifests: Support configuring reporting-operator securityContext

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/values.yaml, manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
=> charts,manifests: Support configuring Presto hive.s3.use-instance-credentials Hive catalog config property

cmd/deploy-metering/main.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/helpers.go, pkg/operator/deploy/install.go, pkg/operator/deploy/uninstall.go, test/deployframework/context.go, test/deployframework/helpers.go, test/deployframework/local.go, test/e2e/main_test.go, test/e2e/meteringconfig_missing_storage_spec.go, test/testhelpers/assert.go
This would extend the e2e suite to test for an invalid `MeteringConfig` (missing storage spec), and add another sub-test that would ensure that the current context's `MeteringConfig` was not created.
=> test: Add support for testing an invalid MeteringConfig.

test/deployframework/local.go
We are already storing these local operator logs in a directory that's guaranteed to be unique (via `ioutil.TempDir` so there's no need to worry about naming collisions.
=> test/deployframework: Create the local operator logs without a trailing suffix.

pkg/aws/client.go, pkg/aws/manifest.go, pkg/operator/datasources.go
When testing previous fixes for bug 1763303 on a new billing bucket I
discovered another bug related to how we expect the AdditionalArtifactKeys
field to be represented.
This was not caught previously due to not enabling any additional features in
the AWS billing reports we didn't need, but were set in the new billing report
being used which causes this field to be present in the AWS billing report JSON
manifests.
Also adds a commit to improve logging since I was having trouble figuring out
these issues originally without the improved logging.
=> bug 1763303: Fix handling of AdditionalArtifactKeys in AWS billing report manifests

charts/openshift-metering/templates/openshift-reporting/report-queries/node-cpu.yaml, charts/openshift-metering/templates/openshift-reporting/report-queries/node-memory.yaml
The proposed change here uses a CASE statement to return the correct resource_id depending on the cloud the cluster is installed in. This adds support for Azure to the resource_id column.
=> Return correct resource_id for Azure

images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Description:
This change would be helpful as we do a lot of validation of the Hive storage configurations in configure_storage.yml. It would be nice to fail earlier in the role execution when a storage component is misconfigured, e.g. when the user-provided s3 credentials secret doesn't exist.
=> images/metering-ansible-operator: Configure storage earlier in the role execution.

Makefile
This would remove the integration-related Makefile targets as those are no longer used after the e2e rewrite has been merged.
=> Makefile: Remove the integration targets.

images/metering-ansible-operator/roles/meteringconfig/library/k8s_status.py
When attempting to patch existing conditions, the `k8s_status` module will merge existing conditions with the conditions introduced in the most recent reconcile period. 
In order to do this, the module iterates over the new conditions list, checking if the current condition iteration's type matches an index in the existing conditions list, and if true, returns the corresponding index in the existing conditions list. 
This can be problematic as the `get_condition_idx` function returns the first match, and in the case where there are multiple existing conditions with the same type, returns a list containing multiple conditions with the same type.
This PR would update the merging process by filtering out any existing conditions that match the current, new condition when iterating over the …
=> images: Update the k8s_status module to better handle merging conditions.

images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml
While this task is somewhat helpful for debugging new dev implementations, it slows down the role execution significantly.
There are other ways to handle skipping this task when applicable, like adding a conditional that defaults to false that you would have to manually enable in the `defaults/main.yml` or adding a configuration option the `MeteringConfig` CRD, both of which are not ideal.
=> images: Remove the task that prints the variables prefixed with 'meteringconfig_*'.

hack/mirror-ose-image.sh, hack/mirror-ose-images-into-cluster.sh
Images from brew are now stored in quay and accessed through an internal
proxy.
=> [release-4.2] bug 1766341: hack: Fix mirroring scripts now that internal image registry is different

test/deployframework/local.go
Before, the testing suite would log the full `os.File` object returned from creating a file, instead of the path to the file created which contains a lot of unnecessary artifacts.
=> test/deployframework: Fix the logging message for where the metering-operator local logs are stored.

Dockerfile.metering-ansible-operator, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/update_meteringconfig_status.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml, images/metering-ansible-operator/watches.yaml
This would update the metering-ansible-operator to manage the `MeteringConfig` status directly, as opposed to the ansible-operator doing it for us. That would involve setting the `manageStatus: false` option in the watches.yml file, and using the `k8s_status` periodically throughout the role.
Also included in the PR is an update to the metering-ansible-operator Dockerfile that ensures the Ansible version is set to 2.8 for now as there was a regression in 2.9 where the `ansible_failed_result` and `ansible_failed_task` variables were undefined in a block/rescue task, which is not ideal.
=> Dockerfile,images: Manage the MeteringConfig status directly.

charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
All the images listed in a given CSV use the appropriate release tag, and the `containerImage` field was using `latest` which may be disrupting ART from substituting the image contained in this field to the correct image-registry ones in distgit.
=> charts,manifests: Update the csv's container image field to use the 4.4 tag instead of latest.

Makefile, hack/e2e.sh, test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/helpers.go, test/e2e/main_test.go
As we continue working with the refactored e2e suite, adding any additional e2e manual install tests can be cumbersome. This is because it takes a while to deploy a full install, wait for those resources to become ready to run reporting tests, then teardown any provisioned resources created. In the case where an error has occurred, then you would need to re-run the process outlined above, which is not ideal.
This PR would introduce the option to skip any tasks that uninstall the metering stack, or deletes namespaces containing the e2e label. With this change, you can re-run any failed tests with an existing namespace that already contains ready pods, which leads to quicker turnaround when adding more e2e tests.
=> hack,Makefile,test: Support running the e2e suite in a more dev-friendly configuration.

charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Manually opening this PR as the cherry-pick-bot didn't automatically open this PR, so must have messed up somewhere on the BZ-side of things.
=> Bug 1781499: Fix the invalid tag used in the release-4.2 CSV's container image field.

pkg/operator/datasources.go, pkg/operator/hivetables.go, pkg/operator/operator.go
This was found while investigating what parts of the reporting-operator need to be updated to read directly from the presto-prometheus catalog.
=> pkg/operator: Remove unused code and catch potential errors as needed.

Documentation/configuring-storage.md
I think this helps by splitting the docs for S3 into subheads, one for each path: Create Bucket or Use Existing Bucket. Also clarifies the wording.
=> Improve S3 bucket usage docs

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, charts/metering-ansible-operator/values.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Dockerfile(s): Add the python `netaddr` module to allow the usage of the `ipv4` Jinja2 filter.
Charts/: This would add a top-level variable that enables IPV6 networking to values.yaml.
Images/: Update the MeteringConfig Ansible role to allow support for inspecting the Networking config.openshift.io object, iterating over the serviceNetwork array and checking if there are any IPV4 addresses. In the case where there's a mixture of IPV4 and IPV6 addresses, treat that configuration as a single-stack IPV4 Openshift cluster. Else, treat it as a single-stack IPV6 Openshift cluster.
=> Add support for auto-detecting single-stack IPV4/IPV6 Openshift clusters.

images/metering-ansible-operator/roles/meteringconfig/tasks/update_meteringconfig_status.yml
When viewing the metering-operator "operator" container logs, there's no field that details whether a task is skipped or not [1], and in most cases we skip the fail module for this task. This can lead to confusion, so removing this task name can help improve clarity.
[1] {"level":"info","ts":1579721726.2411647,"logger":"logging_event_handler","msg":"[playbook task]","name":"operator-metering","namespace":"openshift-metering","gvk":"metering.openshift.io/v1, Kind=MeteringConfig","event_type":"playbook_on_task_start","job":"3510942875414458836","EventData.Name":"meteringconfig : End role due to failure"}
=> images: Remove the task name for ending the role during an error.

charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
This would add the 'get' verb to the cluster-role RBAC rules as the 'list' verb was insufficient permissions.
=> Bug 1795267: Allow the metering-operator to get the network openshift config object.

Dockerfile.reporting-operator, Dockerfile.reporting-operator.okd, Dockerfile.reporting-operator.rhel
ART uses the Golang 1.13 compiler to build our OCP images, so this would bump the version of the compiler used in the reporting-operator Dockerfiles.
=> Dockerfile.reporting-operator: Bump the Golang compiler version to 1.13.

Dockerfile.src
The test2json package is no longer needed and therefore the path to that package was removed (`gotools` was the base directory), so we need to update the Dockerfile.src to avoid copying a non-existent directory.
=> Dockerfile.src: Remove the unused gotools directory and bump the Go compiler version.

charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, pkg/operator/operator.go
AWS exposes a REST API endpoint for dual-stack s3 bucket hostnames. After playing around with both the virtual hosted-style and path-style requests, it appears that we still need to specify the fs.defaultFS and hive.metastore.warehouse.dir in order to talk with Hive Metastore correctly. This implies that we need to specify the s3 bucket name as the defaultFS/warehouseDir components, and use the path-style endpoint (i.e. s3.dualstack.us-east-1.amazonaws.com/<bucket name>) to hit the correct s3 bucket host.
Link to AWS dualstack docs: https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html
=> Bug 1793543: Allow support for using S3 buckets in an IPV6 cluster.

images/metering-ansible-operator/roles/meteringconfig/module_utils/crypto.py
When attempting to run Metering on a FIPS-enabled cluster, we fail role execution while generating user TLS certificates calling the 'openssl_privatekey' module. This module utilizes the module_utils/crypto.py helper library. This library iterates over a list of hashlib algorithms, which contains "FIPS-compliant" algorithms but still contains the 'md5' algorithm.
This would remove that algorithm from the list of available algorithms, and allow role execution to progress past the TLS-related tasks.
=> Bug 1787745: Remove the RSA's md5 algorithm from the Ansible openssl modules.

charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
This feature was added to the Openshift console in 4.4 and allows users to install Metering through OperatorHub.io in one step, instead of having to create the namespace first, then installing the Operator.
=> Bug 1799054: Add support for suggested namespace and cluster monitoring annotations in OLM.

charts/metering-ansible-operator/templates/crds/prestotable.crd.yaml, manifests/deploy/ocp-testing/metering-ansible-operator/prestotable.crd.yaml, manifests/deploy/ocp-testing/olm/bundle/4.4/prestotable.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/prestotable.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/prestotable.crd.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/prestotable.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/prestotable.crd.yaml, pkg/operator/prestotables.go, pkg/operator/reporting/db.go, pkg/presto/util.go
Currently, `spec.columns` are a required value in the `PrestoTable` CRD which is not always ideal. In the case of unmanaged tables, you would still need to specify a `spec.columns` configuration despite that table schema already existing in Presto. This would update the way that the reporting-operator handles unmanaged tables, namely natively querying the Presto go-client for the `spec.tableName` table_name, which eliminates the need to specify a column definition.
=> Support querying unmanaged, existing Presto table metadata. 

Documentation/reports.md, pkg/operator/reports.go
Changes docs and logging around reports `spec.runImmediately: true` to reflect what actually is required and what happens.
=> Bug 1790601: Fix description of runImmediately

pkg/deploy/install.go
When changes are made to the clusterrole and/or clusterrolebinding charts, existing Metering installs can break if existing clusterroles/clusterrolebindings don't have sufficient permissions to access certain k8s resources that the newer charts do.
=> Bug 1795267: Support updating existing clusterrole/clusterrolebindings when install Metering.

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
This is needed as the s3_bucket Ansible module does not support dual-stack endpoints, which is problematic is metering is run in an ipv6 single-stack configuration. In order to use the aws_s3 module which exposes a `dualstack` option, but has a dependency on the `botocore` python package. This commit would install that package so we can utilize this module to support both single-stack ipv4 and single-stack ipv6 configurations.
=> Bug 1802638: Allow support for creating an S3 bucket on an IPV6 cluster.

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel
This a workaround now that base image uses a version of` setuptools` (>= 45.2.0) which requires a python version >= 3.5.
=> Dockerfile: Require the setuptools python package to be less than the 45.2.0 version.

charts/openshift-metering/templates/hive/hive-configmap.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
This is a follow-up to PR #1077 which introduced support for using S3 as the storage backend in an IPV6 cluster. The changes in this PR update the Hive ghostunnel configuration needed to support both a single-stack configuration, dependent on the value of the top-level .useIPV6Networking.
In the case of the pkg/reporting-operator/cmd.go flags, we typically override the default values through the corresponding environment variable, which is reflected in the reporting-operator deployment changes. It's important to note that this means we need to be more careful when interacting with the CLI explicitly (i.e. in the case of running the reporting-operator locally, or in the e2e suite.)
=> Bug 1797801: Update the Hive and reporting-operator charts to work with single-stack ipv4 and ipv6.

charts/metering-ansible-operator/templates/olm/art.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/art.yaml, manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
This would add the `olm.skipRange` CSV annotation to the metering-operator's CSV which allows users to automatically upgrade to a newer channel once it becomes available in OperatorHub. Before, users would need to manually uninstall the operator and then reinstall when a new version is available, which is not ideal.
=> charts,manifests: Add support for upgrading between Metering CSV versions.

Dockerfile.metering-ansible-operator
Previously, we needed to always use the Ansible 2.8 version in the metering-ansible-operator origin Dockerfile as there was a regression in 2.9 with regards to the 'ansible_failed_result' and 'ansible_failed_task' variables being out of scope in a block/rescue task. It would appear this is no longer necessary and we can use the Ansible 2.9 version.
Commit that originally introduced this change: https://github.com/operator-framework/operator-metering/commit/c70e60048fad6fc0839e06401e2375192c84a23b
=> Dockerfile: Update the metering-ansible-operator to use the Ansible 2.8 and newer versions.

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
This validation check was already in-place but only validated that this secret exists when `createBucket` was set to true, and not in the case where the default value (false) was used.
=> images: Validate the S3 credentials secret exists before continuing role execution.

Dockerfile.metering-ansible-operator
This reverts commit 3b268d03b9954123773476a1f660795cf817cddb, reversing
changes made to 4769b7ff1fa9fd026bd5ad1d033f68c636bc76de.
For some reason, this started slowing down the role progression significantly, particularly when using the more recent 2.9 z-stream releases.
=> Revert "Merge pull request #1114 from timflannagan1/remove-ansible-2.8-pip-install".

Makefile, hack/update-codegen.sh
Currently the `./hack/update-codegen.sh` script is hardcoded to use the operator-framework/operator-metering package path, which breaks in the case we move this repository to another organization.
This adds support for overriding the `$SCRIPT_PACKAGE` variable, changing it to use the value of the `$GO_PKG` environment variable, and if that variable is unset, e.g. in the case of running the script directly, it defaults to the current github.com/<organization_name>/<repository_name>.
In the case where you want to override the value of the `$GO_PKG` environment variable, you would do something similar to the following:
```bash
make verify GO_PKG="github.com/<some org name>/<some project name>
```
=> hack,Makefile: Support overriding the script package path in the update-codegen script.

Documentation/dev/mirroring-ocp-images.md
Description
Providing a link to shell script file, so that user can navigate directly from documentation
Motive
Better readability of documentation
=> Providing a link to shell script file location

Documentation/reports.md
Description
Including reference to external RFC3339 documentation from documentation
Motivation
Better readability of documentation
=> Providing reference to external rfc3339 documentation

Gopkg.lock
Improvements needed to Gopkg.lock that are needed to help `go init mod` do its job.
=> Adds revision hash that was missing for OLM package

charts/metering-ansible-operator/values.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml, manifests/deploy/openshift/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/metering-operator-clusterrole.yaml, manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
Metering currently does not respect any cluster-wide Proxy configurations, so this would be the first step towards implementing support.
On the Metering side-of-things, when this Proxy cluster object is not nil, we need to set a top-level boolean variable that can be used at the Helm chart level to determine whether or not to use a certain proxy configuration or not.
In addition to that, we need to update our cluster role/rolebinding permissions which allows us to directly read from this cluster-scope Proxy object, pulling out the information we need and overriding the default proxy configuration values that Metering reads from.
To dissect a proxy URL, we can use the `urlsplit` Ansible filter [1] to pull out the hostname/port/username/password values that we care about, and updating the …
=> charts,images,manifests: Add support for auto-detecting when a cluster-wide Proxy has been configured.

hack/run-test-cleanup.sh
The `hack/run-test-cleanup.sh` script is a way to generate a must-gather geared towards a Metering installation, so this would just expand that scripts capabilities to also dump the descriptions of the `deployment` and `statefulset` objects that get created during installation.
=> hack: Capture the deployment and statefulset description before tearing down a test installation.

Documentation/index.md
Description : 
Correcting navigation to prometheus url subsection from index.md
Motivation:
Documentation review
=> Correcting prometheus link from index.md

Documentation/dev/developer-guide.md
Remove refs to `dep` and replace with instruction for `go mod` and general installation via `git clone`.
=> Update dev docs for go mod changes

Dockerfile.metering-ansible-operator
The ansible-operator base image has switched from rhel 7.7 to rhel 8.1, which includes bumping the python version to python3, and having to change where we pull the epel-release package.
=> Dockerfile: Update metering-ansible-operator image to work with rhel 8.1.

Documentation/configuring-reporting-operator.md, charts/openshift-metering/templates/monitoring/monitoring-rbac.yaml, cmd/reporting-operator/start.go, hack/run-reporting-operator-local.sh, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
In 4.3, the monitoring team updated its architecture to introduce this Thanos Querier component, which provides a way for components like Metering to connect to a single, multi-tenant interface.
By default and when run on Openshift, Metering connects to the cluster-wide, prometheus-k8s service to retrieve the metrics scraped from the cluster. These changes update the metering-ansible-operator Ansible role to connect to the thanos-querier service API instead of the prometheus-k8s service.
In the case of running Metering on a vanilla Kubernetes cluster, nothing has changed - you're still required to configure/provide the Prometheus URL in the `MeteringConfig` custom resource.
=> *: Connect to the thanos-querier API instead of the cluster-wide Prometheus instance.

pkg/deploy/uninstall.go
When uninstalling the metering associated PVCs, we list all the PVCs in the deploy namespace that match the `app=hdfs` or `app=hive`. This is problematic as the hive-metastore PVC manifest does not match the rest of the Hive components labeling structure (`app=hive,hive=<metastore,server>`) so we are label selecting something that won't ever exist.
In the case where you're using s3 as a storage backend, then a WARNing message will be produced as there's no PVC that matches that label selection:
```bash
$ ./bin/deploy-metering uninstall --namespace openshift-metering
INFO[04-13-2020 19:24:29] Setting the log level to info                 app=deploy
INFO[04-13-2020 19:24:29] Metering Deploy Namespace: openshift-metering  app=deploy
INFO[04-13-2020 19:24:29] Metering Deploy Platform: …
```
=> pkg/deploy: Fix the hive-metastore PVC label selector.

Makefile
In the case where you only want to run the manual e2e tests and not the upgrade tests, you would need to specify `EXTRA_TEST_FLAGS="-run TestManualMeteringInstall"`.
=> Makefile: Stop passing EXTRA_TEST_FLAGS to the e2e make target.

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
In 2.9.6, changes were made to how the template caching mechanism works. In previous versions, all variables (i.e. jinja2 expressions) were being cached, instead of the intended behavior which is a single variable gets cached. This was obviously problematic, especially in the case where you're trying to generate a password a couple of times, which meant the first password result gets cached, and any subsequent calls to generating passwords would result in the value of the first, cached password being assigned to the corresponding variable. 
In the case of Metering, our Ansible role heavily relies on the notion of lazy evaluation - Ansible evaluates any variables at the last possible second. When this change to 2.9.6 was made, Metering saw a significant performance degradation, going from …
=> Bug 1829836: Fix performance issues when deploying Metering on Ansible 2.9.6+ versions.

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
With the template caching changes made in 2.9.6, having to evaluate the result of the `ansible_failed_task` expression was greatly slowing down the role and doesn't provide much value for debuggability purposes.
- Removed all `ansible_failed_task` references
- Normalized most of the status updates
- Stored the result of the `meteringconfig_spec` variable locally.
At that point in the role, we've finished overriding any variables that reference this `meteringconfig_spec` variable, which is a giant dictionary containing all of the overridden MeteringConfig default values, and we can safely store this result locally.
Before this change, we copied this variable to a tmp file that the `reconcile_*` task files reference to deploy metering-related resources:
```yaml
- name: Store MeteringConfig …
```
=> Bug 1829836: Remove the ansible_failed_task variable from all block/rescue instances.

Documentation/dev/developer-guide.md
We don't need to mention `dep` any more in developer docs.
Does not work with Helm 3.x
=> Helm minor version note and rm dep

images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/update_meteringconfig_status.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
Previously, all instances of the `k8s_event` module were using an invalid `k8s_event.name` configuration. This produced an error like the following:
```yaml
TASK [meteringconfig : Log Events for validating configurations] ***************
task path: /opt/ansible/roles/meteringconfig/tasks/validate.yml:91
Tuesday 28 April 2020  18:09:29 +0000 (0:00:00.365)       0:00:14.305 ********* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /api/v1/namespaces/openshift-metering/events/Validate Configuration (Caused by ProtocolError('Connection aborted.', InvalidURL("URL can't contain control characters. '/api/v1/namespaces/openshift-metering/events/Validate …
```
=> Bug 1829072: Fix all of the k8s_event module instances.

pkg/deploy/deploy.go
For more installs, the MeteringConfig CRD should already be present so this is more of a quality of life change.
=> pkg/deploy: Lower the initial CRD poll time.

Dockerfile.metering-ansible-operator, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
In 2.9.6, changes were made to how the template caching mechanism works. In previous versions, all variables (i.e. jinja2 expressions) were being cached, instead of the intended behavior which is a single variable gets cached. This was obviously problematic, especially in the case where you're trying to generate a password a couple of times, which meant the first password result gets cached, and any subsequent calls to generating passwords would result in the value of the first, cached password being assigned to the corresponding variable.
- Replaced all instances of the depreciated `k8s_facts` module with the `k8s_info` module.
- Stored the result of the `meteringconfig_default_values` variable locally.
- Stored the result of the `meteringconfig_spec` variable locally.
- Removed all of …
=> Bug 1829833: Fix performance issues when deploying Metering on Ansible 2.9.6+ versions.

test/deployframework/helpers.go
Occasionally, we get an error in the e2e suite that we're reading from a file that's already been closed. It appears there might be a race between reading from the stdout pipe and the cmd.Run() method. This would stop appending any read buffer errors to the overall function's error array and in most cases, capturing these errors provide very little value.
=> Bug 1831325: Stop returning an error when running the gather testing artifacts script.

charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
This CA bundle already gets mounted in the reporting-operator container when the cluster-wide proxy is enabled, but not in the sidecar container.
=> Bug 1837043: Mount the cluster's certificate authority bundle in the auth-proxy sidecar container.

charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml, charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
In 4.1, the `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` field was depreciated, and in 4.5 it was removed entirely. Now, we need to migrate to reconciling an empty ConfigMap with the `service.beta.openshift.io/inject-cabundle="true"` annotation, which results in the service CA certificate bundle being automatically injected through one of the cluster's controllers. We can then mount that certificate into any of the Metering operand Pods that require access to that CA bundle.
- charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml adds an empty ConfigMap with the `service.beta.openshift.io/inject-cabundle="true"` annotation
- images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml adds another reconciliation item to the …
=> Bug 1842978: Migrate to obtaining the service-serving CA bundle from a ConfigMap.

charts/openshift-metering/templates/monitoring/monitoring-rbac.yaml
This was a regression when we updated our reporting-operator Prometheus URL configuration to point to the `thanos-querier` service, as we also updated the serviceaccount that grants Prometheus access to those resources, from the `prometheus-k8s` service account, to the `thanos-querier` one. 
When we updated our configuration to point to the thanos-querier service instead of the prometheus-k8s, we also updated the serviceaccount from prometheus-k8s to thanos-query, which results in the following errors:
```
level=error ts=2020-06-01T19:49:34.902Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Pod: pods is forbidden: User …
```
=> charts: Reference the correct serviceaccount to allow Prometheus to scrape Metering endpoints properly.

images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
This is another example of a static dictionary that we reference throughout the role where storing its result into a fact will shave off some overall role execution time, as Ansible no longer has to evaluate it every time its referenced.
=> images: Finalize the meteringconfig_spec_overrides dictionary before running any top-level tasks.

charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml, charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
In 4.1, the `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` field was depreciated, and in 4.5 it was removed entirely. Now, we need to migrate to reconciling an empty ConfigMap with the `service.beta.openshift.io/inject-cabundle="true"` annotation, which results in the service CA certificate bundle being automatically injected through one of the cluster's controllers. We can then mount that certificate into any of the Metering operand Pods that require access to that CA bundle.
- charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml adds an empty ConfigMap with the `service.beta.openshift.io/inject-cabundle="true"` annotation
- images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml adds another reconciliation item to the …
=> [release-4.5] Bug 1842977: Migrate to obtaining the service-serving CA bundle from a ConfigMap

charts/openshift-metering/templates/monitoring/monitoring-rbac.yaml
This was a regression when we updated our reporting-operator Prometheus URL configuration to point to the `thanos-querier` service, as we also updated the serviceaccount that grants Prometheus access to those resources, from the `prometheus-k8s` service account, to the `thanos-querier` one. 
When we updated our configuration to point to the thanos-querier service instead of the prometheus-k8s, we also updated the serviceaccount from prometheus-k8s to thanos-query, which results in the following errors:
```
level=error ts=2020-06-01T19:49:34.902Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Pod: pods is forbidden: User …
```
=> [release-4.5] Bug 1843178: Reference the correct serviceaccount to allow Prometheus to scrape Metering endpoints properly.

pkg/deploy/uninstall.go
It looks like we were properly cleaning up the metering-operator clusterrole and clusterrolebinding resources by encoding those YAML resources into Go objects and then deleting them, but the clusterroles/clusterrolebindings that metering was reconciling for the reporting-operator were being left over.
We always attach the [`app=reporting-operator` label](https://github.com/kube-reporting/metering-operator/blob/master/charts/openshift-metering/templates/reporting-operator/reporting-operator-rbac.yaml#L17) to any resource associated with the reporting-operator, so deleting all clusterroles/clusterrolebindings that match that label when the `--delete-crb` option is specified will properly clean up those resources.
=> pkg/deploy: Delete all clusterroles/clusterrolebindings matching the 'app=reporting-operator' selector.

go.sum, pkg/deploy/install.go
We're currently running into a problem in the upgrade e2e suite where we ensure the MeteringConfig CRD exists before creating the MeteringConfig custom resource.
This has proven to be an inadequate check, as seen in the following error:
```bash
FATA[06-08-2020 11:24:41] Failed to deploy metering: failed to install metering through OLM: failed to create the MeteringConfig resource: the server could not find the requested resource (post meteringconfigs.metering.openshift.io)  error="failed to install metering through OLM: failed to create the MeteringConfig resource: the server could not find the requested resource (post meteringconfigs.metering.openshift.io)"
```
Despite verifying the MeteringConfig CRD exists, we can still see that the apiserver is failing to find the plural name version …
=> Bug 1838652: Ensure the MeteringConfig CRD exists and has a populated Status field.

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
When creating this cookie seed, we have validation in place for the reporting-operator auth-proxy secret helm charts.
Here is an error that we picked up while running the role:
```
tflannag@localhost metering-operator [ensure-cookie-seed-is-32-char-length] k get meteringconfig operator-metering -o json | jq '.status'
{
"conditions": [
{
"lastTransitionTime": "2020-06-05T16:08:57.961574Z",
"message": "\"'Error: render error in \"openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml\":\n    template: openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml:51:62:\n    executing \"openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml\"\n    at <include (print $.Template.BasePath …
```
=> images: Ensure the randomly generated cookie seed string matches 32 characters in length.

test/e2e/main_test.go, test/e2e/testdata/meteringconfigs/missing-storage.yaml, test/e2e/testdata/meteringconfigs/prometheus-metrics-importer-disabled.yaml, test/e2e/testdata/meteringconfigs/prometheus-metrics-importer-enabled.yaml
This would add a set of MeteringConfig custom resource YAML manifests in the test/e2e/testdata directory. We can decode those manifests into Go object which is what the rest of the e2e deployframework suite currently expects. This way, we reduce the size of the main_test.go significantly, and it's much easier to follow the configuration listed in the YAML manifest, as compared to a giant Go object.
=> test/e2e: Replace the MeteringConfig Golang objects with decoded YAML manifests.

hack/e2e.sh, test/deployframework/framework.go
It the current iteration of the e2e suite, we always add a `metering-testing-ns` namespace label to any namespace that gets created. This is problematic in the case where multiple people are running the e2e suite locally, where all namespaces matching the `metering-testing-ns` get deleted as of a result of finishing (or exiting the e2e.sh script early) e2e suite.
This updates the `deployframework` structure to include the `--namespace-prefix` that gets passed to the e2e package. For whatever reason, this field was never added, despite being passed to the `deployframework` constructor. Once we add this field, we can prepend that field when we're constructing a label to pass to the `deploy` metering package. Now, in the trap function for the e2e.sh script we can target only the labels that …
=> hack,test: Prepend the namespace prefix to the testing namespace label we apply for multi-tenancy.

charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
In the art.yaml, which defines the substitution rules for ART, we search for this olm.skipRange annotation in the Metering CSV file:
```yaml
- search: 'olm.skipRange: ">=4.3.0 <{MAJOR}.{MINOR}.0"'
```
What's problematic here is that we're searching for strings that start with double-quotes, but helm renders many of the chart's CSV annotations as single quotes, instead of double-quotes, so the search for substitution rule fails and the end result is ART cannot properly substitute the 4.6 version.
=> Bug 1847151: Fix the olm.skipRange CSV annotation being rendered incorrectly.

charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
In the art.yaml, which defines the substitution rules for ART, we search for this olm.skipRange annotation in the Metering CSV file:
```yaml
- search: 'olm.skipRange: ">=4.2.0 <{MAJOR}.{MINOR}.0"'
```
What's problematic here is that we're searching for strings that start with double-quotes, but helm renders all of the chart's annotations as single quotes, instead of quote, so the search for that string fails and the end result is ART cannot properly substitute the 4.5 version.
=> [release-4.5] Bug 1847154: Fix the olm.skipRange CSV annotation being rendered incorrectly.

CHANGELOG.md, Documentation/configuring-hive-metastore.md, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_metastore.yml
We need to avoid using `set_fact` on the `meteringconfig_spec` dictionary before we're finished processing any non-reconciliation tasks. If we added an additional task file that we include after the `configure_hive_metastore.yml` task file, override a variable in the `meteringconfig_spec` dictionary, we won't see that propagate to the rest of the role as we ran `set_fact` on this dictionary in a previous task file.
The main change here is consolidating the need to set `hive.spec.metastore.storage.create` to false when a non-default database configuration has been specified. Also, we add MeteringConfig status updates and some light validation centered around asserting that the user didn't provide a username/password/secretName configuration in the `MeteringConfig` custom resource. This is …
=> Documentation,images: Generalize and update the configuring_hive_metastore task file.

charts/openshift-metering/values.yaml, pkg/operator/prestostore/query.go
We occasionally see errors of the type:
```bash
errored: failed to perform Prometheus query: execution: found duplicate series for the match group {namespace=\"metering-validhdfs-reportdynamicinputdata\", persistentvolumeclaim=\"hive-metastore-db-data\"} on the right hand-side of the operation: [{namespace=\"metering-validhdfs-reportdynamicinputdata\", persistentvolumeclaim=\"hive-metastore-db-data\", storageclass=\"gp2\", volumename=\"pvc-e7ea4ab5-b8e6-4f87-8f16-c4cfc84d19db\"}, {namespace=\"metering-validhdfs-reportdynamicinputdata\", persistentvolumeclaim=\"hive-metastore-db-data\", storageclass=\"gp2\"}];many-to-many matching not allowed: matching labels must be unique on one side"
```
Checking the Prometheus code we see:
```go
ev.errorf("found duplicate series for the match group %s …
```
=> Bug 1844240: Fix many-to-many occasional e2e errors by adding `label_replace()` to handle missing `volumename`

charts/openshift-metering/values.yaml, pkg/operator/prestostore/query.go
Reverts kube-reporting/metering-operator#1257
=> Revert "Bug 1844240: Fix many-to-many occasional e2e errors by adding `label_replace()` to handle missing `volumename`"

Dockerfile.src
WIP
We are encountering a build error, likely due to a dependency being removed:
```
Error: Package: jq-1.6-2.el7.x86_64 (ecnahc515-faq)
Requires: libonig.so.2()(64bit)
Error: Package: faq-0.0.6-1.el7.x86_64 (ecnahc515-faq)
Requires: libonig.so.2()(64bit) 
```
=> First pass jq faq without hack/faq.repo copy

charts/openshift-metering/values.yaml, pkg/operator/prestostore/query.go
Take 2 (this was accidentally force merged)
We occasionally see errors of the type:
```bash
errored: failed to perform Prometheus query: execution: found duplicate series for the match group {namespace=\"metering-validhdfs-reportdynamicinputdata\", persistentvolumeclaim=\"hive-metastore-db-data\"} on the right hand-side of the operation: [{namespace=\"metering-validhdfs-reportdynamicinputdata\", persistentvolumeclaim=\"hive-metastore-db-data\", storageclass=\"gp2\", volumename=\"pvc-e7ea4ab5-b8e6-4f87-8f16-c4cfc84d19db\"}, {namespace=\"metering-validhdfs-reportdynamicinputdata\", persistentvolumeclaim=\"hive-metastore-db-data\", storageclass=\"gp2\"}];many-to-many matching not allowed: matching labels must be unique on one side"
```
Checking the Prometheus code we see:
```go …
```
=> Bug 1844240: Fix many-to-many occasional e2e errors by adding `label_replace()` to handle missing `volumename` 

hack/e2e.sh
This is a nice to have, especially when the repository structure is still using the old $GOPATH style.
=> hack: Add the '-mod=vendor' go test option.

Documentation/dev/deploy-metering.md
This utility has been in use for a while but there was no available documentation that described the various sub-commands and their options.
=> Documentation/dev: Add documentation for the deploy-metering CLI utility.

pkg/deploy/uninstall.go
When we're reconciling the clusterrole and clusterrolebinding resources for the reporting-operator, we add a pruning label for those resources:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
annotations:
operator-sdk/primary-resource: tflannag/operator-metering
operator-sdk/primary-resource-type: MeteringConfig.metering.openshift.io
creationTimestamp: "2020-06-23T16:29:24Z"
labels:
app: reporting-operator
metering.openshift.io/ns-prune: tflannag
metering.openshift.io/prune: cluster-monitoring-view-rbac
```
These are namely hacks to ensure we clean up all resources properly, but you can see that we tag the watched namespace and the resource with a `metering.openshift.io/*prune*` label to track these resources.
In the past implementation, we only searched for …
=> pkg/deploy: Update the label selector used to delete the metering clusterroles/clusterrolebindings.

Dockerfile.src
Our CI is configured to use this Dockerfile as the build root - it essentially just adds things like `operator-courier`, `faq`, `helm`, etc. that get used throughout our testing configuration.
=> Dockerfile.src: Get the faq dependency via a static Linux binary.

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
The first conditional check was configured to check if the `cluster_proxy_config` variable was defined. This is problematic check as that variable is the registered output of querying for the OCP cluster-wide proxy object, and in the case of Ansible, a registered variable will always be defined even if a task has been skipped. If we, instead, check if the `.resources` dictionary key is defined instead of the top-level object, that's sufficient as a baseline check.
=> images: Fix conditional when checking if the cluster-wide proxy has been configured.

cmd/deploy-metering/main.go, pkg/deploy/deploy.go, pkg/deploy/install.go, pkg/deploy/uninstall.go
This functionality was mainly only used for upgrade testing in our e2e suite, so the creating and deletion of OLM resources like a Subscription were configured to use several constants/hardcoded values, like using the redhat-operators CatalogSource and the `metering-ocp` package name.
Now, you can specify the subscription name, the name, and namespace of an existing CatalogSource resource, etc. This will be mainly used for updating the e2e suite to deploy Metering using OLM, instead of manually creating the requisite objects, so this work is intended to be iterative.
=> cmd,pkg/deploy: Support passing a list of configurable OLM flagsets/environment variables.

pkg/deploy/deploy.go, pkg/deploy/uninstall.go
Before, we were label selecting for any PVC in the `deploy.config.Namespace` that matches either of the `app=hdfs` or `app=hive`, but in the case of the latter, the MeteringConfig is listed as the owner reference so there's no need to manually list and delete the PVC ourselves, and instead, we can only list the hdfs PVCs, if present.
=> pkg/deploy: Update the uninstallMeteringPVCs method to only list the hdfs PVCs.

hack/push-olm-manifests.sh, olm_deploy/Dockerfile.registry, olm_deploy/manifests/deployment.yaml, olm_deploy/manifests/service.yaml, olm_deploy/scripts/init-bundle-registry.sh
In order to deploy the most up-to-date operator bundle, we need to be able to create a CatalogSource custom resource that references an existing image.
We have a couple of different options for doing this:
- Create ConfigMap containing the package.yaml, CRDs, and CSV manifests.
- Build and push an image containing the manifest bundle and an initialized registry server to an image registry.
- Build and push an image containing the manifest bundle and serve the registry server locally.
In the case of CI, we need to take the third approach as they expose a series of environment variables pointing to the newly built metering/reporting operator images.
In the Dockerfile.registry, we copy over the current openshift manifest bundle to a known destination path in the container and copy over a …
=> hack,olm_deploy: Add an additional set of manifests used to build a local bundle registry.

test/e2e/main_test.go
This is needed in the case where you want to defer any test cleanup as os.Exit doesn't respect that call in TestMain.
If we instead create a wrapper function around TestMain and call that wrapper function in TestMain, then we can start
cleaning up any testing resources in the e2e suite, instead of doing all of that work as part of the `trap cleanup EXIT` call in hack/e2e.sh.
Link to article that explains that behavior:
- http://blog.englund.nu/golang,/testing/2017/03/12/using-defer-in-testmain.html
=> test/e2e: Add a wrapper function around the top-level TestMain function.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
I was seeing this pop up in the e2e test runs where the resource limits and request configurations in the MeteringConfig manifests weren't being rendered properly:
```yaml
...
spec:
hadoop:
spec:
hdfs:
datanode:
resources:
requests: {}
storage:
size: 5Gi
enabled: true
namenode:
resources:
requests: {}
storage:
size: 5Gi
...
```
This is a result of moving from v1beta1 to v1 CRDs, which auto-purges any CRD schemas that aren't defined.
If we instead explicitly specify that we don't want these fields pruned by the apiserver, we get the following:
```yaml
...
spec:
hadoop:
spec:
hdfs:
datanode:
resources:
requests:
memory: 500Mi
storage:
size: 5Gi
enabled: true
namenode:
resources:
requests:
memory: 500Mi
storage:
size: 5Gi
...
```
=> chart,manifests: Fix issue where configuring resource requirements for Metering gets purged.

charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/presto/presto-worker-config.yaml
Will likely revisit these changes once our forked Presto version => 330 when more complete security changes were made to upstream.
Presto as of v228 requires a non-null keystore password
=> Changes needed to accomodate the move of our forked Presto to  v328

charts/metering-ansible-operator/templates/olm/art.yaml, charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/art.yaml, manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
In the 4.5 release cycle, support was added to support upgrading between Metering CSV versions. We were asked to backport upgrade support to any release that made sense, which in this case would be 4.3/4.4 as 4.2 is marked as EOL once 4.5 GA is released.
The [`olm.skipRange`](https://docs.openshift.com/container-platform/4.4/operators/understanding_olm/olm-understanding-olm.html#olm-upgrades-replacing-multiple_olm-understanding-olm) CSV annotation adds the ability to upgrade between Metering CSV versions in a single `package.yaml`, which ART populates.
This file governs the substitution rules that ART is configured to read from. In this case, we're substituting the second x.y.z version from <4.4.0 reference, with the latest 4.4.z z-stream release.
=> [release-4.4] Bug 1847111: Add support for upgrading between Metering CSV versions.

test/e2e/main_test.go, test/e2e/metering_manual_install_tests.go
In order to add more flexibility to the e2e suite, we need to support creating any pre-installation resources before punting the current test context to the deploy-metering Go package. In order to do this we can create a function type that takes a deployframework.DeployerCtx object, with the assumption that when we run the preInstallFunc, that state has been initialized. This is useful in the case where we want to create things like an NFS provisioner, or create a secret containing the AWS credentials that will be used throughout the testing suite.
=> test/e2e: Add support for running any pre-installation tests.

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
When we bumped the apiextensions.k8s.io versioning to v1, all unknown CRD schema definitions get purged automatically, which is problematic in the case of specifying labels, annotations, and node selector configurations for the Metering operands, as those schema definitions are missing a properties definition. The end result was them being rendered as an empty dictionary (e.g. `nodeSelector: {}`) and the user-provided configuration was not respected.
If we instead add this `additionalProperties` field for those fields, those contents are rendered correctly assuming they're in the correct form.
=> charts,manifests: Fix missing schema definitions for map[string]string API fields.

hack/get-metering-package-images.sh
This script is useful for interacting with CatalogSource bundles locally, ensuring that the images listed in the bundle matches what you expect before creating a Subscription object.
The following will output the contents of the 4.5 metering-ocp package in the qe-app-registry CatalogSource:
```bash
$ kubectl -n openshift-marketplace port-forward svc/qe-app-registry 50051 &
...
$ ./hack/get-metering-package-images.sh 
export METERING_ANSIBLE_OPERATOR_IMAGE=quay.io/openshift-qe-optional-operators/ose-metering-ansible-operator@sha256:0d3766d650504a00bfe552a64c7d17f8ae905dfc1f3629a49d6d72f722cfee1b
export METERING_REPORTING_OPERATOR_IMAGE=quay.io/openshift-qe-optional-operators/ose-metering-reporting-operator@sha256:3f701a5539ac347e9bca2da31bc771384abe32560d7a7671e6962b2e5d9d8a87
export …
```
=> hack: Bump the default channel in the get-metering-package-images script.

hack/e2e.sh, test/e2e/custom_node_selector_tests.go, test/e2e/main_test.go, test/e2e/metering_manual_install_tests.go, test/e2e/testdata/meteringconfigs/node-selector-prometheus-importer-disabled.yaml
This is a common MeteringConfig custom resource configuration we document downstream and following the updates in #1310, we should be testing this configuration regularly to ensure it's still working. At the moment, we can make this a required test with the intention of offloading it eventually as a periodic test that's not run as part of the regular dev PR e2e.
=> Add an e2e test for validating a custom node selector configuration.

Dockerfile.deploy-metering
This builds an alpine container image containing the deploy-metering utility that we use to provision Metering installations in for the dev and testing environments.
For simple usage, you could alias running the container locally:
```bash
$ alias dm="podman run --rm -v "$KUBECONFIG:/kubeconfig" -v "$METERING_CR_FILE:/mc.yaml -e KUBECONFIG=/kubeconfig -e METERING_CR_FILE=/mc.yaml quay.io/tflannag/deploy-metering:latest
```
And interacting with that command could look something like this:
```bash
$ dm install --namespace metering --deploy-manifest-dir /manifests
time="07-16-2020 18:20:50" level=info msg="Setting the log level to info" app=deploy
time="07-16-2020 18:20:50" level=info msg="Metering Deploy Namespace: tflannag-test" app=deploy
time="07-16-2020 18:20:50" level=info msg="Metering …
```
=> Add a Dockerfile for building the deploy-metering CLI utility.

charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Right now, every PR is failing e2e as the minKubeVersion specified in our CSV resource is 1.18.3, which is greater than the server version (1.17.0) that the apiserver is advertising. In order to unblock CI, we can lower this value to 1.17.0 with the intention of reverting it once this issue is resolved.
=> charts,manifests: Lower the minKubeVersion to 1.17.0 to unblock CI.

test/e2e/main_test.go, test/e2e/manifests/meteringconfigs/mysql.yaml, test/e2e/metering_manual_install_tests.go
In our OCP documentation, we recommend overriding the default, local embedded Derby database that Hive metastore is configured to use, with either a MySQL or PostgreSQL instance.
This would add a fairly straight-forward MeteringConfig YAML manifest that is configured to reference to a MySQL database instance in the `mysql` namespace. We create that namespace and the database instance using the `oc new-app ...` mysql 5.7 imagestream before firing off the metering installation responsible for using MySQL as an underlying hive metastore database.
=> test/e2e: Add an e2e test for configuring a MySQL instance for Hive metastore.

pkg/operator/operator.go
`NewFilteredSharedInformerFactory` is deprecated in favor of `NewSharedInformerFactoryWithOptions`.  See https://github.com/kube-reporting/metering-operator/blob/62484305833c3576b59f1889b110538b2c78da97/pkg/generated/informers/externalversions/factory.go#L70
=> update to non-deprecated informer factory method

pkg/operator/operator.go
Looks like (probably) the blank import was there to get the driver registered via the init function and someone needed to call `presto.RegisterCustomClient` later so a dupe was added.
Also cleaned up the redundant alias for the `hive` import - the import path is `go-hive-driver` but the actual package is already `hive`.
=> remove duplicate import and redundant alias for hive

test/e2e/main_test.go
This test is causing frequent e2e flakes as we're adding this custom testing label
to the available sets of nodes in the prior to firing off any metering installations.
The result is that all of the metering installations fight for their pods to be scheduled,
which is fine as the machineautoscaler will provision new machines. With this node selector
test, that's problematic as the new machines that the machineautoscaler provisions will not
have the custom testing node label, so pods will never schedule.
=> test/e2e: Disable the node selector e2e test by default.

charts/metering-ansible-operator/templates/_helpers.tpl, manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml, manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
This field controls the internal ansible-operator logging level. We can default this logging level to logging both Ansible playbook logs and the internal ansible-operator logs, with the intention of editing this value on the deployment/CSV objects if you want to change the verbosity of the default logging.
Other available values for this argument are 'debug' and 'error' (or providing the verbosity of the logs using an integer):
- https://github.com/operator-framework/operator-sdk/blob/be718958884e04b4c4adfab5e0054524bba5226b/pkg/log/zap/flags.go#L52
In the case where you only want to stream the Ansible playbook logs and not the internal ansible-operator logs, you would edit the value of this argument to '--zap-level=error' in the metering-ansible-operator deployment and that would reduce …
=> charts,manifests: Add the zap-level argument to the ansible-operator container.

charts/metering-ansible-operator/templates/crds/report.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml, manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/report.crd.yaml, manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml
It looks like this is a valid API field for the Report CRD, but wasn't added when we were initially adding the schema validation for this object. Before, when we were using apiextensions.k8s.io/v1beta1 CRDs, this was fine as the pruning of unknown fields defaulting to false, but now that we transitioned to v1 CRDs, we need to add this field as a valid schema property.
=> charts,manifests: Update the Report CRD to add a schema for 'spec.overwriteExistingData'.

test/e2e/main_test.go, test/e2e/metering_ansible_operator_metrics_test.go
This is a follow-up to the fixes made in https://github.com/kube-reporting/metering-operator/pull/1235 to make sure we don't regress in future releases.
At the moment, all this post-install test does is exec into the `prometheus-k8s` Pod in the openshift-monitoring namespace and ensures that the workqueue_work_duration_seconds_count metric returns a successful status. The ansible-operator, which will expose this metric, creates a ServiceMonitor for the metering-operator-metrics service name, so we should be able to query for the value of this metric in the test namespace that has deployed Metering.
=> test/e2e: Add a post-install test that verifies that the metering-ansible-operator is exposing metrics properly.

pkg/apis/metering/v1/util/report_util.go, pkg/apis/metering/v1/util/report_util_test.go, pkg/operator/reports.go
Just throwing in some tests while I poke around the codebase.  
A couple items marked with TODOs that probably need a closer eye from someone more familiar with the usages:
1.  we accept a pointer in SetReportCondition but don't account for nils by either throwing an error or returning.  I added a return but that may be just hiding a programming error - your call.
2.  we accept a pointer in RemoveReportCondition but don't account for nils by either throwing an error or returning.  I added a return but that may be just hiding a programming error - your call.
3.  we don't consider a change in message a change in SetReportCondition.  Not sure if that's on purpose or not.
=> add unit testing for report util methods.

pkg/operator/operator.go, test/e2e/ensure_leader_election_event_is_created.go, test/e2e/main_test.go
In order to broadcast k8s events to help report errors for the metering-related resources, we need to add the metering scheme that gets generated from the `pkg/apis/metering/v1/register.go` implementation on top of the default scheme the controller was using the report the leader election event. Changing the event recorder to use the metering scheme, in addition to the default scheme allows us to broadcast events to different object's lifecycles.
=> pkg/operator: Update the scheme used for the event record to include the metering v1 scheme.

charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
This is a follow-up PR to #1322 which lowered the `minKubeVersion` in our CSV's to unblock CI as the server was reporting a kube version of 1.17.0 instead of 1.18.3 at the time. It appears this is now fixed, so this reverts back to 1.18.3, which is the version our kube dependencies are currently pinned to now.
=> charts,manifests: Bump the minimum kubernetes server version to 1.18.3

charts/metering-ansible-operator/templates/crds/report.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml, manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/report.crd.yaml, manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml, pkg/apis/metering/v1/report.go, pkg/apis/metering/v1/zz_generated.deepcopy.go, pkg/operator/http_test.go, pkg/operator/operator.go, pkg/operator/reporting/templates_test.go, pkg/operator/reporting/validate_test.go, pkg/operator/reports.go, pkg/operator/reports_test.go, test/testhelpers/helpers.go
Less WIP:
- Does have any required manifest changes;
- Does not have validation on the retention value provided;
- Does have consideration of `spec.input` dependencies (please check that seem complete and correct way to go about doing them though)
Note: Do we think the new `report.Spec.Expiration` on the Report CRD should just be a duration to be added to Report create timestamp?
=> Additions for Report expiration

pkg/operator/operator.go
This was missing during the initial review where the events that get created as a result include the string format specification ('%s') instead of the Report name, which resulted in the following:
```bash
$ oc get events --field-selector reason="ExpiredReportHasBeenDeleted"
19m         Normal   ExpiredReportHasBeenDeleted   report/node-cpu-capacity-now   Deleted the %s Report as the configured expiration date has passed
...
```
=> pkg/operator: Add the value of the missing format specification when firing off Report events.

pkg/operator/operator.go, pkg/operator/reports.go
A couple of more changes that follow-up the work done in #1298.
=> pkg/operator: Use the parent logger from op.syncReport instead of the built-in reporting logger.

pkg/operator/reports.go
More follow-up changes introduced in #1298.
We should be checking whether the Report we're currently processing in the op.runReport method has reached its expiration date and requeueing that object such that op.syncReport will properly manage it.
This produces the following output in the reporting-operator container logs:
```go
time="2020-08-01T17:22:08Z" level=info msg="syncing Report tflannag/node-cpu-capacity-now" app=metering component=reportWorker logID=7ygCr5kB0Q
time="2020-08-01T17:22:08Z" level=info msg="deleted Report: node-cpu-capacity-now in the Namespace: tflannag because it reached the expiration time" app=metering
time="2020-08-01T17:22:08Z" level=info msg="requeueing report that has reached its expiration date during the op.runReport method" app=metering …
```
=> pkg/operator: Requeue a Report that has reached its expiration date during the op.runReport method.

test/e2e/main_test.go
This test is potentially problematic as we're creating a bucket in an AWS account we don't have any governance over. We should just disable this test for now as periodic jobs would've run this test case in it's current form until we touch base with DPTP.
=> test/e2e: Disable the s3 bucket test installation by default.

test/e2e/main_test.go
The MySQL 5.7 imagestream has been recently removed from the 4.6 release, which ends up breaking this e2e test as we're attempting to instantiate a 5.7 MySQL service with an image that doesn't exist. Let's disable this test for now and circle back to it later.
=> test/e2e: Disable the MySQL Hive metastore e2e test.

Dockerfile.bundle, olm_deploy/bundle/manifests/hive.crd.yaml, olm_deploy/bundle/manifests/meteringconfig.crd.yaml, olm_deploy/bundle/manifests/meteringoperator.v4.6.0.clusterserviceversion.yaml, olm_deploy/bundle/manifests/prestotable.crd.yaml, olm_deploy/bundle/manifests/report.crd.yaml, olm_deploy/bundle/manifests/reportdatasource.crd.yaml, olm_deploy/bundle/manifests/reportquery.crd.yaml, olm_deploy/bundle/manifests/storagelocation.crd.yaml, olm_deploy/bundle/metadata/annotations.yaml
This is mainly a no-op at the moment as we consider how to best integrate this during the 4.6 release. We may want to merge these standalone, with the intention of integrating with CI as a follow-up, before fully migrating over from the old manifest bundle format to this new one.
A couple of open questions:
- ~Where should the image-references file be located?~ This isn't necessary and will break validation.
- ~Where should the art.yaml file be located?~ This isn't necessary and will break validation.
- ~Do we need to incorporate either right now if we don't need them for use throughout CI?~ Nope
- ~How to best organize the existing manifests with these newly introduced manifests, in addition to the olm_deploy manifests that are used to deploy metering in CI.~
=> olm_deploy: Add the metering-ansible-operator bundle format.

charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml, charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
In 4.1, the `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` field was depreciated, and in 4.5 it was removed entirely. Now, we need to migrate to reconciling an empty ConfigMap with the `service.beta.openshift.io/inject-cabundle="true"` annotation, which results in the service CA certificate bundle being automatically injected through one of the cluster's controllers. We can then mount that certificate into any of the Metering operand Pods that require access to that CA bundle.
- charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml adds an empty ConfigMap with the `service.beta.openshift.io/inject-cabundle="true"` annotation
- images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml adds another reconciliation item to the …
=> [release-4.4] Bug 1849221: Migrate to obtaining the service-serving CA bundle from a ConfigMap.

test/deployframework/helpers.go, test/e2e/metering_upgrade_test.go
We're seeing consistent upgrade failures due to the 4.5 metering-ansible-operator version in the redhat-operators CatalogSource custom resource not containing the PVC-related many-to-many fix. As a result, upgrade tests will fail as the pre-upgrade tests are reporting errors due to metrics not being correctly important (namely due to the aforementioned many-to-many bug), but the actual upgrade and tests against that upgrade are succeeding.
=> test: Upgrade from metering version that contains the 4.5 many-to-many fix.

hack/gather-test-install-artifacts.sh
This updates the test must-gather script to also grab the YAML output of all of the CRDs in the metering group during cleanup of a test installation.
=> hack: Gather the metering-related CRDs during test execution.

hack/e2e.sh
I was seeing the following output pop up occasionally in CI runs:
```bash
The connection to the server api.ci-op-tf0ln7ck-1deb1.origin-ci-int-aws.dev.rhcloud.com:6443 was refused - did you specify the right host or port?
Removing namespaces with the 'name=metering-metering-testing-ns' label
No resources found
Removing any testing labels that were added to the cluster's nodes
No resources found.
hack/e2e.sh: line 11: nodes[@]: unbound variable
make: *** [e2e] Error 1
+ touch /tmp/shared/exit
```
We attempt to grab the list of nodes in a cluster and populate that list as an array:
```bash
nodes=( $(kubectl get nodes -l metering-node-testing-label="true" --no-headers | awk '{ print $1 }') )
for i in "${nodes[@]}"
do
kubectl label node "$i" metering-node-testing-label- 2>/dev/null
done
``` …
=> hack: Fix array variable expansion in e2e.sh.

pkg/operator/aws_usage_hive.go, pkg/operator/datasources.go, pkg/operator/health.go, pkg/operator/hivetables.go, pkg/operator/operator.go, pkg/operator/prestotables.go, pkg/operator/promsum.go, pkg/operator/queues.go, pkg/operator/reportquery.go, pkg/operator/reports.go, pkg/operator/storage.go, pkg/operator/storagelocations.go, pkg/operator/types.go, pkg/operator/validation.go, pkg/operator/validation_test.go
Round 1 - go!
Let's see what clean up we can do here @timflannagan1.
This has the following commits that can be reviewed independently
1.  move the type declarations to their own file and try to comment them up for future readers
2.  since the reporting operator was not exporting anything, introduce an interface and unexport the type.  Consumers deal with the interface now
3.  move all the smaller validation blurbs from the various sections that are called during `New`, `newOperator`, and `Run` methods and consolidate on a single validation call to ensure the config is good during `New`.  No good config == no operator to run.  Bonus: Add tests for all validations
4.  rename cb* imports to remove references to chargeback
There are a couple questions sprinkled in where things weren't …
=> Operator refactor - validation and import cleanup

olm_deploy/Dockerfile.registry
This updates the base image to use ubi8 instead of the previous Golang image, which helps significantly cut down the size of this image and we don't need much more besides a basic linux environment to utilize this image throughout the testing suite.
=> olm_deploy: Use the ubi8-minimal base image for the registry Dockerfile.

test/e2e/report_static_input_data_test.go, test/reportingframework/datasource.go, test/reportingframework/db.go, test/reportingframework/framework.go, test/reportingframework/prestotables.go, test/reportingframework/report.go, test/reportingframework/service.go
All of the reportingframework methods, sans a couple, were severely lacking comments that explained what that method was trying to accomplish.
This also tries to make some of the imports naming a bit more consistent.
=> test: Add comments and perform general cleanup for the various reportingframework method and functions.

Dockerfile.metering-ansible-operator
With the migration of the ansible-operator base image to RHEL8, we need to install the `pip` rpm ourselves in order to utilize it.
=> Dockerfile: Install the pip3 rpm for the metering-ansible-operator

Makefile, hack/e2e.sh
This test was being ignored as hack/e2e.sh was only running any top-level tests that were in the test/e2e directory.
There are probably cleaner ways to do this but they involve re-organizing the reportingframework/deployframework to be in the test/e2e path, or moving the second `go test ...` call to its own make target and letting the `make e2e` target call that make target so we ensure that we're running both of those tests in the openshift CI environment.
Closes #1379
=> hack,Makefile: Explicitly run any of the test/deployframework tests.

test/reportingframework/db.go
Fix the trailing '/' delimiter in endpoint we build up to make POST requests against the reporting-operator API, injecting static json data into ReportDataSource database tables.
That trailing slash was problematic as we feed that variable into a fmt.Sprintf call in the form of `fmt.Sprintf("%s/%s/%s", ..., ..., ...)` which results in the following endpoint:
```
/api/v1/datasources/prometheus/store//metering-validhdfs-reportstaticinputdata
```
When we make the POST request to the API, we're getting back a 500 status code, indicating that the request body were sending may be empty. After some light investigation, it appears this is because of the endpoint we're passing to the helper function that wraps that POST call to the API.
=> test/e2e: Fix the Prometheus store API endpoint

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
The functionality for configuring the underlying Hive Metastore database to use a secret containing the username and password credentials for a mysql/postgresql instance was added early in the 4.6 release cycle so this isn't a regression from previous releases. When this feature was added, it looks like this field wasn't added as a property to the schema definition, which means that any user-provided MeteringConfig custom resource configuration that attempts to specify this secretName property will be rejected as it's considered an invalid schema definition (as the field is undefined) when using v1 CRDs.
These changes add the secretName property to the parent `db` object and runs `make metering-manifests` so the rendered YAML manifests are up-to-date.
=> Bug 1874652: Add the secretName property to the MeteringConfig CRD schema validation.

charts/openshift-metering/templates/openshift-reporting/report-queries/pod-cpu.yaml, charts/openshift-metering/templates/openshift-reporting/report-queries/pod-memory.yaml
This is a fix for Bug 1872425 where there were differences between the namespaces being listed between 2 namespace utilization reports. The discrepancy was caused by an improper JOIN which showed namespaces with usage but omitted namespaces without usage and request.
=> Bug 1872425: Fix missing namespaces in the case where usage exists without request 

Dockerfile.metering-ansible-operator.rhel8
Removes the COPY directive that attempts to copy the non-existent images/metering-ansible-operator/scripts path that was removed a couple of releases ago.
=> Bug 1872080: Remove copy directive for the non-existent scripts directory

hack/e2e.sh, hack/unit.sh
For now, the test/deployframework/... tests do not require a running cluster and can be moved outside of the e2e wrapper script into the list of paths the unit check is reponsible for running.
Fixes #1396
=> hack: Move the test/deployframework tests to the unit test script

test/e2e/main_test.go, test/e2e/manifests/meteringconfigs/nfs.yaml, test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-disabled.yaml, test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-enabled.yaml
With the migration to building the metering bundle and index images in CI, we needed to switch to a workflow that has smaller default AWS instance sizes than what we're use to running in CI, even when machine autoscaling has been enabled.
In order to schedule the reporting-operator Pods, we can limit the CPU requests which allows for the reporting-operator to fit inside of a recently scaled up machine.
This also renames some of the test/e2e/main_test.go test table names, which are used as a test namespace suffix as those names didn't make much sense in that context.
=> test/e2e: Reduce reporting-operator CPU requests and rename metering tests

pkg/operator/http_test.go, pkg/operator/reporting/templates_test.go, pkg/operator/reporting/validate_test.go, pkg/operator/reports_test.go, test/e2e/main_test.go, test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-enabled.yaml, test/e2e/report_dynamic_input_data_test.go, test/e2e/report_static_input_data_test.go, test/reportingframework/report.go, test/testhelpers/helpers.go
We need to test via e2e testing, the following situations:
~- [ ] Does a report that is depended on by a ReportQuery not get deleted despite reaching its expiration date?~
[We should add a test on the last item in another pass]
=> e2e: report expires with no dependency & does not expire with dependency

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, charts/openshift-metering/values.yaml
Fix the `persistentvolumeclaim-request-bytes` ReportDataSource promQL query to ensure that the `volumeName` label is not empty. Otherwise, we risk a many-to-many error when joining the two metric series.
=> Bug 1881650: Ensure the volumeName label is not empty in the kube_persistentvolumeclaim_info metric

Dockerfile.metering-ansible-operator.okd, Dockerfile.metering-ansible-operator.rhel, Dockerfile.metering-ansible-operator.rhel8
This package was used to feed Ansible logs into the ansible sidecar container that was removed earlier this release cycle as the ansible-operator removed it from their base image (as inotify-tools isn't in UBI8).
=> Dockerfile: Remove the inotify-tools yum package.

hack/gather-test-install-artifacts.sh
Updates the hack/gather-test-install-artifacts.sh bash script, adding the ServiceAccount resources to the namespace-scoped list of resources we're interested in gathering for an individual metering test installation.
=> hack: Gather all ServiceAccount resources in the test metering namespace

charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
Update the charts/openshift-metering reporting-operator Deployment object, ensuring that the correct ConfigMap path is specified when the user CA bundle is being injected into the containers.
Going through the [certificate injection using Operators documentation](https://docs.openshift.com/container-platform/4.5/networking/configuring-a-custom-pki.html), we can see that the required key is `ca-bundle.crt` and the required path name is `tls-ca-bundle.pem`.
Before, and not using the required path name, resulted in the following invalid symbolic links being produced in the reporting-operator container(s):
```bash
bash-4.2$ ls -alt /etc/pki/tls
total 12
drwxr-xr-x. 1 root root    21 Sep 18 17:13 ..
drwxr-xr-x. 5 root root    81 Sep 18 17:12 .
lrwxrwxrwx. 1 root root    49 Sep 18 17:12 …
```
=> Bug 1890741: Fix the path to the CA trust bundle ConfigMap

hack/gather-registry-artifacts.sh, test/e2e/main_test.go, test/testhelpers/helpers.go
Adds a hack script that's responsible for gathering the CatalogSource and the corresponding PackageManifest custom resources that were used to deploy a custom version of Metering.
Updates the test helpers, adding a function that calls that bash script is responsible for setting the correct environment variables based on the user-provided e2e flags. The main_test.go e2e driver will run this gather registry artifacts test helper function when the e2e suite has been instantiated without the `--run-dev-setup` flag.
=> hack,test: Gather the OLM registry resources during e2e runs

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel8
It looks like the `exec-entrypoint` sub-command was removed from the ansible-operator during the 0.19.x release but a poor 4.6 rebase for ocp-operator-sdk resulted in that field still being used. Here is the updated version after that's been corrected downstream: https://github.com/openshift/ocp-release-operator-sdk/blob/master/release/ansible/bin/entrypoint#L4
=> Dockerfile: Remove the exec-entrypoint ansible-operator subcommand.

Dockerfile.metering-ansible-operator
Update the dev Dockerfile.metering-ansible-operator to use the upstream operator-framework/ansible-operator base image instead of the downstream fork.
Before, you were unable to build this image locally due to the push to using RHEL8 images downstream, but this Dockerfile is used solely for local developmental purposes and isn't used in the CI/ART pipelines.
The operator-framework/ansible-operator Dockerfile uses UBI8 as their base image, so `pip3` usage is now required.
=> Dockerfile: Use the upstream ansible-operator base image

test/e2e/ensure_leader_election_configmap_is_created_test.go, test/e2e/main_test.go
Add a new post-install test that ensures that a ConfigMap is present that is used to determine the Metering Operator leader election.
Update the test/e2e/main_test.go e2e entry-point function, adding this post-install function to the list of tests that will run against the static data input Metering installation.
=> test/e2e: Add a post-install test that ensures the Metering leader election ConfigMap is present

Dockerfile.src
Update the build_root container image that is used to run checks in CI. The `opm` binary will be used throughout our repository to keep the OLM manifests stored in the package manifest format in line with the new bundle packaging format.
=> Dockerfile: Add the opm CLI to interact with operator-registry and build indexes of operator content

test/e2e/main_test.go
The logrus.Fatal logging level logs an entry at the fatal level and then calls os.Exit(1) after logging. This is problematic in the case of main_test.go where we expect that a custom defer function will be called if something problematic happens after creating the registry resources. If we instead log that error to the error log level and then return 1, we can continue getting the same behavior, but the defer function will still be ran.
=> test/e2e: Avoid using the fatal logrus level in the main_test.go

Dockerfile.src
We're starting to get rate limited when using the openshift/origin-golang-1.15 image in the build_root test container image.
We can instead use the registry.svc.ci.openshift.io registry as the tests will already have access to that registry in the CI environment.
=> Avoid using docker.io images in the build_root image

Dockerfile.src, hack/scl-operator-courier.sh
Changes:
- hack: Remove the unused bash script that installs the `operator-courier` package using SCL.
- Dockerfile.src: Stop installing the operator-courier package.
=> hack,Dockerfile: Stop installing the operator-courier package

bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml, charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml
There's no quay.io/coreos/metering-ansible-operator:4.7 image tag, but there is a release-4.7 one that got overridden by the PR that bumped all of the image tags to 4.7.
=> charts,manifests: Fix the invalid metering image tag in the upstream CSV manifest

hack/gather-registry-artifacts.sh
Update the hack/gather-registry-artifacts.sh bash script, and gather the overall list of PackageManifest custom resources that are stored in the openshift-marketplace namespace.
During an individual CI run, the e2e suite is responsible for creating a CatalogSource custom resource that references an index image that the ci-operator creates before a cluster is created. When the corresponding PackageManifest custom resource is not created from that CatalogSource, then querying for the "catalog-namespace=openshift-marketplace,catalog=metering-dev" label selector will return a list of zero indices so this would provide additional debugging measures to help determine if there's something wrong on the metering bundle side-of-things, or OLM side-of-things.
=> hack: Gather all the PackageManifests in a test cluster

bundle/manifests/hive.crd.yaml, charts/metering-ansible-operator/templates/crds/hive.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml, manifests/deploy/openshift/olm/bundle/4.7/hive.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml, manifests/deploy/upstream/olm/bundle/4.7/hive.crd.yaml
Update the charts/metering-ansible-operator/templates/crds/hive.crd.yaml HiveTable CRD schema definition, and ensuring that the status.partitions property can be nullable.
During the effort to migrate from v1beta1 to v1 apiextensions.k8s.io CRDs in the 4.6 release, all possible properties in the HiveTable CRD need to be defined in the schema definition, else the apiserver would prune those undefined fields. The `status.partitions` field was defined as an array of objects, which is problematic in the case of existing HiveTable custom resources that had `status.partitions: null` being set. During an upgrade from a supported release to the 4.6 channel, the upgrade failed as OLM couldn't apply the new HiveTable CRD version against the existing set of HiveTable custom resources defined in the …
=> Bug 1898373: Fix the HiveTable status.partitions schema definition

Dockerfile.src, Makefile
Update the Dockerfile.src (build root Dockerfile for CI) and add the `operator-sdk binary` to the container image.
Update the Makefile and expose a `verify-bundle` target, which is responsible for running the `operator-sdk bundle validate ./bundle` command to validate the Metering bundle metadata/manifest contents.
Note: this validation of manifests for OLM consumption was previously covered by the `operator-courier` utility, but that utility doesn't support validating apiextensions.k8s.io/v1 CRD types so that check was removed.
=> Dockerfile,Makefile: Add a make target that verifies the metering bundle contents are valid

Dockerfile.reporting-operator
Align the Golang version used between the dev Dockerfile and the CI/ART Dockerfile (Dockerfile.reporting-operator.rhel).
=> Dockerfile: Bump the Golang version in the reporting-operator base image

Dockerfile.src
Update the Dockerfile.src (build root Dockerfile for CI tests) and use a release-versioned Helm image tag instead of the `latest` tag.
This is needed as the Helm version has recently been bumped to use the 3.x versioning, which comes with some slight breaking changes to the templating logic.
Note: this commit needs to be force-merged in order to have these changes propagate to CI tests.
=> Dockerfile.src: Avoid using the latest Helm image tag

go.mod, vendor/modules.txt
Update the Golang version listed in.mod and run `make vendor` to propagate changes to the vendored dependencies.
=> go.mod,vendor: Bump the Go version in go.mod

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel8, bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml, charts/metering-ansible-operator/templates/_helpers.tpl, charts/metering-ansible-operator/values.yaml, images/metering-ansible-operator/watches.yaml, manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/openshift/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml, manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/upstream/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml, test/e2e/ensure_leader_election_configmap_is_created_test.go
Update the metering-ansible-operator to use the ansible-operator v1.x version. There are a few breaking changes between the 0.x and 1.x version of the operator-sdk, but we utilize very few of those CLI utilities which lower the number of changes necessary to migrate to this new major version.
With the v1 binary, the ansible-operator now expects a `run` command:
```bash
bash-4.4$ /usr/local/bin/ansible-operator help
Usage:
ansible-operator [command]
Available Commands:
help        Help about any command
run         Run the operator
version     Prints the version of operator-sdk
Flags:
-h, --help   help for ansible-operator
Use "ansible-operator [command] --help" for more information about a command.
```
The watches.yaml file, which contains the API definition for resources that the …
=> Migrate to using the v1.x ansible-operator

cmd/deploy-metering/main.go, cmd/helpers/helpers.go, cmd/reporting-operator/start.go
Add the cmd/helpers, helpers package. This a centralized location for CLI helpers that can be called in existing CLI tooling.
Update the cmd/[deploy-metering/reporting-operator] CLI tooling, move some of the helper functions stored in those main packages, into the CLI helpers package.
=> cmd: Add a CLI helpers package

Dockerfile.reporting-operator, Dockerfile.src
Update any CI-related Dockerfile to avoid using any dockerhub.io images to reduce pull rate-limited errors.
=> Dockerfile: Avoid using docker.io base images

charts/metering-ansible-operator/templates/crds/hive.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml, manifests/deploy/openshift/olm/bundle/4.6/hive.crd.yaml, manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml, manifests/deploy/upstream/olm/bundle/4.6/hive.crd.yaml, olm_deploy/bundle/manifests/hive.crd.yaml
---
Manual cherry-pick of #1443 
---
Update the charts/metering-ansible-operator/templates/crds/hive.crd.yaml HiveTable CRD schema definition, and ensuring that the status.partitions property can be nullable.
During the effort to migrate from v1beta1 to v1 apiextensions.k8s.io CRDs in the 4.6 release, all possible properties in the HiveTable CRD need to be defined in the schema definition, else the apiserver would prune those undefined fields. The `status.partitions` field was defined as an array of objects, which is problematic in the case of existing HiveTable custom resources that had `status.partitions: null` being set. During an upgrade from a supported release to the 4.6 channel, the upgrade failed as OLM couldn't apply the new HiveTable CRD version against the existing set of …
=> [release-4.6] Bug 1897379: Fix the HiveTable status.partitions schema definition

Dockerfile.metering-ansible-operator
This is causing new 4.5 installations to fail in CI as the images are using the Helm 3.x version that was bumped during the 4.7 release cycle, but we expect that we're working with a helm 2.x version in previous releases.
=> [release-4.5] Dockerfile: Avoid using the latest tag for the Helm image in CI

Documentation/configuring-reporting-operator.md
Enhanced the docu to clarify the configuration to use Basic Auth and htpasswd, especially with the right parameter combination (createSecret and htpasswd.data)
imo, we should also update here the OpenShift docu, with such details. But I do not know where/how.
https://docs.openshift.com/container-platform/4.5/metering/configuring_metering/metering-configure-reporting-operator.html#metering-basic-authentication_metering-configure-reporting-operator
=> Enhance docu for Basic Auth with htpasswd.data

Documentation/configuring-hive-metastore.md, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_metastore.yml, test/e2e/main_test.go, test/e2e/metering_manual_install_test.go
Update the Hive metastore deployment to fix compatibility issues
when deploying metering using a non-mysql-5.7 version.
Update the `configuring-hive-metastore.md`  documentation and 
remove the reference to the BZ mentioning metering integration 
issues with any non-mysql-5.7 versions.
Update the hive-scripts ConfigMap entrypoint.sh script, which gets
called in the Hive metastore and server StatefulSets and is responsible
for starting those containers.
In the case of derby (the default) databases, using this tool isn't
necessary and will cause issues when running it against an already
exists schema. This tool is needed in order to get metering working
again with MySQL and PostgreSQL versions.
Update the Hive metastore and server StatefulSets and expose an
additional environment variable, …
=> Bug 1838802: Fix compatibility issues when using MySQL 8.0+ as the underlying Hive metastore database

Documentation/configuring-hive-metastore.md, charts/openshift-metering/templates/hive/hive-configmap.yaml, test/e2e/inspect_hive_site_xml_test.go, test/e2e/main_test.go
In the pre-GA (4.2) days, we supported configuring a PostgreSQL database for usage as the underlying database for the Hive metastore and server deployments. Since GA, using this functionality resulted in no Prometheus metrics being inserting into tables in Hive. This was caused by the Hive components hanging (e.g. reaching a deadlock state) when attempting to create the default `ReportDataSource` metric importer tables.
This builds off of #1463 which introduces the `$HIVE_UNDERLYING_DATABASE` environment variable and using `schematool` to do the schema initialization for non-derby databases.
- Update the `configuring-hive-metastore.md`  documentation and remove the reference to the BZ mentioning metering integration issues with any Postgres version.
- Update the …
=> Bug 1838845: Fix Hive metastore deployment with using PostgeSQL as the underlying database

test/e2e/main_test.go, test/e2e/manifests/meteringconfigs/mysql.yaml
We're currently seeing metering e2e runs fail as OLM can't create the
metering installation due to conflict errors when updating resources
(typically CRDs), so this _attempts_ to try and space those go routines
out.
=> test/e2e: Deflate the MySQL e2e test

test/e2e/report_dynamic_input_data_test.go, test/e2e/report_expiration_tests.go, test/reportingframework/report.go
Update these report expiration subtest functions that are responsible
for testing the expiration functionality. Before, some of these report
objects that were created were flat out invalid, especially in the case
of the testing the rollup report scenarios.
In the case of the testing rollup reports, we need to create a
reportquery custom resource that acts as the aggregate query and sits
between the sub-report and the aggregate report. Then, we can list that
sub-report as an input to the aggregate report while still referencing a
valid reportquery custom resource.
=> test: Fix the Report expiration subtest handler functions

Dockerfile.src
Update the Golang base image we pull from to use the one from the
registry.svc.ci.openshift.org registry due to rate limiting when pulling
from dockerhub.
=> [release-4.6] Dockerfile: Avoid using dockerhub images in the testing root image

test/e2e/metering_manual_install_test.go
Update the error check when attempting to create the test output
directory for an individual test to use the require package instead of
assert.
In the metering-upgrade-aws test handler, we already use require instead
of assert so this is aligning both of those handlers.
=> test/e2e: Require no error when creating the test output directory

test/e2e/metering_manual_install_test.go
Update the MySQL and NFS pre-installation functions to use the correct
namespace label in the form of `name: <namespace_prefix>-metering-testin-ns`.
During the teardown function of the hack/e2e.sh bash script, which
serves as the entrypoint to the e2e suite, we search for any namespaces
that match that label, and attempt to delete them unless the e2e suite
has been run in developer mode.
Previously, the namespaces that were created as a result of these MySQL
and NFS pre-installation functions create a `name` label containing the
actual namespace, and not the prefix supplied to the e2e suite, in the
context of an individual install. This led to those namespaces not being
properly purged at the cleanup call site.
Other changes in this commit include:
- Aligning the grouping of package …
=> test/e2e: Ensure all e2e test namespaces use correct label

pkg/deploy/deploy.go, pkg/deploy/install.go, pkg/deploy/uninstall.go
Update all of the `Deployer` structure fields and export those fields.
We don't have much of a need to have these fields unexported, and
updating any of the `Config` field structure values is impossible
without constructing a new instance.
=> pkg/deploy: Export the Deployer fields

test/deployframework/context.go, test/e2e/main_test.go, test/e2e/metering_manual_install_test.go, test/e2e/metering_upgrade_test.go
Update the deployframework and e2e packages and remove all of the
safeguards around checking if installations are safe to run post-install
tests against. Remove any expectErr or expectErrMsgs type properties
from the main test handler and just always exit early if there's an
error during the Setup method.
=> test: Remove safeguards in e2e test handlers when expecting errors

test/e2e/main_test.go, test/e2e/metering_manual_install_test.go
Add an additional top-level that ensures that invalid MeteringConfig
custom resources report an error when attempting to create those custom
resources against the current set of CRDs. Also, validate that the errors
returned from the client-go .Create interface match what we expect.
=> test/e2e: Add a top-level test that tests invalid MeteringConfig manifests

cmd/deploy-metering/main.go, pkg/deploy/deploy.go, pkg/deploy/uninstall.go, test/deployframework/framework.go, test/deployframework/framework_test.go
Rename the `DeleteCRB` field to `DeleteCRB` to match the naming of the
other delete-related fields in the `Config` structure.
=> cmd,pkg,test: Rename the DeleteCRB -> DeleteCRBs for the Config structure

test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/framework_test.go, test/deployframework/helpers.go, test/deployframework/registry.go, test/e2e/main_test.go, test/e2e/metering_manual_install_test.go, test/e2e/metering_upgrade_test.go
Update the e2e package to deal with InstallPlan failures that we have no
control over. Currently, OLM will mark an InstallPlan as failed when it
encounters any errors, regardless of the context around that error.
In the context of metering, we're seeing more and more e2e flakes
centered around installations not being able to be installed due to
failed InstallPlan resources. These failed installations are typically
due to CRD conflicts being returned from the apiserver and OLM not
handling that error correctly and the result is metering can't be
installed.
We can workaround this by detecting any failed InstallPlan resources
that we know are due to conflicting resource versions and attempt to
re-install metering in the applicable test handlers.
=> test: Handle failed InstallPlans during e2e installations

test/deployframework/registry.go, test/e2e/metering_manual_install_test.go
Update the Setup method for the deployer context structure and ensure
we're zero-ing out the previous failed InstallPlan error we're handling
to avoid failing that particular top-level test metering installation.
=> test/e2e: Fix failed InstallPlan handling in test setup code

Dockerfile.src, Makefile
Remove the `operator-courier` dependency that was previously used to verify the metering manifests. During the 4.6 release cycle, we updated the metering-related CRDs to use the apiextensions.k8s.io/v1 version, which `operator-courier` is unable to process. As a result, we commented out any make targets that attempted to call this dependency but failed to remove that dependency from the root CI build Dockerfile.
=> [release-4.6] Remove operator-courier from the root Dockerfile

hack/gather-test-install-artifacts.sh
Update the gather testing artifacts bash script and ensure we gather the
`kubectl describe <pod> ...` output for each Pod in a testing namespace.
=> hack: Ensure we gather the Pod description artifacts during e2e runs

test/e2e/main_test.go
Update the main testing package and mark the NFS and node selector e2e test to be gated on the `testing.Short()` value we derive from the hack/e2e.sh bash script (entry point to the e2e suite).
Remove the Prometheus connector post-install test from the list of valid tests as we removed that functionality from the Operator.
=> test/e2e: Reduce number of metering e2e tests per-run

Makefile
Update the Makefile and expose a variable that allows users to provide
extra container run flags to the various make container-related targets.
This is useful in the case where you are running into issues around
insufficient permissions when attempting to read from mounting volumes
in the container.
=> Makefile: Support passing a list of extra container run flags

pkg/operator/reports.go
Update the Report handler and avoid requeueing a Report that is
reporting an `expired` status. Before, this would result in the
reporting-operator hot looping as this Report custom resource would
continue to get queued up.
Instead, if we're encountering a Report that
has reached its expiration date, then we should avoid processing it in
the Report handler function and let the call site determine how to
process that Report further in the next cycle.
=> Bug 1926984: Avoid requeueing an expired Report

test/deployframework/context.go, test/e2e/main_test.go, test/e2e/metering_upgrade_test.go
Update the e2e package and remove all installErr and installErrMsgs
parameter handling.
=> test/e2e: Cleanup install and upgrade test helper functions

cmd/deploy-metering/main.go, pkg/deploy/deploy.go, pkg/deploy/install.go, pkg/deploy/uninstall.go, test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/framework_test.go, test/deployframework/helpers.go, test/deployframework/registry.go, test/e2e/main_test.go, test/e2e/metering_manual_install_test.go, test/e2e/metering_upgrade_test.go
Cherry-pick of all of the e2e and deploy package changes needed to fix how we handle failed InstallPlan custom resources in the various metering test installations we created.
=> [release-4.7] Handle failed InstallPlans in metering test installations

cmd/deploy-metering/main.go, pkg/deploy/deploy.go, pkg/deploy/install.go, pkg/deploy/uninstall.go, test/deployframework/context.go, test/deployframework/framework.go, test/deployframework/framework_test.go, test/deployframework/helpers.go, test/deployframework/registry.go, test/e2e/main_test.go, test/e2e/metering_manual_install_test.go, test/e2e/metering_upgrade_test.go
Cherry-pick of all of the e2e and deploy package changes needed to fix how we handle failed InstallPlan custom resources in the various metering test installations we created.
=> [release-4.6] Handle failed InstallPlans in metering test installations

test/e2e/manifests/machines/clusterautoscaler.yaml
Update the clusterautoscaler.yaml YAML manifest that is used to create
a `ClusterAutoscaler` instance in our testing clusters, and disable node
scaling down mechanisms.
We're seeing more and more e2e flakes centered around the
reporting-operator being scaled down at inopportune times, namely when
attempting to get Report results. In the context of our e2e suite, these
additional nodes should be swept up when uninstalling the OCP cluster.
Note: Another way to ensure we're not evicting the reporting-operator
container from a particular node is to add the following label to that
deployment definition:
```yaml
metadata:
labels:
cluster-autoscaler.kubernetes.io/safe-to-evict=false
```
Adding this label doesn't make much sense given the reporting-operator
container isn't a workload that we …
=> test/e2e: Disable ClusterAutoscaler scaling down testing nodes

Documentation/configuring-hive-metastore.md
After updating the MySQL connector/J JDBC driver version in the Hive
image, we're now seeing problems with running newer versions of Metering
with older MySQL server versions (e.g. 5.6, 5.7). When diving into the
MySQL Pod logs, we may see the `"[NOTE] Bad handshake"` message logged,
which may indicate we're attempting to authenticate from the client
using TLS 1.2 or TLS 1.3 during the handshake. This is likely because
earlier MySQL server versions only support TLS 1.1 versions and earlier,
so we need to explicitly document this behavior.
=> Documentation: Update the MySQL Hive Metastore configuration docs

Makefile
Specify a .PHONY target for the make vendor target. This ensure that
running `make vendor` will always be considered "out-of-date" and all
the modules will commands be run.
=> Makefile: Add .PHONY target for vendor check

bundle/manifests/meteringoperator.v4.8.0.clusterserviceversion.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.8/meteringoperator.v4.8.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.8/meteringoperator.v4.8.0.clusterserviceversion.yaml
Add deprecation notice to the Metering CSV YAML manifests
- Update the name from `Metering` to `Metering (Deprecated)`
- Add deprecation notice to the long description. Link to the 4.6 OpenShift release notes.
- Add deprecation notice to the short description.
Needs to be backported to the release-4.6 branch.
=> Bug 1939121: Add deprecation notice to the Metering CSV YAML manifests

bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml
Manual cherry-pick of #1519.
- Update the name from `Metering` to `Metering (Deprecated)`
- Add deprecation notice to the long description. Link to the 4.6
OpenShift release notes.
- Add deprecation notice to the short description.
Likely needs to be backported to the release-4.6 branch as well.
=> [release-4.7] Bug 1940584: Add deprecation notice to the Metering CSV YAML manifests
