charts/openshift-metering/values.yaml, hack/lib/init.sh, hack/openshift-install.sh, hack/openshift-uninstall.sh, jenkins/deploy.groovy, jenkins/vars/testRunner.groovy
This cluster is on Openshift origin 3.10 and is a fresh install. The
existing cluster is fine but is in a bad state because I tried to
upgrade it which didn't go well due to not running the upgrade
playbooks.
=> jenkins: Test deploying against a new openshift cluster

Documentation/using-metering.md, Documentation/writing-custom-queries.md, test/framework/chargeback.go
Update to using http instead of 8080 in tests too
=> Documentation,test: Fix proxy URL to metering service in docs

charts/helm-operator/templates/role.yaml, charts/helm-operator/templates/rolebinding.yaml, charts/metering-operator/templates/metering-rbac.yaml, manifests/deploy/generic/helm-operator/metering-helm-operator-role.yaml, manifests/deploy/generic/helm-operator/metering-helm-operator-rolebinding.yaml, manifests/deploy/openshift/helm-operator/metering-helm-operator-role.yaml, manifests/deploy/openshift/helm-operator/metering-helm-operator-rolebinding.yaml, manifests/deploy/tectonic/helm-operator/metering-helm-operator-role.yaml, manifests/deploy/tectonic/helm-operator/metering-helm-operator-rolebinding.yaml
Found in https://github.com/openshift/openshift-ansible/pull/9426#pullrequestreview-143247126 via QE: https://bugzilla.redhat.com/show_bug.cgi?id=1597334
=> charts,manifests: Update all v1beta1 RBAC resources to v1

Documentation/metering-config.md
The ordering was a bit weird and the section on setting the PVC size
deserves it's own heading.
=> Documentation: Organize PVC documentation

charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-service.yaml, charts/presto/templates/presto-worker-deployment.yaml, manifests/prometheus-operator/rbac/role-and-binding-openshift-metering-ns.yaml, manifests/prometheus-operator/service-monitors/presto-service-monitor.yaml, manifests/prometheus-operator/service-monitors/reporting-operator-service-monitor.yaml
Also adjusts our Presto service to separate metrics so we can scrape
from the workers too
=> Add ServiceMonitors for prometheus-operator/cluster-monitoring

README.md
We have a bunch of great content that we're not showing off!
=> readme: add links to docs

Documentation/install-metering.md
updated the documentation to reflect the new pods, @chancez, PTAL.  Thanks!
=> expected pods have changed

pkg/operator/datasources.go, pkg/operator/generate_report.go, pkg/operator/query.go, pkg/operator/queues.go, pkg/operator/reports.go, pkg/operator/scheduled_reports.go, test/e2e/report_test.go, test/e2e/scheduled_report_test.go
Also fix missing error check in validateDependencyStatus and improve e2e logging
=> Refactor pkg/operator to re-use more common logic for sync handlers and re-queuing

pkg/apis/metering/v1alpha1/util/scheduled_report_util.go, pkg/operator/scheduled_reports.go
=> pkg/operator: Handle ScheduledReport reportingEnd going from set to unset

pkg/operator/http.go
Fixes an error when maps exist in the columns of a ReportGenerationQuery, since we cannot flatten those structures in CSV/Tabular format. So use TableHidden to always filter these columns from tabular/csv formatted results in both v1 and v2 endpoints.
=> pkg/operator: Always hide TableHidden columns if output is CSV or Tabular

.gitattributes
See https://github.com/github/linguist/#generated-code for details
=> Add .gitattributes to mark generated files in Github

Documentation/dev/developer-guide.md, Documentation/dev/release.md, VERSION, hack/lib/version.sh
Adds an initial draft of how I do our release process, so others can do it.
=> Document release process

pkg/operator/datasources.go
In the previous "else" case, after a recent change, the code incorrectly
used := instead of =, meaning the importer variable in the case of an
importer not existing, was not correctly being assigned to, and was
being shadowed in the else case. This corrects that problem by using a
closure to return the importer instead, which also fixed another issue
in not correctly unlocking the Mutex if creating the prometheus
connection failed by using defer.
=> pkg/operator: Fix panic caused by incorrect assignment

Documentation/report.md
Another of the docs weaknesses that I found when working on #424
=> Documentation/report: add custom inputs info

pkg/operator/scheduled_reports.go
It's possible the scheduledReport table could already exist when seeing a new report due to a previous failed cleanup, so this just makes the handler more robust.
Ensures that the scheduledReport table is empty when we're handling a new scheduledReport by checking for status.tableName.
Additionally, we can avoid doing the createTable and updating the CR if if the status.tableName is set.
=> Drop scheduledReport table before creating

Documentation/dev/release.md
Adds some brief documentation on doing manual testing and also how to pull in changes into a release branch.
=> Documentation: Add new sections to release doc

Dockerfile.e2e, Dockerfile.metering-operator.rhel, Dockerfile.reporting-operator.rhel, Documentation/dev/developer-guide.md, Documentation/dev/ocp-images.md, Makefile, hack/ocp-util/ocp-brew-pulp-metering-chart-values.yaml, hack/ocp-util/ocp-image-pull-and-rename.sh, hack/ocp-util/ocp-metering-chart-values.yaml, hack/ocp-util/redhat.repo, hack/ocp-util/subscription-manager.conf
We're being asked to have RHEL dockerfiles for everything soon so this is just
doing that while also making some updates to make building these locally
easier.
=> *: Add rhel versions of Dockerfiles and tooling to help build

pkg/operator/reporting/validate.go
When refactoring code to handle transient ReportDataSources the lookup
of the direct ReportDataSource dependencies was accidently removed.
=> pkg/operator/reporting: Fetch direct ReportDataSource dependencies

cmd/reporting-operator/start.go, hack/run-local-with-port-forward.sh, pkg/operator/operator.go
Fixes the script to work with openshift and adds a few new options to make it easier to interact with the Prometheus running in the cluster.
=> Fixup local port-forward scripts

jenkins/continuous-upgrade.groovy
Acts as a trigger for the downstream continuous upgrade job.
=> jenkins: Add back continuous upgrade job

charts/openshift-reporting/templates/prom-queries/persistentvolumeclaim-phase.yaml, charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-phase.yaml, charts/openshift-reporting/values.yaml
Happy to wait and rebase when you merge your other PR.
=> reporting-operator: add pv phase

pkg/operator/prestostore/prometheusmetric.go
Fix unchecked WriteString call, and improve returned error message to
allow differentiating which insert failed
=> pkg/operator/prestostore: Check errors writing to buffer and improve errors

pkg/apis/metering/v1alpha1/util/scheduled_report_util.go, pkg/operator/queues.go, pkg/operator/reports.go, pkg/operator/scheduled_reports.go, test/e2e/scheduled_report_test.go, test/framework/collect.go
Add validation for generationQuery being set and reportingStart being before reportingEnd for reports and scheduledReports.
=> pkg/operators: Improve validation of scheduledReports and reports

Dockerfile.e2e, Dockerfile.metering-operator, Dockerfile.metering-operator.rhel, Dockerfile.reporting-operator, Dockerfile.reporting-operator.rhel
This should cause yum to fail when a package is missing.
=> Dockerfile.*: Pass --setopt=skip_missing_names_on_install=False to yum

charts/hdfs/templates/datanode-statefulset.yaml, charts/hdfs/templates/namenode-statefulset.yaml, charts/helm-operator/templates/deployment.yaml, charts/presto/templates/hive-metastore-statefulset.yaml, charts/presto/templates/hive-server-statefulset.yaml, charts/presto/templates/presto-coordinator-deployment.yaml, charts/presto/templates/presto-worker-deployment.yaml, charts/reporting-operator/templates/reporting-operator-deployment.yaml, manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Update resources in deployments, statefulsets, etc to apps/v1
=> charts: Update resources in apps apiGroup apiVersion to v1 from v1beta1

Documentation/configuring-reporting-operator.md, Documentation/dev/builds.md, Documentation/manual-install.md, Documentation/using-metering.md, Documentation/writing-custom-queries.md
I left out this one, not sure how to change it.
> If your not Openshift or using [kube-prometheus][kube-prometheus] on non-openshift clusters,
=> your -> you're

.gitignore, Dockerfile.src, Makefile, hack/unit.sh
Generate junit reports for go unit tests and support adjusting output to allow collecting as artifacts in origin CI
=> Add junit reports to unit tests

charts/helm-operator/templates/cr.yaml, charts/helm-operator/values.yaml, manifests/deploy/common-helm-operator-values.yaml, manifests/deploy/openshift-helm-operator-values.yaml, manifests/deploy/openshift/helm-operator/metering.yaml
=> charts,manifests: Update generated metering CR used by scripts to use {} as default spec

Documentation/configuring-telemeter.md, Documentation/index.md, charts/telemeter-reporting/Chart.yaml, charts/telemeter-reporting/templates/datasources.yaml, charts/telemeter-reporting/templates/prom-queries/machine-cpu-cores-by-cluster-id.yaml, charts/telemeter-reporting/templates/report-queries/machine-cpu-cores-by-cluster-id.yaml, charts/telemeter-reporting/values.yaml
This pull request adds:
* telemeter-reporting chart
* chart with telemeter-specific queries
* documentation on setting up Metering to use Telemeter and telemeter-reporting chart
=> telemeter-reporting: add basic telemeter chart

hack/e2e-test-runner.sh, jenkins/vars/testRunner.groovy
Collects Reports, ReportGenerationQueries, and ReportDataSource
resources before deleting the namespace, and also adds junit reports
based on test results.
=> jenkins,hack: Improve test runner to collect more information at end of tests

hack/lib/tests.sh
Goes with https://github.com/openshift/release/pull/3140
=> hack: Update image tag used for origin CI

Documentation/dev/jenkins.md
This fixes everytime and a stray lowercase Jenkins
=> Jenkins Dev Doc Fix

pkg/operator/operator.go, pkg/operator/reporting/health.go
Match the health check tablename to it's location
=> pkg/operator: Fix metering health check table name

Dockerfile.metering-ansible-operator, Makefile, images/metering-ansible-operator/build/test-framework/Dockerfile, images/metering-ansible-operator/build/test-framework/ansible-test.sh, images/metering-ansible-operator/deploy/crds/metering_v1alpha1_meteringconfig_cr.yaml, images/metering-ansible-operator/deploy/crds/metering_v1alpha1_meteringconfig_crd.yaml, images/metering-ansible-operator/deploy/operator.yaml, images/metering-ansible-operator/deploy/role.yaml, images/metering-ansible-operator/deploy/role_binding.yaml, images/metering-ansible-operator/deploy/service_account.yaml, images/metering-ansible-operator/roles/meteringconfig/README.md, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/handlers/main.yml, images/metering-ansible-operator/roles/meteringconfig/meta/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml, images/metering-ansible-operator/roles/meteringconfig/vars/main.yml, images/metering-ansible-operator/watches.yaml
Though this passed CI, this is unlikely not work out of the box.
Issue:
1. Dependencies Needed
Ansible Version 2.6.0 and up
Ansible-Runner 1.1.0 and up
Ansible-Runner-Http 1.0.0 and up
2. Think I need to remove `size` from `roles/meteringconfig/defaults/main.yml`
3. Image names are hardcorded into `deploy/operator.yaml`
4. Operator SDK usage also we need to think about what Namespace
=> Add Metering Ansible Operator 

Documentation/metering-architecture.md
link target was moved to separate page
=> fixed link to aws billing correlation

Dockerfile.metering-operator, Dockerfile.metering-operator.rhel
/hold
Hold until https://github.com/openshift/release/pull/3992 and https://github.com/openshift/ocp-build-data/pull/139 are merged.
=> Remove metering-helm-operator Dockerfiles

Dockerfile.metering-ansible-operator, Dockerfile.metering-ansible-operator.rhel, hack/ocp-util/redhat.repo
=> metering-ansible-operator: Install tini to cleanup zombie processes created by ansible

pkg/operator/datasources.go, pkg/operator/http.go, pkg/operator/http_test.go, pkg/operator/operator.go, pkg/operator/promsum.go, pkg/operator/reportingutil/util.go, pkg/operator/reports.go, pkg/presto/util.go, test/framework/datasource.go, test/framework/prestotables.go
Also updates e2e/integration tests to ensure the PrestoTable referenced by
ReportDataSources exist and have a status.tableName.
=> Fix lookup of DataSource table name in Prometheus store/fetch API

charts/openshift-metering/templates/hadoop/hadoop-configmap.yaml
=> charts: HDFS: Fix toplogy script location

images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Some how this task file was missed previously.
=> roles/meteringconfig: Add reconcile_metering.yml to reconcile task

Documentation/configuring-aws-billing.md, Documentation/configuring-storage.md, charts/metering-ci/templates/metering.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-authenticated-emails-secret.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-cookie-secret.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-htpasswd-secret.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-rbac.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-aws-credentials-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-cluster-monitoring-view-rbac.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-tls-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-prometheus-bearer-token-secrets.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-prometheus-certificate-authority-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-service.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-tls-secrets.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml, manifests/metering-config/advanced-auth.yaml, manifests/metering-config/aws-billing.yaml, manifests/metering-config/custom-node-selectors.yaml, manifests/metering-config/default-resource-limits.yaml, manifests/metering-config/expose-route.yaml, manifests/metering-config/recommended-resource-limits.yaml
Updates the MeteringConfig spec.reporting-operator section to have more
consistency in configuring options. This is the first of many changes,
where I will be updating all components to have consistency across
components and consistency within components.
=> charts,images,manifests: Update reporting-operator configuration schema

charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/metering-ansible-operator/templates/operator/meteringconfig.yaml, charts/metering-ansible-operator/values.yaml, images/metering-ansible-operator/watches.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml, manifests/metering-config/advanced-auth.yaml, manifests/metering-config/aws-billing.yaml, manifests/metering-config/custom-node-selectors.yaml, manifests/metering-config/default-resource-limits.yaml, manifests/metering-config/default.yaml, manifests/metering-config/expose-route.yaml, manifests/metering-config/hdfs-storage.yaml, manifests/metering-config/latest-versions.yaml, manifests/metering-config/metastore-storage.yaml, manifests/metering-config/recommended-resource-limits.yaml, manifests/metering-config/s3-storage.yaml, manifests/metering-config/shared-storage.yaml
/hold
#786 and #783 should be merged first.
=> charts,images,manifests: Update MeteringConfig CRD API version from v1alpha1 to v1

charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
Closes #796
This fixes the immediate issue but I did not build the whole stack to test it.
=> Update defaultMode of presto configmap

charts/metering-ansible-operator/templates/crds/report.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/report.crd.yaml
This would add validation of the Report CRD fields using the OpenAPI V3 schema specification.
=> Update the Report CRD to use OpenAPI V3 schema validation.

charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/reportdatasource.crd.yaml
This would add schema validation to the `ReportDataSource` CRD using OpenAPI V3.
=> Update the ReportDataSource CRD to use the OpenAPI V3 schema validation.

Documentation/olm-install.md
`oc new-project metering` works.
=> Updates docs: oc create project-> new-project

Documentation/dev/developer-guide.md, manifests/metering-config/hdfs-minimal.yaml
Documentation,manifests; Add minimal HDFS configuration example in developer-guide docs
=> Documentation,manifests; Add minimal HDFS configuration example in developer-guide docs

images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Also updates storage validation tasks to use assert module
=> roles/meteringconfig: Verify azure storage credentials secret is specified

Documentation/configuring-reporting-operator.md, Documentation/metering-architecture.md, Documentation/using-metering.md, Documentation/writing-custom-queries.md
Mostly same as a squashed version of PR 878, redone for git flow corrections.
=> jq -r fixes to docs and a typo fix

pkg/operator/http.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1736501
=> pkg/operator: Iterate over columns to ensure consistent values ordering

Documentation/configuring-storage.md, charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl, charts/openshift-metering/templates/hadoop/hadoop-s3-compatible-credentials.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/_hive_helpers.tpl, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-s3-compatible-credentials-secret.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-s3-compatible-credentials-secret.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml, manifests/metering-config/s3-compatible-storage.yaml
edited Helm and Ansible to allow for S3 compatible storage like Noobaa
=> S3 compatible storage

Documentation/dev/developer-guide.md
=> Helm template doc add

Documentation/configuring-storage.md, charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml, charts/openshift-metering/templates/hadoop/hadoop-s3-compatible-ca-secret.yaml, charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml, charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml, charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml, charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml, charts/openshift-metering/templates/hive/hive-s3-compatible-ca-secret.yaml, charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml, charts/openshift-metering/templates/hive/hive-server-statefulset.yaml, charts/openshift-metering/templates/presto/_presto_helpers.tpl, charts/openshift-metering/templates/presto/presto-common-config.yaml, charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml, charts/openshift-metering/templates/presto/presto-s3-compatible-ca-secret.yaml, charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml, images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml, manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/ocp-testing/olm/bundle/4.2/meteringconfig.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.2/meteringconfig.crd.yaml, manifests/metering-config/s3-compatible-storage.yaml
See commit messages for details on individual changes.
Depends on:
- https://github.com/operator-framework/hadoop/pull/20
- https://github.com/operator-framework/hive/pull/14
- https://github.com/operator-framework/presto/pull/15
=> Support HTTPs with self-signed certs on s3Compatible storage endpoints

Documentation/hivetables.md
reporting-operator is the one that creates HiveTable resource
=> Update hivetables.md to use reporting-operator

Documentation/metering-architecture.md
=> Documentation: Fix architecture docs

Documentation/dev/noobaa.md
This is for developers/QE to begin testing NooBaa. This will be updated
more as NooBaa becomes GA.
=> Documentation/dev: Add developer documentation for using Metering with NooBaa

pkg/operator/deploy/create.go
This would result in the `openshift.io/cluster-monitoring=true` label being added to the `$METERING_NAMESPACE` namespace during an install:
```bash
[tflannag@localhost operator-metering]$ go run cmd/deploy/main.go install
INFO[09-17-2019 13:21:53] Setting the log level to info                 app=deploy
INFO[09-17-2019 13:21:53] Metering Deploy Namespace: metering-tflannag  app=deploy
INFO[09-17-2019 13:21:53] Metering Deploy Platform: openshift           app=deploy
INFO[09-17-2019 13:21:53] Labeling the metering-tflannag namespace with 'openshift.io/cluster-monitoring=true'  app=deploy
INFO[09-17-2019 13:21:53] Created the metering-tflannag namespace       app=deploy
INFO[09-17-2019 13:21:54] Updated the hivetables.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:54] Updated …
```
=> pkg/deploy: Add the cluster-monitoring label when creating an Openshift namespace.

charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
=> charts,manifests: Update documentation links in OCP OLM packages to use docs.openshift.com

pkg/operator/datasources.go
The status needs to reflect the latest state before we queue otherwise
there's a race between queuing and the status reflecting the changes
that the Report/ReportDataSource handler's checking the status.
=> pkg/operator: Queue Reports and ReportDataSource dependents of ReportDataSources after updating status

charts/metering-ansible-operator/ocp-testing-values.yaml, charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/ocp-testing/olm/bundle/metering.package.yaml, manifests/deploy/openshift/olm/bundle/metering.package.yaml, manifests/deploy/upstream/olm/bundle/metering.package.yaml
4.2 can be interpreted as a number, so quote the value to ensure it's a
string, as OLM and the CRD defines.
=> charts,manifests: Enforce OLM package channel name is a string

charts/metering-ansible-operator/templates/crds/hive.crd.yaml, charts/openshift-metering/templates/openshift-reporting/datasources/aws-datasources.yaml, charts/openshift-metering/templates/openshift-reporting/report-queries/aws-billing.yaml, manifests/deploy/ocp-testing/metering-ansible-operator/hive.crd.yaml, manifests/deploy/ocp-testing/olm/bundle/4.3/hive.crd.yaml, manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml, manifests/deploy/openshift/olm/bundle/4.3/hive.crd.yaml, manifests/deploy/openshift/telemeter/list.yaml, manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml, manifests/deploy/upstream/olm/bundle/4.3/hive.crd.yaml, pkg/operator/aws_usage_hive.go, pkg/operator/hivetables.go, pkg/operator/reporting/db.go
There's a number of distinct issues. See the commits for the individual fixes.
=> bug 1763303: Fix AWS billing ReportDataSource functionality

charts/openshift-metering/values.yaml
=> [release-4.2]: bug 1757551: charts/openshift-metering: Update cpu/memory usage promqueries to handle many to many matching error

images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py
Ansible Module to create and update Metering Events for debugging.
Moved over from ansible fork.
Need to comment.
Example of JSON user supplied args provided.
1. Need ansible installed
2. Need to be in venv
3. Separate install of `openshift` package required 
pip install openshift
4. To run
python -m <path to module>_mod <path to args>
=> K8s Event Creation Module

Documentation/install-metering.md
Correcting prometheus url configuration to point to appropriate page
=> Update prometheus URL configuration link

Documentation/metering-config.md
Updating s3 storage uri to point to correct section in the child page
=> Updating s3 storage uri in documentation

charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/metering.package.yaml, manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml, manifests/deploy/upstream/olm/bundle/4.4/hive.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/image-references, manifests/deploy/upstream/olm/bundle/4.4/meteringconfig.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.4/prestotable.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/report.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/reportdatasource.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/reportquery.crd.yaml, manifests/deploy/upstream/olm/bundle/4.4/storagelocation.crd.yaml, manifests/deploy/upstream/olm/bundle/metering.package.yaml
This is a partial update from 4.3 to 4.4 for the upstream package (which has the 4.4 tags) and the openshift package.yaml that ART uses to publish brew builds.
=> charts,manifests: Update the metering package bundle to 4.4.

charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.4/hive.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/image-references, manifests/deploy/openshift/olm/bundle/4.4/meteringconfig.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml, manifests/deploy/openshift/olm/bundle/4.4/prestotable.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/report.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/reportdatasource.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/reportquery.crd.yaml, manifests/deploy/openshift/olm/bundle/4.4/storagelocation.crd.yaml, manifests/deploy/openshift/olm/bundle/art.yaml
This is needed to generate brew builds for 4.4 OCP images.
=> charts,manifests: Update the art.yaml to 4.4.

Documentation/configuring-hive-metastore.md
Using the correct MeteringConfig spec for database configuration
=> Fix configuring-hive-metastore.md

Documentation/dev/debugging.md
This would attempt to add more clarity to the documentation, and highlight any important information as needed.
=> Documentation/dev: Update the debugging.md file.

Dockerfile.src
Reverts operator-framework/operator-metering#1084
=> Revert "Dockerfile.src: Bump the Go compiler to the 1.13 version."

Documentation/reports.md
Small error in reports.md I noticed.
=> Errant "the" removed

Documentation/install-metering.md
those 2 doc command are incorrect now, update with latest code
=> Fix doc for up-to-date settings

Documentation/dev/developer-guide.md
Description 
Updating reference link to point to correct file location
Motivation 
For better readability of documentation
=> Updating reference to yaml file in manifests folder

Documentation/hivetables.md
Including reference for documentation of hive partitioned tables
=> Adding reference to hive documentation of partitioned tables

Documentation/install-metering.md
Description 
Providing a reference to kubectl installation page in installing metering documentation
Motive 
Document review
=> Providing reference to kubectl setup documentation

Documentation/index.md
Description
Correcting navigation to exact subsection from index.md
Motive:
Document Review
=> Correction in index.md for s3 storage section

charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl, charts/openshift-metering/templates/presto/presto-coordinator-config.yaml, charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml, charts/openshift-metering/values.yaml, images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
This handles changes to reporting-operator and Presto
=> proxy enablement

Documentation/install-metering.md
=> Updating reference to latest kubeprometheus github

Documentation/dev/developer-guide.md
=> Removing testing ocp images section

Documentation/configuring-hive-metastore.md
Motive : Enhancing documentation
=> Providing reference to hive metastore objects from documentation

Documentation/install-metering.md
Motivation : Enhancing documentation
=> Providing reference to kube state metrics page

Documentation/tuning.md
=> Minor grammatical fixture

Documentation/metering-architecture.md
Replaces all references to Operator Metering with Metering Operator in `metering-architecture.md`
=> Fixes refs to Operator Metering architecture doc

pkg/deploy/install.go
In the case where a cluster administrator has configured the `defaultNodeSelector` field for the cluster's `Scheduler` object, which is responsible for determining the placement of Pods in a cluster, there may be conflicts when a user also specifies a `nodeSelector` configuration for the metering-operator's operands in the `MeteringConfig` object. Instead, if we always set the `'openshift.io/node-selector'` annotation to be empty, meaning that we don't care where the Pods in this namespace get scheduled, the `defaultNodeSelector` won't be injected by the Scheduler and the user-provided `nodeSelector` configuration will work as intended.
Note: these changes are only geared towards manually deploying Metering manually (e.g. deploy everything ourselves) and deploying Metering through OLM …
=> pkg/deploy: Add the empty openshift.io/node-selector annotation to the metering-operator namespace.

Documentation/tuning.md
=> Correcting case of software names

Documentation/dev/ocp-images.md
=> Minor typo fix

Documentation/dev/builds.md
Correcting the case of a word in documentation
=> Correcting case

Dockerfile.src
This will need to be force merged to take effect.
Slight mod to simplify for Dockerfile usage from the instructions for static Linux binary given here:
https://github.com/jzelinskie/faq
=> Get faq via static Linux binary

charts/openshift-metering/values.yaml
Still giving trouble with sporadic many-to-many PromQL error, so trying `group_right` swapped in for `group_left` in the original query.
=> Try group_right as less prone to many-to-many

pkg/deploy/deploy.go, pkg/deploy/install.go, pkg/deploy/uninstall.go
Eliminates most of the redundant if/else if/else structures, and updates the handling of non-nil errors.
=> pkg/deploy: Cleanup conditional structure in the top-level deploy methods.

hack/gather-test-install-artifacts.sh
As we continue to make improvements in the e2e testing suite, one of the more problematic areas is how we manage the process of storing testing results.
In the current implementation, we call this hack/gather-test-install-artifact.sh script while we teardown a specific metering instance.
When we take a look at overall test log output, we can see this process can take almost four minutes:
```
time="06-25-2020 15:21:51" level=info msg="Capturing pod descriptions" app=deploy component=cleanup
...
time="06-25-2020 15:25:25" level=info msg="Capturing metering-ocp packagemanifest description" app=deploy component=cleanup
```
If we instead switch to using the `oc adm inspect <resource>` utility to grab debugging information on things like the YAML resource spec, we can greatly lower the time it …
=> hack: Update the must-gather test artifacts script to use 'oc adm inspect'.

Documentation/configuring-reporting-operator.md
Add bold Styling to the warning text.
File: configuring-reporting-operator.md. 
Best Wishes, 
Dinakara Sai Santosh Burugupalli
=> addition of styling in Documentation/configuring-reporting-operator.md

Documentation/reportqueries.md
=> Remove an is

test/e2e/delete_s3_bucket_test.go
We've been seeing the following error in the e2e test logs recently:
```
--- FAIL: TestManualMeteringInstall/S3-ReportDynamicInputData/testEnsureS3BucketIsDeleted (3.46s)
delete_s3_bucket_test.go:44:
Error Trace:	delete_s3_bucket_test.go:44
metering_manual_install_tests.go:98
Error:      	Received unexpected error:
BucketNotEmpty: The bucket you tried to delete is not empty
status code: 409, request id: C8BBCA0B31687E41, host id: Ft4Tt7teHmz/Fxv2cP9IRs0RnCw5KNIKttizkx592BlsA9S9nqkVlhW0ryStlrvk1fzSlvBegf4=
Test:       	TestManualMeteringInstall/S3-ReportDynamicInputData/testEnsureS3BucketIsDeleted
Messages:   	failed to delete the metering-dev-e2e bucket
```
The call to batch delete all of the objects in a bucket happens in the background, so updating to use this client method where we …
=> test/e2e: Wait for the s3 bucket to be deleted.

Dockerfile.metering-ansible-operator.rhel8
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.
=> Add Dockerfile.metering-ansible-operator.rhel8

Documentation/dev/debugging.md
I've been using this locally for a while now but thought there was some value in documenting this in the debugging metering installation guides.
=> Documentation/dev: Add documentation for copying host binaries to a metering container to help debugging.

charts/metering-ansible-operator/upstream-values.yaml, charts/metering-ansible-operator/values.yaml, manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml, manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
=> charts,manifests: Update the upstream and downstream CSV descriptions.

pkg/operator/operator.go
Updates the `Reporting` structure, which is the structure of the controller type for the reporting-operator, adding the event recorder as a field. This recorder is used to relay events to the event broadcaster, but we can also proactively create events based on situations the reporting-operator encounters.
=> pkg/operator: Add the event recorder field to the Report structure.

Documentation/configuring-storage.md
@lbarbeevargas @timflannagan1 @bentito PTAL
=> document noobaa installation with metering

Makefile
```
$ make docker-build-all
podman build -f Dockerfile.reporting-operator -t quay.io/openshift/origin-metering-reporting-operator:4.6 /home/pweil/codebase/metering-operator/src/github.com/kube-reporting/metering-operator
STEP 1: FROM openshift/origin-release:golang-1.13 AS build
Getting image source signatures
Copying blob d42565390f9b done  
Copying blob 524b0c1e57f8 done  
Copying config 2e08ed6863 done  
Writing manifest to image destination
Storing signatures
STEP 2: COPY . /go/src/github.com/kube-reporting/metering-operator
--> 64fcfcbbf54
STEP 3: WORKDIR /go/src/github.com/kube-reporting/metering-operator
--> 467c435f146
STEP 4: ENV GOCACHE='/tmp'
--> e3343eb54a8
STEP 5: RUN make reporting-operator-bin RUN_UPDATE_CODEGEN=false CHECK_GO_FILES=false
make build-reporting-operator …
```
=> Allow using podman by passing in runtime var for systems without docker installed.

cmd/reporting-operator/start.go
Swap around the runReporting function parameters to have the context.Context argument come first.
Remove an unneeded function wrapper around adding cobra.Command(s) to the root command set.
=> cmd/reporting-operator: Minor changes to the main package

pkg/operator/reports.go
Update the pkg/operator/reports.go isReportFinished helper function, adding more general comments and deflating some of the if/else if/else conditionals to single if statements for better readability.
=> pkg/operator: Cleanup the isReportFinished helper function

Documentation/reports.md
Lindsey had written docs for downstream so just adding them verbatim to repo.
=> upstream reports expiration field docs

Documentation/configuring-aws-billing.md, Documentation/configuring-reporting-operator.md, Documentation/configuring-storage.md, Documentation/dev/builds.md, Documentation/dev/developer-guide.md, Documentation/dev/mirroring-ocp-images.md, Documentation/dev/noobaa.md, Documentation/dev/ocp-images.md, Documentation/index.md, Documentation/install-metering.md, Documentation/manual-olm-install.md, Documentation/metering-architecture.md, Documentation/metering-config.md, Documentation/olm-install.md, Documentation/prestotables.md, Documentation/reportdatasources.md, Documentation/reportqueries.md, Documentation/reports.md, Documentation/rollup-reports.md, Documentation/storagelocations.md, Documentation/troubleshooting-metering.md, Documentation/using-metering.md, Documentation/writing-custom-queries.md
- Add code block formatting.
- Add more consistency with newlines.
- Remove extra newlines.
=> Documentation: Minor documentation updates
